// Put all characters that can be a part of a word in the language, for example in English we have all upper and lower case alphabet letters as well as apostrophe "'".

#include "orca/normalizer/it/pv_normalizer_data_it/pv_normalizer_word_character_data_it.h"
#include "orca/normalizer/pv_normalizer_data/pv_normalizer_shared_data.h"
#include "orca/normalizer/pv_normalizer_language_data.h"

const char *const PV_NORMALIZER_WORD_CHARACTERS_IT[PV_NORMALIZER_NUM_WORD_CHARACTERS_IT] = {
        "A",
        "a",
        "B",
        "b",
        "C",
        "c",
        "D",
        "d",
        "E",
        "e",
        "F",
        "f",
        "G",
        "g",
        "H",
        "h",
        "I",
        "i",
        "J",
        "j",
        "K",
        "k",
        "L",
        "l",
        "M",
        "m",
        "N",
        "n",
        "O",
        "o",
        "P",
        "p",
        "Q",
        "q",
        "R",
        "r",
        "S",
        "s",
        "T",
        "t",
        "U",
        "u",
        "V",
        "v",
        "W",
        "w",
        "X",
        "x",
        "Y",
        "y",
        "Z",
        "z",
        "À",
        "à",
        "È",
        "è",
        "É",
        "é",
        "Ì",
        "ì",
        "Ò",
        "ò",
        "Ù",
        "ù",
        APOSTROPHE,
        //"-", // TODO (Ted): Could not determine if we should separate (i.e. pause when verbalizing) hyphenated Italian words. Comment this out for now to pass the integration test. Future decide on this.
};

const char *const PV_NORMALIZER_ALPHABET_CHARACTERS_IT[PV_NORMALIZER_NUM_ALPHABET_CHARACTERS_IT] = {
        "A",
        "a",
        "B",
        "b",
        "C",
        "c",
        "D",
        "d",
        "E",
        "e",
        "F",
        "f",
        "G",
        "g",
        "H",
        "h",
        "I",
        "i",
        "J",
        "j",
        "K",
        "k",
        "L",
        "l",
        "M",
        "m",
        "N",
        "n",
        "O",
        "o",
        "P",
        "p",
        "Q",
        "q",
        "R",
        "r",
        "S",
        "s",
        "T",
        "t",
        "U",
        "u",
        "V",
        "v",
        "W",
        "w",
        "X",
        "x",
        "Y",
        "y",
        "Z",
        "z",
        "À",
        "à",
        "È",
        "è",
        "É",
        "é",
        "Ì",
        "ì",
        "Ò",
        "ò",
        "Ù",
        "ù",
        //"-", // TODO (Ted): Could not determine if we should separate (i.e. pause when verbalizing) hyphenated Italian words. Comment this out for now to pass the integration test. Future decide on this.
};

const char *const PV_NORMALIZER_VOWELS_IT[PV_NORMALIZER_NUM_VOWELS_IT] = {
        "A",
        "a",
        "E",
        "e",
        "I",
        "i",
        "O",
        "o",
        "U",
        "u",
        "À",
        "à",
        "È",
        "è",
        "É",
        "é",
        "Ì",
        "ì",
        "Ò",
        "ò",
        "Ù",
        "ù",
};

const char PV_NORMALIZER_CONSONANTS_IT[PV_NORMALIZER_NUM_CONSONANTS_IT] = {
        'B',
        'b',
        'C',
        'c',
        'D',
        'd',
        'F',
        'f',
        'G',
        'g',
        'H',
        'h',
        'J',
        'j',
        'K',
        'k',
        'L',
        'l',
        'M',
        'm',
        'N',
        'n',
        'P',
        'p',
        'Q',
        'q',
        'R',
        'r',
        'S',
        's',
        'T',
        't',
        'V',
        'v',
        'W',
        'w',
        'X',
        'x',
        'Y',
        'y',
        'Z',
        'z',
};

const char *const PV_ORCA_PHONEMIZER_IT_ALPHABET_UPPERCASE_LETTERS[PV_ORCA_PHONEMIZER_IT_ALPHABET_NUM_LETTERS] = {
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
        "À",
        "È",
        "É",
        "Ì",
        "Ò",
        "Ù",
};

const char *const PV_ORCA_PHONEMIZER_IT_ALPHABET_PRONUNCIATIONS[PV_ORCA_PHONEMIZER_IT_ALPHABET_NUM_LETTERS] = {
        "a",
        "b i",
        "tʃ i",
        "d i",
        "e",
        "ɛ f f e",
        "dʒ i",
        "a k k a",
        "i",
        "i l u ŋ g a",
        "k a p p a",
        "ɛ l l e",
        "e m m e",
        "ɛ n n e",
        "o",
        "p i",
        "k u",
        "ɛ rr e",
        "e s s e",
        "t i",
        "u",
        "v i",
        "d o p p j a v i",
        "i k s",
        "i p s i l o n",
        "dz ɛ t a",
        "a",
        "ɛ",
        "e",
        "i",
        "ɔ",
        "u",
};

const char *PV_ORCA_STREAM_IT_EOS_PUNCTUATIONS[] = {".", "?", "!"};
const char *PV_ORCA_STREAM_IT_FALLBACK_CUTOFF_CHARACTERS[] = {":", ","};


