#include <stdbool.h>

#include "orca/normalizer/it/pv_normalizer_data_it/pv_normalizer_measurement_data_it.h"

const char *const PV_NORMALIZER_MEASUREMENTS_IT[PV_NORMALIZER_NUM_MEASUREMENTS_IT] = {
        "°",
        "º",

        "°C",
        "ºC",
        "°F",
        "ºF",

        "M",
        "M2",
        "M²",
        "M3",
        "M³",
        "CM",
        "CM2",
        "CM²",
        "CM3",
        "CM³",
        "MM",
        "MM2",
        "MM²",
        "MM3",
        "MM³",
        "KM",
        "KM2",
        "KM²",
        "KM3",
        "KM³",
        "DM",
        "DM2",
        "DM²",
        "DM3",
        "DM³",

        "FT",
        "FT2",
        "FT²",
        "FT3",
        "FT³",
        "YD",
        "YD2",
        "YD²",
        "YD3",
        "YD³",
        "MI",
        "MI2",
        "MI²",
        "MI3",
        "MI³",

        "G",
        "KG",
        "MG",

        "OZ",
        "LB",
        "LBS",

        "L",
        "ML",

        "GAL",
        "QT",
        "PT",

        "S",
        "MIN",
        "H",

        "KB",
        "MB",
        "GB",
        "TB",
        "PB",
        "EB",
        "ZB",
        "YB",

        "KBPS",
        "MBPS",

        "HZ",
        "MHZ",
        "GHZ",
        "THZ",

        "KW",
        "MW",
        "GW",
        "TW",
        "PW",

        "KWH",
        "MWH",
        "GWH",
        "TWH",
        "PWH",

        "PA",
        "KPA",

        "V",
        "KV",

        "RPM",
        "KCAL",
        "DB",
        "RAD",
};

const char *const PV_NORMALIZER_MEASUREMENTS_VERBALIZED_SINGULAR_IT[PV_NORMALIZER_NUM_MEASUREMENTS_IT] = {
        "GRADO",
        "GRADO",

        "GRADO CELSIUS",
        "GRADO CELSIUS",
        "GRADO FAHRENHEIT",
        "GRADO FAHRENHEIT",

        "METRO",
        "METRO QUADRATO",
        "METRO QUADRATO",
        "METRO CUBO",
        "METRO CUBO",
        "CENTIMETRO",
        "CENTIMETRO QUADRATO",
        "CENTIMETRO QUADRATO",
        "CENTIMETRO CUBO",
        "CENTIMETRO CUBO",
        "MILLIMETRO",
        "MILLIMETRO QUADRATO",
        "MILLIMETRO QUADRATO",
        "MILLIMETRO CUBO",
        "MILLIMETRO CUBO",
        "CHILOMETRO",
        "CHILOMETRO QUADRATO",
        "CHILOMETRO QUADRATO",
        "CHILOMETRO CUBO",
        "CHILOMETRO CUBO",
        "DECIMETRO",
        "DECIMETRO QUADRATO",
        "DECIMETRO QUADRATO",
        "DECIMETRO CUBO",
        "DECIMETRO CUBO",

        "PIEDE",
        "PIEDE QUADRATO",
        "PIEDE QUADRATO",
        "PIEDE CUBO",
        "PIEDE CUBO",
        "IARDA",
        "IARDA QUADRATA",
        "IARDA QUADRATA",
        "IARDA CUBA",
        "IARDA CUBA",
        "MIGLIO",
        "MIGLIO QUADRATO",
        "MIGLIO QUADRATO",
        "MIGLIO CUBO",
        "MIGLIO CUBO",

        "GRAMMO",
        "CHILOGRAMMO",
        "MILLIGRAMMO",

        "ONCIA",
        "LIBBRA",
        "LIBBRA",

        "LITRO",
        "MILLILITRO",

        "GALLONE",
        "QUARTO",
        "PINTA",

        "SECONDO",
        "MINUTO",
        "ORA",

        "KILOBYTE",
        "MEGABYTE",
        "GIGABYTE",
        "TERABYTE",
        "PETABYTE",
        "EXABYTE",
        "ZETTABYTE",
        "YOTTABYTE",

        "KILOBIT AL SECONDO",
        "MEGABIT AL SECONDO",

        "HERTZ",
        "MEGAHERTZ",
        "GIGAHERTZ",
        "TERAHERTZ",

        "KILOWATT",
        "MEGAWATT",
        "GIGAWATT",
        "TERAWATT",
        "PETAWATT",

        "KILOWATTORA",
        "MEGAWATTORA",
        "GIGAWATTORA",
        "TERAWATTORA",
        "PETAWATTORA",

        "PASCAL",
        "KILOPASCAL",

        "VOLT",
        "KILOVOLT",

        "GIRI AL MINUTO",
        "KILOCALORIA",
        "DECIBEL",
        "RADIANO",
};

const char *const PV_NORMALIZER_MEASUREMENTS_VERBALIZED_PLURAL_IT[PV_NORMALIZER_NUM_MEASUREMENTS_IT] = {
        "GRADI",
        "GRADI",

        "GRADI CELSIUS",
        "GRADI CELSIUS",
        "GRADI FAHRENHEIT",
        "GRADI FAHRENHEIT",

        "METRI",
        "METRI QUADRATI",
        "METRI QUADRATI",
        "METRI CUBI",
        "METRI CUBI",
        "CENTIMETRI",
        "CENTIMETRI QUADRATI",
        "CENTIMETRI QUADRATI",
        "CENTIMETRI CUBI",
        "CENTIMETRI CUBI",
        "MILLIMETRI",
        "MILLIMETRI QUADRATI",
        "MILLIMETRI QUADRATI",
        "MILLIMETRI CUBI",
        "MILLIMETRI CUBI",
        "CHILOMETRI",
        "CHILOMETRI QUADRATI",
        "CHILOMETRI QUADRATI",
        "CHILOMETRI CUBI",
        "CHILOMETRI CUBI",
        "DECIMETRI",
        "DECIMETRI QUADRATI",
        "DECIMETRI QUADRATI",
        "DECIMETRI CUBI",
        "DECIMETRI CUBI",

        "PIEDI",
        "PIEDI QUADRATI",
        "PIEDI QUADRATI",
        "PIEDI CUBI",
        "PIEDI CUBI",
        "IARDE",
        "IARDE QUADRATE",
        "IARDE QUADRATE",
        "IARDE CUBE",
        "IARDE CUBE",
        "MIGLIA",
        "MIGLIA QUADRATE",
        "MIGLIA QUADRATE",
        "MIGLIA CUBI",
        "MIGLIA CUBI",

        "GRAMMI",
        "CHILOGRAMMI",
        "MILLIGRAMMI",

        "ONCE",
        "LIBBRE",
        "LIBBRE",

        "LITRI",
        "MILLILITRI",

        "GALLONI",
        "QUARTI",
        "PINTE",

        "SECONDI",
        "MINUTI",
        "ORE",

        "KILOBYTE",
        "MEGABYTE",
        "GIGABYTE",
        "TERABYTE",
        "PETABYTE",
        "EXABYTE",
        "ZETTABYTE",
        "YOTTABYTE",

        "KILOBIT AL SECONDO",
        "MEGABIT AL SECONDO",

        "HERTZ",
        "MEGAHERTZ",
        "GIGAHERTZ",
        "TERAHERTZ",

        "KILOWATT",
        "MEGAWATT",
        "GIGAWATT",
        "TERAWATT",
        "PETAWATT",

        "KILOWATTORA",
        "MEGAWATTORA",
        "GIGAWATTORA",
        "TERAWATTORA",
        "PETAWATTORA",

        "PASCAL",
        "KILOPASCAL",

        "VOLT",
        "KILOVOLT",

        "GIRI AL MINUTO",
        "KILOCALORIE",
        "DECIBEL",
        "RADIANTI",
};
