#include "orca/normalizer/it/pv_normalizer_data_it/pv_normalizer_number_data_it.h"

const int64_t MAX_VERBALIZED_CARDINAL_IT = 1000000000000000 - 1; // 1 quadrillion

const int64_t MAX_MULTIPLIER_IT = 1000000000000; // 1 trillion
const char *NUMBER_RANGE_INBETWEEN_STRING_IT = "A";


const char *const ZERO_TO_NINETY_NINE_ACCENTED_IT[100] = {
        "ZERO", "UNO", "DUE", "TRE", "QUATTRO", "CINQUE", "SEI", "SETTE", "OTTO", "NOVE", "DIECI",
        "UNDICI", "DODICI", "TREDICI", "QUATTORDICI", "QUINDICI", "SEDICI", "DICIASSETTE", "DICIOTTO", "DICIANNOVE", "VENTI",
        "VENTUNO", "VENTIDUE", "VENTITRÉ", "VENTIQUATTRO", "VENTICINQUE", "VENTISEI", "VENTISETTE", "VENTOTTO", "VENTINOVE", "TRENTA",
        "TRENTUNO", "TRENTADUE", "TRENTATRÉ", "TRENTAQUATTRO", "TRENTACINQUE", "TRENTASEI", "TRENTASETTE", "TRENTOTTO", "TRENTANOVE", "QUARANTA",
        "QUARANTUNO", "QUARANTADUE", "QUARANTATRÉ", "QUARANTAQUATTRO", "QUARANTACINQUE", "QUARANTASEI", "QUARANTASETTE", "QUARANTOTTO", "QUARANTANOVE", "CINQUANTA",
        "CINQUANTUNO", "CINQUANTADUE", "CINQUANTATRÉ", "CINQUANTAQUATTRO", "CINQUANTACINQUE", "CINQUANTASEI", "CINQUANTASETTE", "CINQUANTOTTO", "CINQUANTANOVE", "SESSANTA",
        "SESSANTUNO", "SESSANTADUE", "SESSANTATRÉ", "SESSANTAQUATTRO", "SESSANTACINQUE", "SESSANTASEI", "SESSANTASETTE", "SESSANTOTTO", "SESSANTANOVE", "SETTANTA",
        "SETTANTUNO", "SETTANTADUE", "SETTANTATRÉ", "SETTANTAQUATTRO", "SETTANTACINQUE", "SETTANTASEI", "SETTANTASETTE", "SETTANTOTTO", "SETTANTANOVE", "OTTANTA",
        "OTTANTUNO", "OTTANTADUE", "OTTANTATRÉ", "OTTANTAQUATTRO", "OTTANTACINQUE", "OTTANTASEI", "OTTANTASETTE", "OTTANTOTTO", "OTTANTANOVE", "NOVANTA",
        "NOVANTUNO", "NOVANTADUE", "NOVANTATRÉ", "NOVANTAQUATTRO", "NOVANTACINQUE", "NOVANTASEI", "NOVANTASETTE", "NOVANTOTTO", "NOVANTANOVE"};

const char *const ZERO_TO_NINETY_NINE_NON_ACCENTED_IT[100] = { // In case where the accented "É" occurs in the middle of the word, then we un-accented it.
        "ZERO", "UNO", "DUE", "TRE", "QUATTRO", "CINQUE", "SEI", "SETTE", "OTTO", "NOVE", "DIECI",
        "UNDICI", "DODICI", "TREDICI", "QUATTORDICI", "QUINDICI", "SEDICI", "DICIASSETTE", "DICIOTTO", "DICIANNOVE", "VENTI",
        "VENTUNO", "VENTIDUE", "VENTITRE", "VENTIQUATTRO", "VENTICINQUE", "VENTISEI", "VENTISETTE", "VENTOTTO", "VENTINOVE", "TRENTA",
        "TRENTUNO", "TRENTADUE", "TRENTATRE", "TRENTAQUATTRO", "TRENTACINQUE", "TRENTASEI", "TRENTASETTE", "TRENTOTTO", "TRENTANOVE", "QUARANTA",
        "QUARANTUNO", "QUARANTADUE", "QUARANTATRE", "QUARANTAQUATTRO", "QUARANTACINQUE", "QUARANTASEI", "QUARANTASETTE", "QUARANTOTTO", "QUARANTANOVE", "CINQUANTA",
        "CINQUANTUNO", "CINQUANTADUE", "CINQUANTATRE", "CINQUANTAQUATTRO", "CINQUANTACINQUE", "CINQUANTASEI", "CINQUANTASETTE", "CINQUANTOTTO", "CINQUANTANOVE", "SESSANTA",
        "SESSANTUNO", "SESSANTADUE", "SESSANTATRE", "SESSANTAQUATTRO", "SESSANTACINQUE", "SESSANTASEI", "SESSANTASETTE", "SESSANTOTTO", "SESSANTANOVE", "SETTANTA",
        "SETTANTUNO", "SETTANTADUE", "SETTANTATRE", "SETTANTAQUATTRO", "SETTANTACINQUE", "SETTANTASEI", "SETTANTASETTE", "SETTANTOTTO", "SETTANTANOVE", "OTTANTA",
        "OTTANTUNO", "OTTANTADUE", "OTTANTATRE", "OTTANTAQUATTRO", "OTTANTACINQUE", "OTTANTASEI", "OTTANTASETTE", "OTTANTOTTO", "OTTANTANOVE", "NOVANTA",
        "NOVANTUNO", "NOVANTADUE", "NOVANTATRE", "NOVANTAQUATTRO", "NOVANTACINQUE", "NOVANTASEI", "NOVANTASETTE", "NOVANTOTTO", "NOVANTANOVE"};

const char *const MULTIPLIERS_SINGULAR_IT[5] = {"", "BILIONE", "MILIARDO", "MILIONE", "MILLE"}; // "" is placeholder.
const char *const MULTIPLIERS_PLURAL_IT[5] = {"", "BILIONI", "MILIARDI", "MILIONI", "MILA"};

const char HUNDRED_IT[] = "CENTO";
const char ONE_MASCULINE_IT[] = "UN";

const char UN[] = "UN";
const char UNO[] = "UNO";
const char UNA[] = "UNA";
const char UN_APOSTROPHE[] = "UN'";

const char ORDINAL_SUFFIX_MASCULINE_IT[] = "ESIMO";
const char ORDINAL_SUFFIX_FEMININE_IT[] = "ESIMA";

const int32_t ORDINAL_SUFFIX_MASCULINE_LENGTH_IT = 5;
const int32_t ORDINAL_SUFFIX_FEMININE_LENGTH_IT = 5;

const char *const ORDINAL_KEYS_IT[PV_NORMALIZER_NUM_ORDINALS_IT] = {
        "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "1000", "1000000", "1000000000", "1000000000000"};
const char *const ORDINAL_VALUES_MASCULINE_IT[PV_NORMALIZER_NUM_ORDINALS_IT] = {
        "ZERO", "PRIMO", "SECONDO", "TERZO", "QUARTO", "QUINTO", "SESTO", "SETTIMO", "OTTAVO", "NONO", "DECIMO", "MILLESIMO", "MILIONESIMO", "MILIARDESIMO", "BILIONESIMO"};
const char *const ORDINAL_VALUES_FEMININE_IT[PV_NORMALIZER_NUM_ORDINALS_IT] = {
        "ZERO", "PRIMA", "SECONDA", "TERZA", "QUARTA", "QUINTA", "SESTA", "SETTIMA", "OTTAVA", "NONA", "DECIMA", "MILLESIMA", "MILIONESIMA", "MILIARDESIMA", "BILIONESIMA"};

const char *const DENOMINATOR_ORDINAL_KEYS_IT[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_IT] = {
        "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"};
const char *const DENOMINATOR_ORDINAL_VALUES_SINGULAR_IT[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_IT] = {
        "INTERO", "MEZZO", "TERZO", "QUARTO", "QUINTO", "SESTO", "SETTIMO", "OTTAVO", "NONO", "DECIMO"};
const char *const DENOMINATOR_ORDINAL_VALUES_PLURAL_IT[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_IT] = {
        "INTERI", "MEZZI", "TERZI", "QUARTI", "QUINTI", "SESTI", "SETTIMI", "OTTAVI", "NONI", "DECIMI"};
