#include "orca/normalizer/it/pv_normalizer_data_it/pv_normalizer_special_character_data_it.h"
#include "orca/normalizer/pv_normalizer_data/pv_normalizer_shared_data.h"
#include <stdbool.h>

const char *const PV_NORMALIZER_SPECIAL_CHARACTERS_IT[PV_NORMALIZER_NUM_SPECIAL_CHARACTERS_IT] = {
        // Need to put compound special character in front of singleton special character! E.g. "°C" in front of "°".
        "°C",
        "ºC",
        "°F",
        "ºF",
        "M²",
        "M³",
        "CM²",
        "CM³",
        "MM²",
        "MM³",
        "KM²",
        "KM³",
        "DM²",
        "DM³",
        "FT²",
        "FT³",
        "YD²",
        "YD³",
        "MI²",
        "MI³",
        "KBPS",
        "MBPS",
        "MHZ",
        "GHZ",
        "RPM",
        "KCAL",
        "+",
        "=",
        "/",
        "ª", // Italian feminine ordinal abbreviation.
        "#",

        "@",
        "%",
        "&",
        "\n",
        "_",
        "(",
        ")",
        "°", // Italian masculine ordinal abbreviation.
        "º", // Italian masculine ordinal abbreviation.
        EM_DASH,
        HORIZONTAL_BAR,
        HORIZONTAL_ELLIPSIS,
        RIGHT_DOUBLE_QUOTATION_MARK,
        LEFT_DOUBLE_QUOTATION_MARK,
};

const char *const PV_NORMALIZER_SPECIAL_CHARACTERS_VERBALIZED_IT[PV_NORMALIZER_NUM_SPECIAL_CHARACTERS_IT] = {
        "GRADI CELSIUS",
        "GRADI CELSIUS MASCHILE",
        "GRADI FAHRENHEIT",
        "GRADI FAHRENHEIT MASCHILE",
        "METRI QUADRATI",
        "METRI CUBI",
        "CENTIMETRI QUADRATI",
        "CENTIMETRI CUBI",
        "MILLIMETRI QUADRATI",
        "MILLIMETRI CUBI",
        "CHILOMETRI QUADRATI",
        "CHILOMETRI CUBI",
        "DECIMETRI QUADRATI",
        "DECIMETRI CUBI",
        "PIEDI QUADRATI",
        "PIEDI CUBI",
        "IARDE QUADRATI",
        "IARDE CUBI",
        "MIGLIA QUADRATI",
        "MIGLIA CUBI",
        "KILOBIT PER SECONDO",
        "MEGABIT PER SECONDO",
        "MEGAHERTZ",
        "GIGAHERTZ",
        "GIRI AL MINUTO",
        "CHILOCALORIE",
        "PIÙ",
        "UGUALE",
        "BARRA",
        "A FEMMINILE",
        "CANCELLETTO",

        "CHIOCCIOLA",
        "PER CENTO",
        "E",
        ".",
        "TRATTINO BASSO",
        ",",
        ",",
        "GRADO",
        "GRADO MASCHILE",
        ",",
        ",",
        ".",
        "\"",
        "\"",
};

bool const PV_NORMALIZER_SPECIAL_CHARACTERS_IS_VERBALIZED_TO_PUNCTUATION_IT[PV_NORMALIZER_NUM_SPECIAL_CHARACTERS_IT] = {
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,

        false,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
};
