#include "orca/normalizer/it/pv_normalizer_data_it/pv_normalizer_currency_data_it.h"

const char *const PV_NORMALIZER_CURRENCIES_IT[PV_NORMALIZER_NUM_CURRENCIES_IT] = {
        "$",
        "€",
        "¥", // Note: JPY and CNY use the same unicode symbol. Currently verbalizes to YUAN
        "₪",
        "£",
        "₩",
        "₺",
        "₱",
        "₽",
        "฿",
        "₴",
        "₹",
        "¢",

        "USD",
        "EUR",
        "CAD",
        "JPY",
        "GBP",
        "AUD",
        "CHF",
        "CNY",
        "SEK",
        "NZD",
        "MXN",
        "SGD",
        "HKD",
        "NOK",
        "KRW",
        "TRY",
        "RUB",
        "INR",
        "BRL",
        "ZAR",
        "DKK",
        "PLN",
        "THB",
        "IDR",
        "MYR",
        "CZK",
        "HUF",
        "ILS",
        "ARS",
        "PHP",
        "CLP",
        "COP",
        "EGP",
        "SAR",
        "AED",
        "KWD",
        "PKR",
        "BDT",
        "NGN",
        "VES",
};

const char *const PV_NORMALIZER_CURRENCIES_VERBALIZED_SINGULAR_IT[PV_NORMALIZER_NUM_CURRENCIES_IT] = {
        "DOLLARO",
        "EURO",
        "YUAN",
        "SHEKEL",
        "STERLINA",
        "WON",
        "LIRA",
        "PESO",
        "RUBLO",
        "BAHT",
        "GRIVNIA",
        "RUPIA",
        "CENTESIMO",

        "DOLLARO USA",
        "EURO",
        "DOLLARO CANADESE",
        "YEN GIAPPONESE",
        "STERLINA BRITANNICA",
        "DOLLARO AUSTRALIANO",
        "FRANCO SVIZZERO",
        "YUAN CINESE",
        "CORONA SVEDESE",
        "DOLLARO NEOZELANDESE",
        "PESO MESSICANO",
        "DOLLARO SINGAPOREANO",
        "DOLLARO DI HONG KONG",
        "CORONA NORVEGESE",
        "WON COREANO",
        "LIRA TURCA",
        "RUBLO RUSSO",
        "RUPIA INDIANA",
        "REAL BRASILIANO",
        "RAND SUDAFRICANO",
        "CORONA DANESE",
        "ZLOTY POLACCO",
        "BAHT THAILANDESE",
        "RUPIA INDONESIANA",
        "RINGGIT MALESE",
        "CORONA CECA",
        "FIORINO UNGERESE",
        "SHEKEL ISRAELIANO",
        "PESO ARGENTINO",
        "PESO FILIPPINO",
        "PESO CILENO",
        "PESO COLOMBIANO",
        "STERLINA EGIZIANA",
        "RIYAL SAUDITA",
        "DIRHAM",
        "DINARO KUWAITANO",
        "RUPIA PAKISTANA",
        "TAKA BANGLADESE",
        "NAIRA NIGERIANA",
        "BOLIVAR VENEZUELANO",
};

const char *const PV_NORMALIZER_CURRENCIES_VERBALIZED_PLURAL_IT[PV_NORMALIZER_NUM_CURRENCIES_IT] = {
        "DOLLARI",
        "EURO",
        "YUAN",
        "SHEKELIM",
        "STERLINE",
        "WON",
        "LIRE",
        "PESOS",
        "RUBLI",
        "BAHT",
        "GRIVNIE",
        "RUPIE",
        "CENTESIMI",

        "DOLLARI USA",
        "EURO",
        "DOLLARI CANADESI",
        "YEN GIAPPONESI",
        "STERLINE BRITANNICHE",
        "DOLLARI AUSTRALIANI",
        "FRANCHI SVIZZERI",
        "YUAN CINESI",
        "CORONE SVEDESI",
        "DOLLARI NEOZELANDESI",
        "PESI MESSICANI",
        "DOLLARI SINGAPOREANI",
        "DOLLARI DI HONG KONG",
        "CORONE NORVEGESI",
        "WON COREANI",
        "LIRE TURCHE",
        "RUBLI RUSSI",
        "RUPIE INDIANE",
        "REAIS BRASILIANI",
        "RAND SUDAFRICANI",
        "CORONE DANESI",
        "ZLOTY POLACCHI",
        "BAHT THAILANDESI",
        "RUPIE INDONESIANE",
        "RINGGIT MALESI",
        "CORONE CECHE",
        "FIORINI UNGERESI",
        "SHEKELIM ISRAELIANE",
        "PESI ARGENTINI",
        "PESI FILIPPINI",
        "PESI CILENI",
        "PESI COLOMBIANI",
        "STERLINE EGIZIANE",
        "RIAL SAUDITI",
        "DIRHAM",
        "DINARI KUWAITANI",
        "RUPIE PAKISTANE",
        "TAKA BANGLADESI",
        "NAIRE NIGERIANE",
        "BOLIVARI VENEZUELANI",
};

const char *const PV_NORMALIZER_SUB_CURRENCIES_VERBALIZED_SINGULAR_IT[PV_NORMALIZER_NUM_CURRENCIES_IT] = {
        "CENTESIMO",
        "CENTESIMO",
        "FEN",
        "AGOROT",
        "PENNY",
        "JEON",
        "KURUS",
        "CENTAVO",
        "KOPEK",
        "SATANG",
        "KOPIYKA",
        "PAISA",
        "",

        "CENTESIMO",
        "CENTESIMO",
        "CENTESIMO",
        "SEN",
        "PENNY",
        "CENTESIMO",
        "CENTESIMO",
        "FEN",
        "ORE",
        "CENTESIMO",
        "CENTAVO",
        "CENTESIMO",
        "CENTESIMO",
        "ORE",
        "JEON",
        "KURUS",
        "KOPEK",
        "PAISA",
        "CENTAVO",
        "CENTESIMO",
        "ORE",
        "GROSZ",
        "SATANG",
        "SEN",
        "SEN",
        "HALER",
        "FILLER",
        "AGOROT",
        "CENTAVO",
        "SENTIMO",
        "CENTAVO",
        "CENTAVO",
        "PIASTRE",
        "HALALA",
        "FILS",
        "FILS",
        "PAISA",
        "POISHA",
        "KOBO",
        "CENTESIMO",
};

const char *const PV_NORMALIZER_SUB_CURRENCIES_VERBALIZED_PLURAL_IT[PV_NORMALIZER_NUM_CURRENCIES_IT] = {
        "CENTESIMI",
        "CENTESIMI",
        "FEN",
        "AGOROT",
        "PENCE",
        "JEON",
        "KURUS",
        "CENTAVOS",
        "KOPEK",
        "SATANG",
        "KOPIYKY",
        "PAISE",
        "",

        "CENTESIMI",
        "CENTESIMI",
        "CENTESIMI",
        "SEN",
        "PENCE",
        "CENTESIMI",
        "CENTESIMI",
        "FEN",
        "ORE",
        "CENTESIMI",
        "CENTAVOS",
        "CENTESIMI",
        "CENTESIMI",
        "ORE",
        "JEON",
        "KURUS",
        "KOPEK",
        "PAISE",
        "CENTAVOS",
        "CENTESIMI",
        "ORE",
        "GROSZY",
        "SATANG",
        "SEN",
        "SEN",
        "HALERE",
        "FILLER",
        "AGOROT",
        "CENTAVOS",
        "SENTIMOS",
        "CENTAVOS",
        "CENTAVOS",
        "PIASTRE",
        "HALALAT",
        "FILS",
        "FILS",
        "PAISE",
        "POISHA",
        "KOBO",
        "CENTESIMI",
};

