#include "orca/normalizer/ja/pv_normalizer_use_cases_ja.h"

const pv_normalizer_use_cases_ja_t ALL_USE_CASES_JA[PV_NORMALIZER_NUM_CASES_JA] = {
        PV_NORMALIZER_USE_WORD_NORMALIZER_JA,
        PV_NORMALIZER_USE_CUSTOM_PRONUNCIATION_NORMALIZER_JA,
        PV_NORMALIZER_USE_PUNCTUATION_NORMALIZER_JA,
        PV_NORMALIZER_USE_CARDINAL_NORMALIZER_JA,
        PV_NORMALIZER_USE_NEGATIVE_CARDINAL_NORMALIZER_JA,
        PV_NORMALIZER_USE_NUMBER_RANGE_NORMALIZER_JA,
        PV_NORMALIZER_USE_SPECIAL_CHARACTER_NORMALIZER_JA,
        PV_NORMALIZER_USE_DECIMAL_NORMALIZER_JA,
        PV_NORMALIZER_USE_ALPHANUM_SPELL_OUT_NORMALIZER_JA,
        PV_NORMALIZER_USE_MEASUREMENT_NORMALIZER_JA,
        PV_NORMALIZER_USE_TIME_NORMALIZER_JA,
        PV_NORMALIZER_USE_FRACTION_NORMALIZER_JA,
        PV_NORMALIZER_USE_URL_NORMALIZER_JA,
        PV_NORMALIZER_USE_CURRENCY_NORMALIZER_JA,
        PV_NORMALIZER_USE_ABBREVIATION_NORMALIZER_JA,
        PV_NORMALIZER_USE_DIGITS_SEQUENCE_NORMALIZER_JA,
        PV_NORMALIZER_USE_DATE_NORMALIZER_JA,
        PV_NORMALIZER_USE_NAME_NORMALIZER_JA,
};
