variables:
  GIT_SUBMODULE_STRATEGY: normal
  PV_PEER_MODULE_DIR: ../peer-modules
  TAGGED_BRANCH: '/^v[0-9]+\.[0-9]+.*-(patches)$/'

default:
  artifacts:
    expire_in: 7 days

stages:
  - build-beta
  - perf-beta
  - test-beta
  - build-prod
  - test-prod
  - collect-artifacts
  - util

include:
  - local: 'gitlab-ci/stage-build-test-beta.yml'
  - local: 'gitlab-ci/stage-build-test-prod.yml'
  - local: 'gitlab-ci/stage-collect-artifacts.yml'
  - local: 'gitlab-ci/stage-util.yml'
