// Put all characters that can be a part of a word in the language, for example in English we have all upper and lower case alphabet letters as well as apostrophe "'".

#include "orca/normalizer/en/pv_normalizer_data_en/pv_normalizer_word_character_data_en.h"
#include "orca/normalizer/pv_normalizer_data/pv_normalizer_shared_data.h"
#include "orca/normalizer/pv_normalizer_language_data.h"

const char *const PV_NORMALIZER_WORD_CHARACTERS_EN[PV_NORMALIZER_NUM_WORD_CHARACTERS_EN] = {
        "a",
        "b",
        "c",
        "d",
        "e",
        "f",
        "g",
        "h",
        "i",
        "j",
        "k",
        "l",
        "m",
        "n",
        "o",
        "p",
        "q",
        "r",
        "s",
        "t",
        "u",
        "v",
        "w",
        "x",
        "y",
        "z",
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
        APOSTROPHE,
};

const char *const PV_NORMALIZER_ALPHABET_CHARACTERS_EN[PV_NORMALIZER_NUM_ALPHABET_CHARACTERS_EN] = {
        "a",
        "b",
        "c",
        "d",
        "e",
        "f",
        "g",
        "h",
        "i",
        "j",
        "k",
        "l",
        "m",
        "n",
        "o",
        "p",
        "q",
        "r",
        "s",
        "t",
        "u",
        "v",
        "w",
        "x",
        "y",
        "z",
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
};

const char *const PV_ORCA_PHONEMIZER_EN_ALPHABET_UPPERCASE_LETTERS[PV_ORCA_PHONEMIZER_EN_ALPHABET_NUM_LETTERS] = {
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
};

const char *const PV_ORCA_PHONEMIZER_EN_ALPHABET_PRONUNCIATIONS[PV_ORCA_PHONEMIZER_EN_ALPHABET_NUM_LETTERS] = {
        "EY",
        "B IY",
        "S IY",
        "D IY",
        "IY",
        "EH F",
        "JH IY",
        "EY CH",
        "AY",
        "JH EY",
        "K EY",
        "EH L",
        "EH M",
        "EH N",
        "OW",
        "P IY",
        "K Y UW",
        "AA R",
        "EH S",
        "T IY",
        "Y UW",
        "V IY",
        "D AH B AH L Y UW",
        "EH K S",
        "W AY",
        "Z IY",
};

const char *PV_ORCA_STREAM_EN_EOS_PUNCTUATIONS[] = {"?", "!"};
const char *PV_ORCA_STREAM_EN_FALLBACK_CUTOFF_CHARACTERS[] = {":", ","};


