#include <stdbool.h>

#include "orca/normalizer/en/pv_normalizer_data_en/pv_normalizer_special_character_data_en.h"
#include "orca/normalizer/pv_normalizer_data/pv_normalizer_shared_data.h"

const char *const PV_NORMALIZER_SPECIAL_CHARACTERS[PV_NORMALIZER_NUM_SPECIAL_CHARACTERS] = {
        "@",
        "%",
        "&",
        "\n",
        "_",
        "(",
        ")",
        "°C",
        "ºC",
        "°F",
        "ºF",
        "°",
        "º",
        "M²",
        "M³",
        "CM²",
        "CM³",
        "MM²",
        "MM³",
        "KM²",
        "KM³",
        "DM²",
        "DM³",
        "FT²",
        "FT³",
        "YD²",
        "YD³",
        "MI²",
        "MI³",
        "KBPS",
        "MBPS",
        "MHZ",
        "GHZ",
        "RPM",
        "KCAL",
        "+",
        "=",
        "/",
        "#",
        EM_DASH,
        HORIZONTAL_BAR,
        HORIZONTAL_ELLIPSIS,
        RIGHT_DOUBLE_QUOTATION_MARK,
        LEFT_DOUBLE_QUOTATION_MARK,
};

const char *const PV_NORMALIZER_SPECIAL_CHARACTERS_VERBALIZED[PV_NORMALIZER_NUM_SPECIAL_CHARACTERS] = {
        "AT",
        "PERCENT",
        "AND",
        ".",
        "UNDERSCORE",
        ",",
        ",",
        "DEGREES CELSIUS",
        "DEGREES CELSIUS",
        "DEGREES FAHRENHEIT",
        "DEGREES FAHRENHEIT",
        "DEGREES",
        "DEGREES",
        "SQUARE METERS",
        "CUBIC METERS",
        "SQUARE CENTIMETERS",
        "CUBIC CENTIMETERS",
        "SQUARE MILLIMETERS",
        "CUBIC MILLIMETERS",
        "SQUARE KILOMETERS",
        "CUBIC KILOMETERS",
        "SQUARE DECIMETERS",
        "CUBIC DECIMETERS",
        "SQUARE FEET",
        "CUBIC FEET",
        "SQUARE YARDS",
        "CUBIC YARDS",
        "SQUARE MILES",
        "CUBIC MILES",
        "KILOBIT PER SECOND",
        "MEGABIT PER SECOND",
        "MEGAHERTZ",
        "GIGAHERTZ",
        "REVOLUTIONS PER MINUTE",
        "KILO CALORIES",
        "PLUS",
        "EQUALS",
        "SLASH",
        "NUMBER",
        ",",
        ",",
        ".",
        "\"",
        "\"",
};

bool const PV_NORMALIZER_SPECIAL_CHARACTERS_IS_VERBALIZED_TO_PUNCTUATION[PV_NORMALIZER_NUM_SPECIAL_CHARACTERS] = {
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
};
