#include "orca/normalizer/en/pv_normalizer_data_en/pv_normalizer_number_data_en.h"

const int64_t MAX_VERBALIZED_CARDINAL = 1000000000000000 - 1; // 1 quadrillion

const int64_t MAX_MULTIPLIER = 1000000000000; // 1 trillion
const char *NUMBER_RANGE_INBETWEEN_STRING = "TO";

const char *const ONE_TO_NINETEEN[20] = {
        "", "ONE", "TWO", "THREE", "FOUR", "FIVE", "SIX", "SEVEN", "EIGHT", "NINE", "TEN", "ELEVEN", "TWELVE",
        "THIRTEEN", "FOURTEEN", "FIFTEEN", "SIXTEEN", "SEVENTEEN", "EIGHTEEN", "NINETEEN"};
const char *const TENS[9] = {"", "TWENTY", "THIRTY", "FORTY", "FIFTY", "SIXTY", "SEVENTY", "EIGHTY", "NINETY"};
const char *const MULTIPLIERS[5] = {"", "TRILLION", "BILLION", "MILLION", "THOUSAND"};

const char *const ORDINAL_KEYS[PV_NORMALIZER_NUM_ORDINALS] = {
        "ZERO", "ONE", "TWO", "THREE", "FOUR", "FIVE", "SIX", "SEVEN", "EIGHT", "NINE", "TEN", "ELEVEN", "TWELVE",
        "THIRTEEN", "FOURTEEN", "FIFTEEN", "SIXTEEN", "SEVENTEEN", "EIGHTEEN", "NINETEEN", "TWENTY", "THIRTY", "FORTY",
        "FIFTY", "SIXTY", "SEVENTY", "EIGHTY", "NINETY", "HUNDRED", "THOUSAND", "MILLION", "BILLION", "TRILLION"};
const char *const ORDINAL_VALUES[PV_NORMALIZER_NUM_ORDINALS] = {
        "ZEROTH", "FIRST", "SECOND", "THIRD", "FOURTH", "FIFTH", "SIXTH", "SEVENTH", "EIGHTH", "NINTH", "TENTH",
        "ELEVENTH", "TWELFTH", "THIRTEENTH", "FOURTEENTH", "FIFTEENTH", "SIXTEENTH", "SEVENTEENTH", "EIGHTEENTH",
        "NINETEENTH", "TWENTIETH", "THIRTIETH", "FORTIETH", "FIFTIETH", "SIXTIETH", "SEVENTIETH", "EIGHTIETH",
        "NINETIETH", "HUNDREDTH", "THOUSANDTH", "MILLIONTH", "BILLIONTH", "TRILLIONTH"};

const char *const DENOMINATOR_ORDINAL_KEYS[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS] = {
        "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",
        "30", "40", "50", "60", "70", "80", "90", "100", "1000", "1000000", "1000000000", "1000000000000"};
const char *const DENOMINATOR_ORDINAL_VALUES_SINGULAR[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS] = {
        "HALF", "THIRD", "QUARTER", "FIFTH", "SIXTH", "SEVENTH", "EIGHTH", "NINTH", "TENTH", "ELEVENTH", "TWELFTH",
        "THIRTEENTH", "FOURTEENTH", "FIFTEENTH", "SIXTEENTH", "SEVENTIETH", "EIGHTIETH", "NINETIETH", "TWENTIETH",
        "THIRTIETH", "FORTIETH", "FIFTIETH", "SIXTIETH", "SEVENTIETH", "EIGHTIETH", "NINETIETH", "HUNDREDTH",
        "THOUSANDTH", "MILLIONTH", "BILLIONTH", "TRILLIONTH"};
const char *const DENOMINATOR_ORDINAL_VALUES_PLURAL[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS] = {
        "HALVES", "THIRDS", "QUARTERS", "FIFTHS", "SIXTHS", "SEVENTHS", "EIGHTHS", "NINTHS", "TENTHS", "ELEVENTHS",
        "TWELFTHS", "THIRTEENTHS", "FOURTEENTHS", "FIFTEENTHS", "SIXTEENTHS", "SEVENTIETHS", "EIGHTIETHS", "NINETIETHS",
        "TWENTIETHS", "THIRTIETHS", "FORTIETHS", "FIFTIETHS", "SIXTIETHS", "SEVENTIETHS", "EIGHTIETHS", "NINETIETHS",
        "HUNDREDTHS", "THOUSANDTHS", "MILLIONTHS", "BILLIONTHS", "TRILLIONTHS"};
