#include "orca/normalizer/en/pv_normalizer_data_en/pv_normalizer_currency_data_en.h"

const char *const PV_NORMALIZER_CURRENCIES[PV_NORMALIZER_NUM_CURRENCIES] = {
        "$",
        "€",
        "¥", // Note: JPY and CNY use the same unicode symbol. Currently verbalizes to YUAN
        "₪",
        "£",
        "₩",
        "₺",
        "₱",
        "₽",
        "฿",
        "₴",
        "₹",
        "¢",

        "USD",
        "EUR",
        "CAD",
        "JPY",
        "GBP",
        "AUD",
        "CHF",
        "CNY",
        "SEK",
        "NZD",
        "MXN",
        "SGD",
        "HKD",
        "NOK",
        "KRW",
        "TRY",
        "RUB",
        "INR",
        "BRL",
        "ZAR",
        "DKK",
        "PLN",
        "THB",
        "IDR",
        "MYR",
        "CZK",
        "HUF",
        "ILS",
        "ARS",
        "PHP",
        "CLP",
        "COP",
        "EGP",
        "SAR",
        "AED",
        "KWD",
        "PKR",
        "BDT",
        "NGN",
        "VES",
};

const char *const PV_NORMALIZER_CURRENCIES_VERBALIZED_SINGULAR[PV_NORMALIZER_NUM_CURRENCIES] = {
        "DOLLAR",
        "EURO",
        "YUAN",
        "SHEKEL",
        "POUND",
        "WON",
        "LIRA",
        "PESO",
        "RUBLE",
        "BAHT",
        "HRYVNIA",
        "RUPEE",
        "CENT",

        "UNITED STATES DOLLAR",
        "EURO",
        "CANADIAN DOLLAR",
        "JAPANESE YEN",
        "GREAT BRITAIN POUND",
        "AUSTRALIAN DOLLAR",
        "SWISS FRANC",
        "CHINESE YUAN",
        "SWEDISH KRONA",
        "NEW ZEALAND DOLLAR",
        "MEXICAN PESO",
        "SINGAPORE DOLLAR",
        "HONG KONG DOLLAR",
        "NORWEGIAN KRONE",
        "SOUTH KOREAN WON",
        "TURKISH LIRA",
        "RUSSIAN RUBLE",
        "INDIAN RUPEE",
        "BRAZILIAN REAL",
        "SOUTH AFRICAN RAND",
        "DANISH KRONE",
        "POLISH ZLOTY",
        "THAI BAHT",
        "INDONESIAN RUPIAH ",
        "MALAYSIAN RINGGIT ",
        "CZECH KORUNA ",
        "HUNGARIAN FORINT ",
        "ISRAELI SHEKEL ",
        "ARGENTINE PESO ",
        "PHILIPPINE PESO ",
        "CHILEAN PESO ",
        "COLOMBIAN PESO ",
        "EGYPTIAN POUND ",
        "SAUDI RIYAL ",
        "UAE DIRHAM ",
        "KUWAIT DINAR ",
        "PAKISTANI RUPEE ",
        "BANGLADESH TAKA ",
        "NIGERIAN NAIRA ",
        "VENEZUELAN BOLIVAR ",
};

const char *const PV_NORMALIZER_CURRENCIES_VERBALIZED_PLURAL[PV_NORMALIZER_NUM_CURRENCIES] = {
        "DOLLARS",
        "EUROS",
        "YUAN",
        "SHEKELS",
        "POUNDS",
        "WON",
        "LIRA",
        "PESOS",
        "RUBLES",
        "BAHT",
        "HRYVNIAS",
        "RUPEES",
        "CENTS",

        "UNITED STATES DOLLARS",
        "EUROS",
        "CANADIAN DOLLARS",
        "JAPANESE YEN",
        "GREAT BRITAIN POUNDS",
        "AUSTRALIAN DOLLARS",
        "SWISS FRANCS",
        "CHINESE YUAN",
        "SWEDISH KRONOR",
        "NEW ZEALAND DOLLARS",
        "MEXICAN PESOS",
        "SINGAPORE DOLLARS",
        "HONG KONG DOLLARS",
        "NORWEGIAN KRONER",
        "SOUTH KOREAN WON",
        "TURKISH LIRA",
        "RUSSIAN RUBLES",
        "INDIAN RUPEES",
        "BRAZILIAN REALS",
        "SOUTH AFRICAN RAND",
        "DANISH KRONER",
        "POLISH ZLOTY",
        "THAI BAHT",
        "INDONESIAN RUPIAH",
        "MALAYSIAN RINGGIT",
        "CZECH KORUNA",
        "HUNGARIAN FORINT",
        "ISRAELI SHEKELS",
        "ARGENTINE PESOS",
        "PHILIPPINE PESOS",
        "CHILEAN PESOS",
        "COLOMBIAN PESOS",
        "EGYPTIAN POUNDS",
        "SAUDI RIYALS",
        "UAE DIRHAMS",
        "KUWAIT DINARS",
        "PAKISTANI RUPEES",
        "BANGLADESH TAKA",
        "NIGERIAN NAIRA",
        "VENEZUELAN BOLIVARES",
};

const char *const PV_NORMALIZER_SUB_CURRENCIES_VERBALIZED_SINGULAR[PV_NORMALIZER_NUM_CURRENCIES] = {
        "CENT",
        "CENT",
        "FEN",
        "AGORA",
        "PENNY",
        "JEON",
        "KURUS",
        "SENTIMO",
        "KOPECK",
        "SATANG",
        "KOPIYKA",
        "PAISA",
        "",

        "CENT",
        "CENT",
        "CENT",
        "SEN",
        "PENNY",
        "CENT",
        "RAPPEN",
        "FEN",
        "ORE",
        "CENT",
        "CENTAVO",
        "CENT",
        "CENT",
        "ORE",
        "JEON",
        "KURUS",
        "KOPECK",
        "PAISA",
        "CENTAVO",
        "CENT",
        "ORE",
        "GROSZ",
        "SATANG",
        "SEN",
        "SEN",
        "HELLER",
        "FILLER",
        "AGORA",
        "CENTAVO",
        "SENTIMO",
        "SENTAVO",
        "CENTAVO",
        "PAISTRE",
        "HALALA",
        "FILS",
        "FILS",
        "PAISA",
        "POISHA",
        "KOBO",
        "CENTIMO",
};

const char *const PV_NORMALIZER_SUB_CURRENCIES_VERBALIZED_PLURAL[PV_NORMALIZER_NUM_CURRENCIES] = {
        "CENTS",
        "CENTS",
        "FEN",
        "AGORAS",
        "PENCE",
        "JEON",
        "KURUS",
        "SENTIMOS",
        "KOPECKS",
        "SATANG",
        "KOPIYKAS",
        "PAISE",
        "",

        "CENTS",
        "CENTS",
        "CENTS",
        "SEN",
        "PENCE",
        "CENTS",
        "RAPPEN",
        "FEN",
        "ORE",
        "CENTS",
        "CENTAVOS",
        "CENTS",
        "CENTS",
        "ORE",
        "JEON",
        "KURUS",
        "KOPECKS",
        "PAISE",
        "CENTAVOS",
        "CENTS",
        "ORE",
        "GROSZ",
        "SATANG",
        "SEN",
        "SEN",
        "HELLER",
        "FILLER",
        "AGORAS",
        "CENTAVOS",
        "SENTIMOS",
        "SENTAVOS",
        "CENTAVOS",
        "PAISTRES",
        "HALALAS",
        "FULUS",
        "FULUS",
        "PAISAs",
        "POISHA",
        "KOBO",
        "CENTIMOS",
};
