#include "orca/normalizer/en/pv_normalizer_data_en/pv_normalizer_measurement_data_en.h"

const char *const PV_NORMALIZER_MEASUREMENTS[PV_NORMALIZER_NUM_MEASUREMENTS] = {
        "°",
        "º",

        "°C",
        "ºC",
        "°F",
        "ºF",

        "M",
        "M2",
        "M²",
        "M3",
        "M³",
        "CM",
        "CM2",
        "CM²",
        "CM3",
        "CM³",
        "MM",
        "MM2",
        "MM²",
        "MM3",
        "MM³",
        "KM",
        "KM2",
        "KM²",
        "KM3",
        "KM³",
        "DM",
        "DM2",
        "DM²",
        "DM3",
        "DM³",

        "FT",
        "FT2",
        "FT²",
        "FT3",
        "FT³",
        "YD",
        "YD2",
        "YD²",
        "YD3",
        "YD³",
        "MI",
        "MI2",
        "MI²",
        "MI3",
        "MI³",

        "G",
        "KG",
        "MG",

        "OZ",
        "LB",
        "LBS",

        "L",
        "ML",

        "GAL",
        "QT",
        "PT",

        "S",
        "MIN",
        "H",

        "KB",
        "MB",
        "GB",
        "TB",
        "PB",
        "EB",
        "ZB",
        "YB",

        "KBPS",
        "MBPS",

        "HZ",
        "MHZ",
        "GHZ",
        "THZ",

        "KW",
        "MW",
        "GW",
        "TW",
        "PW",

        "KWH",
        "MWH",
        "GWH",
        "TWH",
        "PWH",

        "PA",
        "KPA",

        "V",
        "KV",

        "RPM",
        "KCAL",
        "DB",
        "RAD",

        "MPH",
        "BPS",
        "PPM",

        "MA",
        "MMHG",

        "NM",
};

const char *const PV_NORMALIZER_MEASUREMENTS_VERBALIZED_SINGULAR[PV_NORMALIZER_NUM_MEASUREMENTS] = {
        "DEGREE",
        "DEGREE",

        "DEGREE CELSIUS",
        "DEGREE CELSIUS",
        "DEGREE FAHRENHEIT",
        "DEGREE FAHRENHEIT",

        "METER",
        "SQUARE METER",
        "SQUARE METER",
        "CUBIC METER",
        "CUBIC METER",
        "CENTIMETER",
        "SQUARE CENTIMETER",
        "SQUARE CENTIMETER",
        "CUBIC CENTIMETER",
        "CUBIC CENTIMETER",
        "MILLIMETER",
        "SQUARE MILLIMETER",
        "SQUARE MILLIMETER",
        "CUBIC MILLIMETER",
        "CUBIC MILLIMETER",
        "KILOMETER",
        "SQUARE KILOMETER",
        "SQUARE KILOMETER",
        "CUBIC KILOMETER",
        "CUBIC KILOMETER",
        "DECIMETER",
        "SQUARE DECIMETER",
        "SQUARE DECIMETER",
        "CUBIC DECIMETER",
        "CUBIC DECIMETER",

        "FOOT",
        "SQUARE FOOT",
        "SQUARE FOOT",
        "CUBIC FOOT",
        "CUBIC FOOT",
        "YARD",
        "SQUARE YARD",
        "SQUARE YARD",
        "CUBIC YARD",
        "CUBIC YARD",
        "MILE",
        "SQUARE MILE",
        "SQUARE MILE",
        "CUBIC MILE",
        "CUBIC MILE",

        "GRAM",
        "KILOGRAM",
        "MILLIGRAM",

        "OUNCE",
        "POUND",
        "POUND",

        "LITER",
        "MILLILITER",

        "GALLON",
        "QUART",
        "PINT",

        "SECOND",
        "MINUTE",
        "HOUR",

        "KILOBYTE",
        "MEGABYTE",
        "GIGABYTE",
        "TERABYTE",
        "PETABYTE",
        "EXABYTE",
        "ZETTABYTE",
        "YOTTABYTE",

        "KILOBIT PER SECOND",
        "MEGABIT PER SECOND",

        "HERTZ",
        "MEGAHERTZ",
        "GIGAHERTZ",
        "TERAHERTZ",

        "KILOWATT",
        "MEGAWATT",
        "GIGAWATT",
        "TERAWATT",
        "PETAWATT",

        "KILOWATT HOUR",
        "MEGAWATT HOUR",
        "GIGAWATT HOUR",
        "TERAWATT HOUR",
        "PETAWATT HOUR",

        "PASCAL",
        "KILOPASCAL",

        "VOLT",
        "KILOVOLT",

        "REVOLUTION PER MINUTE",
        "KILO CALORIE",
        "DECIBEL",
        "RADIAN",

        "MILE PER HOUR",
        "BASIS POINTS",
        "PART PER MILLION",

        "MILLIAMP",
        "MILLIMETER OF MERCURY",

        "NANOMETER",
};

const char *const PV_NORMALIZER_MEASUREMENTS_VERBALIZED_PLURAL[PV_NORMALIZER_NUM_MEASUREMENTS] = {
        "DEGREES",
        "DEGREES",

        "DEGREES CELSIUS",
        "DEGREES CELSIUS",
        "DEGREES FAHRENHEIT",
        "DEGREES FAHRENHEIT",

        "METERS",
        "SQUARE METERS",
        "SQUARE METERS",
        "CUBIC METERS",
        "CUBIC METERS",
        "CENTIMETERS",
        "SQUARE CENTIMETERS",
        "SQUARE CENTIMETERS",
        "CUBIC CENTIMETERS",
        "CUBIC CENTIMETERS",
        "MILLIMETERS",
        "SQUARE MILLIMETERS",
        "SQUARE MILLIMETERS",
        "CUBIC MILLIMETERS",
        "CUBIC MILLIMETERS",
        "KILOMETERS",
        "SQUARE KILOMETERS",
        "SQUARE KILOMETERS",
        "CUBIC KILOMETERS",
        "CUBIC KILOMETERS",
        "DECIMETERS",
        "SQUARE DECIMETERS",
        "SQUARE DECIMETERS",
        "CUBIC DECIMETERS",
        "CUBIC DECIMETERS",

        "FEET",
        "SQUARE FEET",
        "SQUARE FEET",
        "CUBIC FEET",
        "CUBIC FEET",
        "YARDS",
        "SQUARE YARDS",
        "SQUARE YARDS",
        "CUBIC YARDS",
        "CUBIC YARDS",
        "MILES",
        "SQUARE MILES",
        "SQUARE MILES",
        "CUBIC MILES",
        "CUBIC MILES",

        "GRAMS",
        "KILOGRAMS",
        "MILLIGRAMS",

        "OUNCES",
        "POUNDS",
        "POUNDS",

        "LITERS",
        "MILLILITERS",

        "GALLONS",
        "QUARTS",
        "PINTS",

        "SECONDS",
        "MINUTES",
        "HOURS",

        "KILOBYTES",
        "MEGABYTES",
        "GIGABYTES",
        "TERABYTES",
        "PETABYTES",
        "EXABYTES",
        "ZETTABYTES",
        "YOTTABYTES",

        "KILOBITS PER SECOND",
        "MEGABITS PER SECOND",

        "HERTZ",
        "MEGAHERTZ",
        "GIGAHERTZ",
        "TERAHERTZ",

        "KILOWATTS",
        "MEGAWATTS",
        "GIGAWATTS",
        "TERAWATTS",
        "PETAWATTS",

        "KILOWATT HOURS",
        "MEGAWATT HOURS",
        "GIGAWATT HOURS",
        "TERAWATT HOURS",
        "PETAWATT HOURS",

        "PASCALS",
        "KILOPASCALS",

        "VOLTS",
        "KILOVOLTS",

        "REVOLUTIONS PER MINUTE",
        "KILO CALORIES",
        "DECIBELS",
        "RADIANS",

        "MILES PER HOUR",
        "BASIS POINTS",
        "PARTS PER MILLION",

        "MILLIAMPS",
        "MILLIMETERS OF MERCURY",

        "NANOMETERS",
};
