#ifndef PV_NORMALIZER_USE_CASES_KO_H
#define PV_NORMALIZER_USE_CASES_KO_H

#include "orca/normalizer/pv_normalizer_util.h"

typedef enum {
    PV_NORMALIZER_USE_WORD_NORMALIZER_KO = 0,
    PV_NORMALIZER_USE_CUSTOM_PRONUNCIATION_NORMALIZER_KO,
    PV_NORMALIZER_USE_PUNCTUATION_NORMALIZER_KO,
    PV_NORMALIZER_USE_CARDINAL_NORMALIZER_KO,
    PV_NORMALIZER_USE_NEGATIVE_CARDINAL_NORMALIZER_KO,
    PV_NORMALIZER_USE_NUMBER_RANGE_NORMALIZER_KO,
    PV_NORMALIZER_USE_SPECIAL_CHARACTER_NORMALIZER_KO,
    PV_NORMALIZER_USE_DECIMAL_NORMALIZER_KO,
    PV_NORMALIZER_USE_MEASUREMENT_NORMALIZER_KO,
    PV_NORMALIZER_USE_ALPHANUM_SPELL_OUT_NORMALIZER_KO,
    PV_NORMALIZER_USE_TIME_NORMALIZER_KO,
    PV_NORMALIZER_USE_FRACTION_NORMALIZER_KO,
    PV_NORMALIZER_USE_URL_NORMALIZER_KO,
    PV_NORMALIZER_USE_CURRENCY_NORMALIZER_KO,
    PV_NORMALIZER_USE_DIGITS_SEQUENCE_NORMALIZER_KO,
    PV_NORMALIZER_USE_DATE_NORMALIZER_KO,
    PV_NORMALIZER_USE_NAME_NORMALIZER_KO,
    PV_NORMALIZER_NUM_CASES_KO,
} pv_normalizer_use_cases_ko_t;

extern const pv_normalizer_use_cases_ko_t ALL_USE_CASES_KO[PV_NORMALIZER_NUM_CASES_KO];

#endif // PV_NORMALIZER_USE_CASES_KO_H
