source 'https://cdn.cocoapods.org/'
platform :ios, '13.0'

target 'OrcaDemo' do
  pod 'Orca-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/orca/v0.2.1-ios/binding/ios/Orca-iOS.podspec'
end
