#include <stdbool.h>

#include "orca/normalizer/es/pv_normalizer_data_es/pv_normalizer_measurement_data_es.h"

const char *const PV_NORMALIZER_MEASUREMENTS_ES[PV_NORMALIZER_NUM_MEASUREMENTS_ES] = {
        "°",
        "º",

        "°C",
        "ºC",
        "°F",
        "ºF",

        "M",
        "M2",
        "M²",
        "M3",
        "M³",
        "CM",
        "CM2",
        "CM²",
        "CM3",
        "CM³",
        "MM",
        "MM2",
        "MM²",
        "MM3",
        "MM³",
        "KM",
        "KM2",
        "KM²",
        "KM3",
        "KM³",
        "DM",
        "DM2",
        "DM²",
        "DM3",
        "DM³",

        "FT",
        "FT2",
        "FT²",
        "FT3",
        "FT³",
        "YD",
        "YD2",
        "YD²",
        "YD3",
        "YD³",
        "MI",
        "MI2",
        "MI²",
        "MI3",
        "MI³",

        "G",
        "KG",
        "MG",

        "OZ",
        "LB",
        "LBS",

        "L",
        "ML",
        "DL",

        "GAL",
        "QT",
        "PT",

        "S",
        "MIN",
        "H",

        "KB",
        "MB",
        "GB",
        "TB",
        "PB",
        "EB",
        "ZB",
        "YB",

        "KBPS",
        "MBPS",

        "HZ",
        "MHZ",
        "GHZ",
        "THZ",

        "KW",
        "MW",
        "GW",
        "TW",
        "PW",

        "KWH",
        "MWH",
        "GWH",
        "TWH",
        "PWH",

        "PA",
        "KPA",

        "V",
        "KV",

        "RPM",
        "KCAL",
        "DB",
        "RAD",
};

const char *const PV_NORMALIZER_MEASUREMENTS_VERBALIZED_SINGULAR_ES[PV_NORMALIZER_NUM_MEASUREMENTS_ES] = {
        "GRADO",
        "GRADO",

        "GRADO CELSIUS",
        "GRADO CELSIUSS",
        "GRADO FAHRENHEIT",
        "GRADO FAHRENHEIT",

        "METRO",
        "METRO CUADRADO",
        "METRO CUADRADO",
        "METRO CÚBICO",
        "METRO CÚBICO",
        "CENTÍMETRO",
        "CENTÍMETRO CUADRADO",
        "CENTÍMETRO CUADRADO",
        "CENTÍMETRO CÚBICO",
        "CENTÍMETRO CÚBICO",
        "MILÍMETRO",
        "MILÍMETRO CUADRADO",
        "MILÍMETRO CUADRADO",
        "MILÍMETRO CÚBICO",
        "MILÍMETRO CÚBICO",
        "KILÓMETRO",
        "KILÓMETRO CUADRADO",
        "KILÓMETRO CUADRADO",
        "KILÓMETRO CÚBICO",
        "KILÓMETRO CÚBICO",
        "DECÍMETRO",
        "DECÍMETRO CUADRADO",
        "DECÍMETRO CUADRADO",
        "DECÍMETRO CUADRADO",
        "DECÍMETRO CUADRADO",

        "PIE",
        "PIE CUADRADO",
        "PIE CUADRADO",
        "PIE CÚBICO",
        "PIE CÚBICO",
        "YARDA",
        "YARDA CUADRADA",
        "YARDA CUADRADA",
        "YARDA CÚBICA",
        "YARDA CÚBICA",
        "MILLA",
        "MILLA CUADRADA",
        "MILLA CUADRADA",
        "MILLA CÚBICA",
        "MILLA CÚBICA",

        "GRAMO",
        "KILOGRAMO",
        "MILIGRAMO",

        "ONZA",
        "LIBRA",
        "LIBRA",

        "LITRO",
        "MILILITRO",
        "DECILITRO",

        "GALÓN",
        "CUARTO",
        "PINTA",

        "SEGUNDO",
        "SEGUNDO",
        "HORA",

        "KILOBYTE",
        "MEGABYTE",
        "GIGABYTE",
        "TERABYTE",
        "PETABYTE",
        "EXABYTE",
        "ZETTABYTE",
        "YOTTABYTE",

        "KILOBIT POR SEGUNDO",
        "MEGABIT POR SEGUNDO",

        "HERCIO",
        "MEGAHERCIO",
        "GIGAHERCIO",
        "TERAHERCIO",

        "KILOVATIO",
        "MEGAWATIO",
        "GIGAWATIO",
        "TERAWATIO",
        "TERAWATIO",

        "KILOVATIO HORA",
        "MEGAWATIO HORA",
        "GIGAWATIO HORA",
        "TERAWATIO HORA",
        "PETAWATIO HORA",

        "PASCAL",
        "KILOPASCAL",

        "VOLTIO",
        "KILOVOLTIO",

        "REVOLUCIÓN POR MINUTO",
        "KILO CALORÍA",
        "DECIBELIO",
        "RADIAN",
};

const char *const PV_NORMALIZER_MEASUREMENTS_VERBALIZED_PLURAL_ES[PV_NORMALIZER_NUM_MEASUREMENTS_ES] = {
        "GRADOS",
        "GRADOS",

        "GRADOS CELSIUS",
        "GRADOS CELSIUS",
        "GRADOS FAHRENHEIT",
        "GRADOS FAHRENHEIT",

        "METROS",
        "METROS CUADRADOS",
        "METROS CUADRADOS",
        "METROS CÚBICOS",
        "METROS CÚBICOS",
        "CENTÍMETROS",
        "CENTÍMETROS CUADRADOS",
        "CENTÍMETROS CUADRADOS",
        "CENTÍMETROS CÚBICOS",
        "CENTÍMETROS CÚBICOS",
        "MILÍMETROS",
        "MILÍMETROS CUADRADOS",
        "MILÍMETROS CUADRADOS",
        "MILÍMETROS CÚBICOS",
        "MILÍMETROS CÚBICOS",
        "KILÓMETROS",
        "KILÓMETROS CUADRADOS",
        "KILÓMETROS CUADRADOS",
        "KILÓMETROS CÚBICOS",
        "KILÓMETROS CÚBICOS",
        "DECÍMETROS",
        "DECÍMETROS CUADRADOS",
        "DECÍMETROS CUADRADOS",
        "DECÍMETROS CÚBICOS",
        "DECÍMETROS CÚBICOS",

        "PIES",
        "PIES CUADRADOS",
        "PIES CUADRADOS",
        "PIES CÚBICOS",
        "PIES CÚBICOS",
        "YARDAS",
        "YARDAS CUADRADAS",
        "YARDAS CUADRADAS",
        "YARDAS CÚBICAS",
        "YARDAS CÚBICASS",
        "MILLAS",
        "MILLAS CUADRADAS",
        "MILLAS CUADRADAS",
        "MILLAS CÚBICAS",
        "MILLAS CÚBICAS",

        "GRAMOS",
        "KILOGRAMOS",
        "MILIGRAMOS",

        "ONZAS",
        "LIBRAS",
        "LIBRAS",

        "LITROS",
        "MILILITROS",
        "DECILITROS",

        "GALONES",
        "CUARTOS",
        "PINTSS",

        "SEGUNDOS",
        "MINUTOS",
        "HORAS",

        "KILOBYTES",
        "MEGABYTES",
        "GIGABYTES",
        "TERABYTES",
        "PETABYTES",
        "EXABYTES",
        "ZETTABYTES",
        "YOTTABYTES",

        "KILOBITS POR SEGUNDO",
        "MEGABITS POR SEGUNDO",

        "HERCIOS",
        "MEGAHERCIOS",
        "GIGAHERCIOS",
        "TERAHERCIOS",

        "KILOVATIOS",
        "MEGAWATIOS",
        "GIGAWATIOS",
        "TERAWATIOS",
        "PETAWATIOS",

        "KILOVATIO HORAS",
        "MEGAWATIO HORAS",
        "GIGAWATIO HORAS",
        "TERAWATIO HORAS",
        "PETAWATIO HORAS",

        "PASCALS",
        "KILOPASCALS",

        "VOLTIOS",
        "KILOVOLTIOS",

        "REVOLUCIONES POR MINUTO",
        "KILO CALORÍAS  ",
        "DECIBELIOS",
        "RADIANES",
};
