#include <stdbool.h>

#include "orca/normalizer/es/pv_normalizer_data_es/pv_normalizer_special_character_data_es.h"
#include "orca/normalizer/pv_normalizer_data/pv_normalizer_shared_data.h"

const char *const PV_NORMALIZER_SPECIAL_CHARACTERS_ES[PV_NORMALIZER_NUM_SPECIAL_CHARACTERS_ES] = {
        "@",
        "%",
        "&",
        "\n",
        "_",
        "(",
        ")",
        "°C",
        "ºC",
        "°F",
        "ºF",
        "°",
        "º",
        "M²",
        "M³",
        "CM²",
        "CM³",
        "MM²",
        "MM³",
        "KM²",
        "KM³",
        "DM²",
        "DM³",
        "FT²",
        "FT³",
        "YD²",
        "YD³",
        "MI²",
        "MI³",
        "KBPS",
        "MBPS",
        "MHZ",
        "GHZ",
        "RPM",
        "KCAL",
        "+",
        "=",
        "/",
        "#",
        "[",
        "]",
        EM_DASH,
        ";",
        HORIZONTAL_BAR,
        HORIZONTAL_ELLIPSIS,
        RIGHT_DOUBLE_QUOTATION_MARK,
        LEFT_DOUBLE_QUOTATION_MARK,
};

const char *const PV_NORMALIZER_SPECIAL_CHARACTERS_VERBALIZED_ES[PV_NORMALIZER_NUM_SPECIAL_CHARACTERS_ES] = {
        "ARROBA",
        "POR CIENTO",
        "Y",
        ".",
        "GUION BAJO",
        ",",
        ",",
        "GRADOS CELSIUS",
        "GRADOS CELSIUS",
        "GRADOS FAHRENHEIT",
        "GRADOS FAHRENHEIT",
        "GRADOS",
        "GRADOS",
        "METROS CUADRADOS",
        "METROS CÚBICOS",
        "CENTÍMETROS CUADRADOS",
        "CENTÍMETROS CÚBICOS",
        "MILÍMETROS CUADRADOS",
        "MILÍMETROS CÚBICOS",
        "KILÓMETROS CUADRADOS",
        "KILÓMETROS CÚBICOS",
        "DECÍMETROS CUADRADOS",
        "DECÍMETROS CÚBICOS",
        "PIES CUADRADOS",
        "PIES CÚBICOS",
        "YARDAS CUADRADAS",
        "YARDAS CÚBICAS",
        "MILLAS CUADRADAS",
        "MILLAS CÚBICAS",
        "KILOBIT POR SEGUNDO",
        "MEGABIT POR SEGUNDO",
        "MEGAHERCIOS",
        "GIGAHERCIOS",
        "REVOLUCIONES POR MINUTO",
        "KILOCALORÍAS",
        "MÁS",
        "ES IGUAL A",
        "DIAGONAL",
        "NUMERAL",
        ",",
        ",",
        ",",
        ",",
        ",",
        ".",
        "\"",
        "\"",
};

bool const PV_NORMALIZER_SPECIAL_CHARACTERS_IS_VERBALIZED_TO_PUNCTUATION_ES[PV_NORMALIZER_NUM_SPECIAL_CHARACTERS_ES] = {
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
};
