// Put all characters that can be a part of a word in the language, for example in English we have all upper and lower case alphabet letters as well as apostrophe "'".

#include "orca/normalizer/es/pv_normalizer_data_es/pv_normalizer_word_character_data_es.h"
#include "orca/normalizer/pv_normalizer_data/pv_normalizer_shared_data.h"
#include "orca/normalizer/pv_normalizer_language_data.h"

const char *const PV_NORMALIZER_WORD_CHARACTERS_ES[PV_NORMALIZER_NUM_WORD_CHARACTERS_ES] = {
        "A",
        "a",
        "B",
        "b",
        "C",
        "c",
        "D",
        "d",
        "E",
        "e",
        "F",
        "f",
        "G",
        "g",
        "H",
        "h",
        "I",
        "i",
        "J",
        "j",
        "K",
        "k",
        "L",
        "l",
        "M",
        "m",
        "N",
        "n",
        "O",
        "o",
        "P",
        "p",
        "Q",
        "q",
        "R",
        "r",
        "S",
        "s",
        "T",
        "t",
        "U",
        "u",
        "V",
        "v",
        "W",
        "w",
        "X",
        "x",
        "Y",
        "y",
        "Z",
        "z",
        "Á",
        "á",
        "É",
        "é",
        "Í",
        "í",
        "Ó",
        "ó",
        "Ú",
        "ú",
        "Ü",
        "ü",
        "Ñ",
        "ñ",
        APOSTROPHE,
};

const char *const PV_NORMALIZER_ALPHABET_CHARACTERS_ES[PV_NORMALIZER_NUM_ALPHABET_CHARACTERS_ES] = {
        "A",
        "a",
        "B",
        "b",
        "C",
        "c",
        "D",
        "d",
        "E",
        "e",
        "F",
        "f",
        "G",
        "g",
        "H",
        "h",
        "I",
        "i",
        "J",
        "j",
        "K",
        "k",
        "L",
        "l",
        "M",
        "m",
        "N",
        "n",
        "O",
        "o",
        "P",
        "p",
        "Q",
        "q",
        "R",
        "r",
        "S",
        "s",
        "T",
        "t",
        "U",
        "u",
        "V",
        "v",
        "W",
        "w",
        "X",
        "x",
        "Y",
        "y",
        "Z",
        "z",
        "Á",
        "á",
        "É",
        "é",
        "Í",
        "í",
        "Ó",
        "ó",
        "Ú",
        "ú",
        "Ü",
        "ü",
        "Ñ",
        "ñ",
};

const char *const PV_ORCA_PHONEMIZER_ES_ALPHABET_UPPERCASE_LETTERS[PV_ORCA_PHONEMIZER_ES_ALPHABET_NUM_LETTERS] = {
        "A", "B", "C", "D", "E", "F", "G", "H", "I",
        "J", "K", "L", "M", "N", "O", "P", "Q",
        "R", "S", "T", "U", "V", "W", "X", "Y",
        "Z", "Á", "É", "Í", "Ó", "Ú", "Ü", "Ñ",
};

const char *const PV_ORCA_PHONEMIZER_ES_ALPHABET_PRONUNCIATIONS[PV_ORCA_PHONEMIZER_ES_ALPHABET_NUM_LETTERS] = {
        "a", "b e", "θ e", "d e", "e", "e f e", "x e", "a ʧ e", "i",
        "x o t a", "k a", "e l e", "e m e", "e n e", "o", "p e", "k u",
        "e r e", "e s e", "t e", "u", "u β e", "u β e d o β l e", "e k i s",
        "i", "θ e t a", "a", "e", "i", "o", "u", "u", "e ɲ e"
};

const char *PV_ORCA_STREAM_ES_EOS_PUNCTUATIONS[] = {".", "?", "!"};
const char *PV_ORCA_STREAM_ES_FALLBACK_CUTOFF_CHARACTERS[] = {":", ","};


