#include "orca/normalizer/es/pv_normalizer_data_es/pv_normalizer_currency_data_es.h"

const char *const PV_NORMALIZER_CURRENCIES_ES[PV_NORMALIZER_NUM_CURRENCIES_ES] = {
        "$",
        "€",
        "¥", // Note: JPY and CNY use the same unicode symbol. Currently verbalizes to YUAN
        "₪",
        "£",
        "₩",
        "₺",
        "₱",
        "₽",
        "฿",
        "₴",
        "₹",
        "¢",

        "USD",
        "EUR",
        "CAD",
        "JPY",
        "GBP",
        "AUD",
        "CHF",
        "CNY",
        "SEK",
        "NZD",
        "MXN",
        "SGD",
        "HKD",
        "NOK",
        "KRW",
        "TRY",
        "RUB",
        "INR",
        "BRL",
        "ZAR",
        "DKK",
        "PLN",
        "THB",
        "IDR",
        "MYR",
        "CZK",
        "HUF",
        "ILS",
        "ARS",
        "PHP",
        "CLP",
        "COP",
        "EGP",
        "SAR",
        "AED",
        "KWD",
        "PKR",
        "BDT",
        "NGN",
        "VES",
};

const char *const PV_NORMALIZER_CURRENCIES_VERBALIZED_SINGULAR_ES[PV_NORMALIZER_NUM_CURRENCIES_ES] = {
        "DÓLAR",
        "EURO",
        "YUAN",
        "SHEKEL",
        "LIBRA",
        "WON",
        "LIRA",
        "PESO",
        "RUBLO",
        "BAHT",
        "GRIVNA",
        "RUPIA",
        "CENTAVO",

        "DÓLAR ESTADOUNIDENSE",
        "EURO",
        "DÓLAR CANADIENSE",
        "YEN JAPONÉS",
        "LIBRA ESTERLINA",
        "DÓLAR AUSTRALIANO",
        "FRANCO SUIZO",
        "YUAN CHINO",
        "CORONA SUECA",
        "DÓLAR NEOZELANDÉS",
        "PESO MEXICANO",
        "DÓLAR DE SINGAPUR",
        "DÓLAR DE HONG KONG",
        "CORONA NORUEGA",
        "WON SURCOREANO",
        "LIRA TURCA",
        "RUBLO RUSO",
        "RUPIA INDIA",
        "REAL BRASILEÑO",
        "RAND SURAFRICANO",
        "CORONA DANESA",
        "ZLOTY POLACO",
        "BAHT TAILANDÉS",
        "RUPIA INDONESIA",
        "RINGGIT MALASIO",
        "CORONA CHECA",
        "FORINTO HÚNGARO",
        "SHEKEL ISRAELÍ",
        "PESO ARGENTINO",
        "PESO FILIPINO",
        "PESO CHILENO",
        "PESO COLOMBIANO",
        "LIBRA EGIPCIA",
        "RIYAL SAUDÍ",
        "DIRHAM DE LOS EMIRATOS ÁRABES UNIDOS",
        "DINAR KUWAITÍ",
        "RUPIA PAQUISTANÍ",
        "TAKA BANGLADESHÍ",
        "NAIRA NIGERIANA",
        "BOLÍVAR SOBERANO",
};

const char *const PV_NORMALIZER_CURRENCIES_VERBALIZED_PLURAL_ES[PV_NORMALIZER_NUM_CURRENCIES_ES] = {
        "DÓLARES",
        "EUROS",
        "YUANES",
        "SHEKELS",
        "LIBRAS",
        "WON",
        "LIRAS",
        "PESOS",
        "RUBLOS",
        "BAHTS",
        "GRIVNAS",
        "RUPIAS",
        "CENTAVOS",

        "DÓLARES ESTADOUNIDENSES",
        "EUROS",
        "DÓLARES CANADIENSES",
        "YENES JAPONESES",
        "LIBRAS ESTERLINAS",
        "DÓLARES AUSTRALIANOS",
        "FRANCOS SUIZOS",
        "YUANES CHINOS",
        "CORONAS SUECAS",
        "DÓLARES NEOZELANDESES",
        "PESOS MEXICANOS",
        "DÓLARES DE SINGAPUR",
        "DÓLARES DE HONG KONG",
        "CORONAS NORUEGAS",
        "WONES SURCOREANOS",
        "LIRAS TURCAS",
        "RUBLOS RUSOS",
        "RUPIAS INDIAS",
        "REALES BRASILEÑOS",
        "RAND SUDAFRICANOS",
        "CORONAS DANESAS",
        "ZLOTYS POLACOS",
        "BAHTS TAILANDESES",
        "RUPIAS INDONESIAS",
        "RINGGITS MALASIOS",
        "CORONAS CHECAS",
        "FORINTOS HÚNGAROS",
        "SHEKELS ISRAELÍES",
        "PESOS ARGENTINOS",
        "PESOS FILIPINOS",
        "PESOS CHILENOS",
        "PESOS COLOMBIANOS",
        "LIBRAS EGIPCIAS",
        "RIYALES SAUDÍES",
        "DIRHAMS DE LOS EMIRATOS ÁRABES UNIDOS",
        "DINARES KUWAITÍES",
        "RUPIAS PAQUISTANÍES",
        "TAKAS BANGLADESHÍES",
        "NAIRAS NIGERIANAS",
        "BOLÍVARES VENEZOLANOS",
};

const char *const PV_NORMALIZER_SUB_CURRENCIES_VERBALIZED_SINGULAR_ES[PV_NORMALIZER_NUM_CURRENCIES_ES] = {
        "CENTAVO",
        "CÉNTIMO",
        "FEN",
        "ÁGORA",
        "PENIQUE",
        "JEON",
        "KURUS",
        "CÉNTIMO",
        "KOPEK",
        "SATANG",
        "KOPIYKA",
        "PAISA",
        "",

        "CENTAVO",
        "CENTAVO",
        "CENTAVO",
        "SEN",
        "PENIQUE",
        "CENTAVO",
        "RAPPEN",
        "FEN",
        "ÖRE",
        "CENTAVO",
        "CENTAVO",
        "CENTAVO",
        "CENTAVO",
        "ÖRE",
        "JEON",
        "KURUS",
        "KOPEK",
        "PAISA",
        "CENTAVO",
        "CENT",
        "ÖRE",
        "GROSZ",
        "SATANG",
        "SEN",
        "SEN",
        "HELLER",
        "FILLER",
        "ÁGORA",
        "CENTAVO",
        "CÉNTIMO",
        "CENTAVO",
        "CENTAVO",
        "PAISTRE",
        "HALALA",
        "FILS",
        "FILS",
        "PAISA",
        "POISHA",
        "KOBO",
        "CÉNTIMO",
};

const char *const PV_NORMALIZER_SUB_CURRENCIES_VERBALIZED_PLURAL_ES[PV_NORMALIZER_NUM_CURRENCIES_ES] = {
        "CENTAVOS",
        "CÉNTIMOS",
        "FEN",
        "ÁGORAS",
        "PENIQUES",
        "JEON",
        "KURUS",
        "CÉNTIMOS",
        "KOPEKS",
        "SATANGS",
        "KOPIYKAS",
        "PAISAS",
        "",

        "CENTAVOS",
        "CENTAVOS",
        "CENTAVOS",
        "SEN",
        "PENIQUES",
        "CENTAVOS",
        "RAPPEN",
        "FEN",
        "ÖRE",
        "CENTAVOS",
        "CENTAVOS",
        "CENTAVOS",
        "CENTAVOS",
        "ÖRE",
        "JEON",
        "KURUS",
        "KOPEKS",
        "PAISAS",
        "CENTAVOS",
        "CENTAVOS",
        "ÖRE",
        "GROSZ",
        "SATANGS",
        "SEN",
        "SEN",
        "HELLER",
        "FILLER",
        "ÁGORAS",
        "CENTAVOS",
        "CÉNTIMOS",
        "CENTAVOS",
        "CENTAVOS",
        "PIASTRES",
        "HALALAS",
        "FULUS",
        "FULUS",
        "PAISAS",
        "POISHA",
        "KOBO",
        "CÉNTIMOS",
};
