#include "orca/normalizer/es/pv_normalizer_data_es/pv_normalizer_number_data_es.h"

const int64_t MAX_VERBALIZED_CARDINAL_ES = 1000000000000000 - 1; // 1 quadrillion

const int64_t MAX_MULTIPLIER_ES = 1000000000000; // 1 trillion
const char *NUMBER_RANGE_INBETWEEN_STRING_ES = "A";

const char *const ONE_TO_TWENTY_NINE_ES[30] = {
        "", "UNO", "DOS", "TRES", "CUATRO", "CINCO", "SEIS", "SIETE", "OCHO", "NUEVE", "DIEZ", "ONCE", "DOCE",
        "TRECE", "CATORCE", "QUINCE", "DIECISÉIS", "DIECISIETE", "DIECIOCHO", "DIECINUEVE", "VEINTE", "VEINTIUNO",
        "VEINTIDÓS", "VEINTITRÉS", "VEINTICUATRO", "VEINTICINCO", "VEINTISÉIS", "VEINTISIETE", "VEINTIOCHO", "VEINTINUEVE"};
const char *const TENS_ES[9] = {"", "VEINTE", "TREINTA", "CUARENTA", "CINCUENTA", "SESENTA", "SETENTA", "OCHENTA", "NOVENTA"};
const char *const HUNDREDS_ES[9] = {"", "DOSCIENTOS", "TRESCIENTOS", "CUATROCIENTOS", "QUINIENTOS", "SEISCIENTOS", "SETECIENTOS", "OCHOCIENTOS", "NOVECIENTOS"};
const char *const HUNDREDS_FEMININE_ES[9] = {"", "DOSCIENTAS", "TRESCIENTAS", "CUATROCIENTAS", "QUINIENTAS", "SEISCIENTAS", "SETECIENTAS", "OCHOCIENTAS", "NOVECIENTAS"};
const char *const MULTIPLIERS_ES[6] = {"", "BILLÓN", "MIL", "MILLÓN", "MIL", "CIEN"};
const char *const MULTIPLIERS_PLURAL_ES[6] = {"", "BILLONES", "MIL", "MILLONES", "MIL", "CIEN"};

const char *const ORDINAL_KEYS_ES[PV_NORMALIZER_NUM_ORDINALS_ES] = {
        "CERO", "UNO", "DOS", "TRES", "CUATRO", "CINCO", "SEIS", "SIETE", "OCHO", "NUEVE", "DIEZ", "ONCE", "DOCE",
        "TRECE", "CATORCE", "QUINCE", "DIECISÉIS", "DIECISIETE", "DIECIOCHO", "DIECINUEVE", "VEINTE", "VEINTIUNO",
        "VEINTIDÓS", "VEINTITRÉS", "VEINTICUATRO", "VEINTICINCO", "VEINTISÉIS", "VEINTISIETE", "VEINTIOCHO", "VEINTINUEVE",
        "TREINTA", "CUARENTA", "CINCUENTA", "SESENTA", "SETENTA", "OCHENTA", "NOVENTA", "CIEN", "DOSCIENTOS", "TRESCIENTOS",
        "CUATROCIENTOS", "QUINIENTOS", "SEISCIENTOS", "SETECIENTOS", "OCHOCIENTOS", "NOVECIENTOS", "MIL", "MILLÓN", "MILLONES",
        "BILLÓN", "BILLONES"};
const char *const ORDINAL_VALUES_MASCULINE_ES[PV_NORMALIZER_NUM_ORDINALS_ES] = {
        "CERO", "PRIMERO", "SEGUNDO", "TERCERO", "CUARTO", "QUINTO", "SEXTO", "SÉPTIMO", "OCTAVO", "NOVENO", "DÉCIMO",
        "UNDÉCIMO", "DUODÉCIMO", "DECIMOTERCERO", "DECIMOCUARTO", "DECIMOQUINTO", "DECIMOSEXTO", "DECIMOSÉPTIMO", "DECIMOCTAVO",
        "DECIMONOVENO", "'VIGÉSIMO'", "VIGÉSIMO PRIMERO", "VIGÉSIMO SEGUNDO", "VIGÉSIMO TERCERO", "VIGÉSIMO CUARTO", "VIGÉSIMO QUINTO",
        "VIGÉSIMO SEXTO", "VIGÉSIMO SÉPTIMO", "VIGÉSIMO OCTAVO", "VIGÉSIMO NOVENO",  "TRIGÉSIMO", "CUADRAGÉSIMO", "QUINCUAGÉSIMO",
        "SEXAGÉSIMO", "SEPTUAGÉSIMO", "OCTOGÉSIMO", "NONAGÉSIMO", "CENTÉSIMO", "DUCENTÉSIMO", "TRICENTÉSIMO", "CUADRINGENTÉSIMO",
        "QUINGENTÉSIMO", "SEISCENTÉSIMO", "SEPTINGENTÉSIMO", "OCTINGENTÉSIMO", "NONINGENTÉSIMO",  "MILÉSIMO", "MILLONÉSIMO", "MILLONÉSIMO",
        "BILLONÉSIMO", "BILLONÉSIMO"};
const char *const ORDINAL_VALUES_FEMININE_ES[PV_NORMALIZER_NUM_ORDINALS_ES] = {
        "CERO", "PRIMERA", "SEGUNDA", "TERCERA", "CUARTA", "QUINTA", "SEXTA", "SÉPTIMA", "OCTAVA", "NOVENA", "DÉCIMA",
        "UNDÉCIMA", "DUODÉCIMA", "DECIMOTERCERA", "DECIMOCUARTA", "DECIMOQUINTA", "DECIMOSEXTA", "DECIMOSÉPTIMA", "DECIMOCTAVA",
        "DECIMONOVENA", "'VIGÉSIMA'", "VIGÉSIMO PRIMERA", "VIGÉSIMO SEGUNDA", "VIGÉSIMO TERCERA", "VIGÉSIMO CUARTA", "VIGÉSIMO QUINTA",
        "VIGÉSIMO SEXTA", "VIGÉSIMO SÉPTIMA", "VIGÉSIMA OCTAVA", "VIGÉSIMA NOVENA",  "TRIGÉSIMA", "CUADRAGÉSIMA", "QUINCUAGÉSIMO",
        "SEXAGÉSIMA", "SEPTUAGÉSIMA", "OCTOGÉSIMA", "NONAGÉSIMA", "CENTÉSIMA", "DUCENTÉSIMA", "TRICENTÉSIMA", "CUADRINGENTÉSIMA",
        "QUINGENTÉSIMA", "SEISCENTÉSIMA", "SEPTINGENTÉSIMA", "OCTINGENTÉSIMA", "NONINGENTÉSIMA",  "MILÉSIMA", "MILLONÉSIMA", "MILLONÉSIMA",
        "BILLONÉSIMA", "BILLONÉSIMA"};

const char *const DENOMINATOR_ORDINAL_KEYS_ES[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_ES] = {
        "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "100", "1000", "10000", "100000", "1000000", "10000000", "100000000", "1000000000", "10000000000", "100000000000", "1000000000000"};
const char *const DENOMINATOR_ORDINAL_VALUES_MASCULINE_ES[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_ES] = {
        "MEDIO", "TERCIO", "CUARTO", "QUINTO", "SEXTO", "SÉPTIMO", "OCTAVO", "NOVENO", "DÉCIMO", "ONCEAVO", "DOCEAVO", "CENTÉSIMO", "MILÉSIMO", "DIEZ MILÉSIMO", "CIEN MILÉSIMO", "MILLONÉSIMO", "DIEZ MILLONÉSIMO", "CIEN MILLONÉSIMO", "MIL MILLONÉSIMO", "DIEZ MIL MILLONÉSIMO", "CIEN MIL MILLONÉSIMO", "BILLONÉSIMO"};
const char *const DENOMINATOR_ORDINAL_VALUES_FEMININE_ES[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_ES] = {
        "MEDIA", "TERCIA", "CUARTA", "QUINTA", "SEXTA", "SÉPTIMA", "OCTAVA", "NOVENA", "DÉCIMA", "ONCEAVA", "DOCEAVA", "CENTÉSIMA", "MILÉSIMA", "DIEZ MILÉSIMA", "CIEN MILÉSIMA", "MILLONÉSIMA", "DIEZ MILLONÉSIMA", "CIEN MILLONÉSIMA", "MIL MILLONÉSIMA", "DIEZ MIL MILLONÉSIMA", "CIEN MIL MILLONÉSIMA", "BILLONÉSIMA"};
