#include "orca/normalizer/fr/pv_normalizer_data_fr/pv_normalizer_currency_data_fr.h"

const char *const PV_NORMALIZER_CURRENCIES_FR[PV_NORMALIZER_NUM_CURRENCIES_FR] = {
        "$",
        "€",
        "¥", // Note: JPY and CNY use the same unicode symbol. Currently verbalizes to YUAN
        "₪",
        "£",
        "₩",
        "₺",
        "₱",
        "₽",
        "฿",
        "₴",
        "₹",
        "¢",

        "USD",
        "EUR",
        "CAD",
        "JPY",
        "GBP",
        "AUD",
        "CHF",
        "CNY",
        "SEK",
        "NZD",
        "MXN",
        "SGD",
        "HKD",
        "NOK",
        "KRW",
        "TRY",
        "RUB",
        "INR",
        "BRL",
        "ZAR",
        "DKK",
        "PLN",
        "THB",
        "IDR",
        "MYR",
        "CZK",
        "HUF",
        "ILS",
        "ARS",
        "PHP",
        "CLP",
        "COP",
        "EGP",
        "SAR",
        "AED",
        "KWD",
        "PKR",
        "BDT",
        "NGN",
        "VES",
};

const char *const PV_NORMALIZER_CURRENCIES_VERBALIZED_SINGULAR_FR[PV_NORMALIZER_NUM_CURRENCIES_FR] = {
        "DOLLAR",
        "EURO",
        "YUAN",
        "SHEKEL",
        "LIVRE",
        "WON",
        "LIVRE",
        "PESO",
        "ROUBLE",
        "BAHT",
        "HRYVNIA",
        "ROUPIE",
        "CENT",

        "DOLLAR AMÉRICAIN",
        "EURO",
        "DOLLAR CANADIEN",
        "YEN JAPONAIS",
        "LIVRE STERLING",
        "DOLLAR AUSTRALIEN",
        "FRANC SUISSE",
        "YUAN CHINOIS",
        "COURONNE SUÉDOISE",
        "DOLLAR NÉO-ZÉLANDAIS",
        "PESO MEXICAIN",
        "DOLLAR DE SINGAPOUR",
        "DOLLAR DE HONG KONG",
        "COURONNE NORVÉGIENNE",
        "WON SUD-CORÉEN",
        "LIVRE TURQUE",
        "ROUBLE RUSSE",
        "ROUPIE INDIENNE",
        "RÉAL BRÉSILIEN",
        "RAND SUD-AFRICAIN",
        "COURONNE DANOISE",
        "ZŁOTY POLONAIS",
        "BAHT THAÏ",
        "ROUPIE INDONÉSIENNE",
        "RINGGIT MALAISIEN",
        "COURONNE TCHÈQUE",
        "FORINT HONGROIS",
        "SHEKEL ISRAËL",
        "PESO ARGENTIN",
        "PESO PHILIPPIN",
        "PESO CHILIEN",
        "PESO COLOMBIEN",
        "LIVRE ÉGYPTIENNE",
        "RIAL SAOUDIEN",
        "DIRHAM ÉMIRATI",
        "DINAR KOWEÏTIEN",
        "ROUPIE PAKISTANAISE",
        "TAKA BANGLADESH",
        "NAIRA NIGERIA",
        "BOLIVAR NUMÉRIQUE",
};

const char *const PV_NORMALIZER_CURRENCIES_VERBALIZED_PLURAL_FR[PV_NORMALIZER_NUM_CURRENCIES_FR] = {
        "DOLLARS",
        "EUROS",
        "YUAN",
        "SHEKELS",
        "POUNDS",
        "WON",
        "LIRA",
        "PESOS",
        "RUBLES",
        "BAHT",
        "HRYVNIAS",
        "RUPEES",
        "CENTS",

        "DOLLARS AMÉRICAIN",
        "EUROS",
        "DOLLARS CANADIEN",
        "YEN JAPONAIS",
        "LIVRES STERLING",
        "DOLLARS AUSTRALIEN",
        "FRANCS SUISSE",
        "YUAN CHINOIS",
        "COURONNE SUÉDOISE",
        "DOLLARS NÉO-ZÉLANDAIS",
        "PESOS MEXICAIN",
        "DOLLARS DE SINGAPOUR",
        "DOLLARS DE HONG KONG",
        "COURONNE NORVÉGIENNE",
        "WON SUD-CORÉEN",
        "LIVRES TURQUE",
        "ROUBLES RUSSE",
        "ROUPIES INDIENNE",
        "RÉALS BRÉSILIEN",
        "RANDS SUD-AFRICAIN",
        "COURONNES DANOISE",
        "ZŁOTY POLONAIS",
        "BAHTS THAÏ",
        "ROUPIES INDONÉSIENNE",
        "RINGGITS MALAISIEN",
        "COURONNE TCHÈQUE",
        "FORINTS HONGROIS",
        "SHEKELS ISRAËL",
        "PESOS ARGENTIN",
        "PESOS PHILIPPIN",
        "PESOS CHILIEN",
        "PESOS COLOMBIEN",
        "LIVRES ÉGYPTIENNE",
        "RIALS SAOUDIEN",
        "DIRHAMS ÉMIRATI",
        "DINARS KOWEÏTIEN",
        "ROUPIES PAKISTANAISE",
        "TAKAS BANGLADESH",
        "NAIRAS NIGERIA",
        "BOLIVARS NUMÉRIQUE",
};

// TODO BELOW

const char *const PV_NORMALIZER_SUB_CURRENCIES_VERBALIZED_SINGULAR_FR[PV_NORMALIZER_NUM_CURRENCIES_FR] = {
        "CENT",
        "CENT",
        "FEN",
        "AGORA",
        "PENNY",
        "JEON",
        "KURUS",
        "SENTIMO",
        "KOPECK",
        "SATANG",
        "KOPIYKA",
        "PAISA",
        "",

        "CENT",
        "CENT",
        "CENT",
        "SEN",
        "PENNY",
        "CENT",
        "RAPPEN",
        "FEN",
        "ORE",
        "CENT",
        "CENTAVO",
        "CENT",
        "CENT",
        "ORE",
        "JEON",
        "KURUS",
        "KOPECK",
        "PAISA",
        "CENTAVO",
        "CENT",
        "ORE",
        "GROSZ",
        "SATANG",
        "SEN",
        "SEN",
        "HELLER",
        "FILLER",
        "AGORA",
        "CENTAVO",
        "SENTIMO",
        "SENTAVO",
        "CENTAVO",
        "PAISTRE",
        "HALALA",
        "FILS",
        "FILS",
        "PAISA",
        "POISHA",
        "KOBO",
        "CENTIMO",
};

const char *const PV_NORMALIZER_SUB_CURRENCIES_VERBALIZED_PLURAL_FR[PV_NORMALIZER_NUM_CURRENCIES_FR] = {
        "CENTS",
        "CENTS",
        "FEN",
        "AGORAS",
        "PENCE",
        "JEON",
        "KURUS",
        "SENTIMOS",
        "KOPECKS",
        "SATANG",
        "KOPIYKAS",
        "PAISE",
        "",

        "CENTS",
        "CENTS",
        "CENTS",
        "SEN",
        "PENCE",
        "CENTS",
        "RAPPEN",
        "FEN",
        "ORE",
        "CENTS",
        "CENTAVOS",
        "CENTS",
        "CENTS",
        "ORE",
        "JEON",
        "KURUS",
        "KOPECKS",
        "PAISE",
        "CENTAVOS",
        "CENTS",
        "ORE",
        "GROSZ",
        "SATANG",
        "SEN",
        "SEN",
        "HELLER",
        "FILLER",
        "AGORAS",
        "CENTAVOS",
        "SENTIMOS",
        "SENTAVOS",
        "CENTAVOS",
        "PAISTRES",
        "HALALAS",
        "FULUS",
        "FULUS",
        "PAISAs",
        "POISHA",
        "KOBO",
        "CENTIMOS",
};
