#include <stdbool.h>

#include "orca/normalizer/fr/pv_normalizer_data_fr/pv_normalizer_measurement_data_fr.h"

const char *const PV_NORMALIZER_MEASUREMENTS_FR[PV_NORMALIZER_NUM_MEASUREMENTS_FR] = {
        "°",
        "º",

        "°C",
        "ºC",
        "°F",
        "ºF",

        "M",
        "M2",
        "M²",
        "M3",
        "M³",
        "CM",
        "CM2",
        "CM²",
        "CM3",
        "CM³",
        "MM",
        "MM2",
        "MM²",
        "MM3",
        "MM³",
        "KM",
        "KM2",
        "KM²",
        "KM3",
        "KM³",
        "DM",
        "DM2",
        "DM²",
        "DM3",
        "DM³",

        "FT",
        "FT2",
        "FT²",
        "FT3",
        "FT³",
        "YD",
        "YD2",
        "YD²",
        "YD3",
        "YD³",
        "MI",
        "MI2",
        "MI²",
        "MI3",
        "MI³",

        "G",
        "KG",
        "MG",

        "OZ",
        "LB",
        "LBS",

        "L",
        "ML",

        "GAL",
        "QT",
        "PT",

        "S",
        "MIN",
        "H",

        "KB",
        "MB",
        "GB",
        "TB",
        "PB",
        "EB",
        "ZB",
        "YB",

        "KO",
        "MO",
        "GO",
        "TO",
        "PO",
        "EO",
        "ZO",
        "YO",

        "KBPS",
        "MBPS",

        "KOPS",
        "MOPS",

        "HZ",
        "MHZ",
        "GHZ",
        "THZ",

        "KW",
        "MW",
        "GW",
        "TW",
        "PW",

        "KWH",
        "MWH",
        "GWH",
        "TWH",
        "PWH",

        "PA",
        "KPA",

        "V",
        "KV",

        "RPM",
        "KCAL",
        "DB",
        "RAD",
};

const char *const PV_NORMALIZER_MEASUREMENTS_VERBALIZED_SINGULAR_FR[PV_NORMALIZER_NUM_MEASUREMENTS_FR] = {
        "DEGRÉ",
        "DEGRÉ",

        "DEGRÉ CELSIUS",
        "DEGRÉ CELSIUS",
        "DEGRÉ FAHRENHEIT",
        "DEGRÉ FAHRENHEIT",

        "MÈTRE",
        "MÈTRE CARRÉ",
        "MÈTRE CARRÉ",
        "MÈTRE CUBE",
        "MÈTRE CUBE",
        "CENTIMÈTRE",
        "CENTIMÈTRE CARRÉ",
        "CENTIMÈTRE CARRÉ",
        "CENTIMÈTRE CUBE",
        "CENTIMÈTRE CUBE",
        "MILLIMÈTRE",
        "MILLIMÈTRE CARRÉ",
        "MILLIMÈTRE CARRÉ",
        "MILLIMÈTRE CUBE",
        "MILLIMÈTRE CUBE",
        "KILOMÈTRE",
        "KILOMÈTRE CARRÉ",
        "KILOMÈTRE CARRÉ",
        "KILOMÈTRE CUBE",
        "KILOMÈTRE CUBE",
        "DÉCIMÈTRE",
        "DÉCIMÈTRE CARRÉ",
        "DÉCIMÈTRE CARRÉ",
        "DÉCIMÈTRE CUBE",
        "DÉCIMÈTRE CUBE",

        "PIED",
        "PIED CARRÉ",
        "PIED CARRÉ",
        "PIED CUBE",
        "PIED CUBE",
        "YARD",
        "YARD CARRÉ",
        "YARD CARRÉ",
        "YARD CUBE",
        "YARD CUBE",
        "MILLE",
        "MILLE CARRÉ",
        "MILLE CARRÉ",
        "MILLE CUBE",
        "MILLE CUBE",

        "GRAMME",
        "KILOGRAMME",
        "MILLIGRAMME",

        "OUNCE",
        "POUND",
        "POUND",

        "LITRE",
        "MILLILITRE",

        "GALLON",
        "QUART",
        "PINTE",

        "SECONDE",
        "MINUTE",
        "HEURE",

        "KILOBYTE",
        "MEGABYTE",
        "GIGABYTE",
        "TERABYTE",
        "PETABYTE",
        "EXABYTE",
        "ZETTABYTE",
        "YOTTABYTE",

        "KILO-OCTET",
        "MEGA-OCTET",
        "GIGA-OCTET",
        "TERA-OCTET",
        "PETA-OCTET",
        "EXA-OCTET",
        "ZETTA-OCTET",
        "YOTTA-OCTET",

        "KILOBIT PAR SECONDE",
        "MEGABIT PAR SECONDE",

        "KILO-OCTET PAR SECONDE",
        "MEGA-OCTET PAR SECONDE",

        "HERTZ",
        "MEGAHERTZ",
        "GIGAHERTZ",
        "TERAHERTZ",

        "KILOWATT",
        "MEGAWATT",
        "GIGAWATT",
        "TERAWATT",
        "PETAWATT",

        "KILOWATT HEURE",
        "MEGAWATT HEURE",
        "GIGAWATT HEURE",
        "TERAWATT HEURE",
        "PETAWATT HEURE",

        "PASCAL",
        "KILOPASCAL",

        "VOLT",
        "KILOVOLT",

        "RÉVOLUTION PAR MINUTE",
        "KILO CALORIE",
        "DÉCIBEL",
        "RADIAN",
};

const char *const PV_NORMALIZER_MEASUREMENTS_VERBALIZED_PLURAL_FR[PV_NORMALIZER_NUM_MEASUREMENTS_FR] = {
        "DEGRÉS",
        "DEGRÉS",

        "DEGRÉS CELSIUS",
        "DEGRÉS CELSIUS",
        "DEGRÉS FAHRENHEIT",
        "DEGRÉS FAHRENHEIT",

        "MÈTRES",
        "MÈTRES CARRÉS",
        "MÈTRES CARRÉS",
        "MÈTRES CUBES",
        "MÈTRES CUBES",
        "CENTIMÈTRES",
        "CENTIMÈTRES CARRÉS",
        "CENTIMÈTRES CARRÉS",
        "CENTIMÈTRES CUBES",
        "CENTIMÈTRES CUBES",
        "MILLIMÈTRES",
        "MILLIMÈTRES CARRÉS",
        "MILLIMÈTRES CARRÉS",
        "MILLIMÈTRES CUBES",
        "MILLIMÈTRES CUBES",
        "KILOMÈTRES",
        "KILOMÈTRES CARRÉS",
        "KILOMÈTRES CARRÉS",
        "KILOMÈTRES CUBES",
        "KILOMÈTRES CUBES",
        "DÉCIMÈTRES",
        "DÉCIMÈTRES CARRÉS",
        "DÉCIMÈTRES CARRÉS",
        "DÉCIMÈTRES CUBES",
        "DÉCIMÈTRES CUBES",

        "PIEDS",
        "PIEDS CARRÉS",
        "PIEDS CARRÉS",
        "PIEDS CUBES",
        "PIEDS CUBES",
        "YARDS",
        "YARDS CARRÉS",
        "YARDS CARRÉS",
        "YARDS CUBES",
        "YARDS CUBES",
        "MILLES",
        "MILLES CARRÉS",
        "MILLES CARRÉS",
        "MILLES CUBES",
        "MILLES CUBES",

        "GRAMMES",
        "KILOGRAMMES",
        "MILLIGRAMMES",

        "OUNCES",
        "POUNDS",
        "POUNDS",

        "LITRES",
        "MILLILITRES",

        "GALLONS",
        "QUARTS",
        "PINTES",

        "SECONDES",
        "MINUTES",
        "HEURES",

        "KILOBYTES",
        "MEGABYTES",
        "GIGABYTES",
        "TERABYTES",
        "PETABYTES",
        "EXABYTES",
        "ZETTABYTES",
        "YOTTABYTES",

        "KILO-OCTETS",
        "MEGA-OCTETS",
        "GIGA-OCTETS",
        "TERA-OCTETS",
        "PETA-OCTETS",
        "EXA-OCTETS",
        "ZETTA-OCTETS",
        "YOTTA-OCTETS",

        "KILOBITS PAR SECONDE",
        "MEGABITS PAR SECONDE",

        "KILO-OCTETS PAR SECONDE",
        "MEGA-OCTETS PAR SECONDE",

        "HERTZ",
        "MEGAHERTZ",
        "GIGAHERTZ",
        "TERAHERTZ",

        "KILOWATTS",
        "MEGAWATTS",
        "GIGAWATTS",
        "TERAWATTS",
        "PETAWATTS",

        "KILOWATT HEURES",
        "MEGAWATT HEURES",
        "GIGAWATT HEURES",
        "TERAWATT HEURES",
        "PETAWATT HEURES",

        "PASCALS",
        "KILOPASCALS",

        "VOLTS",
        "KILOVOLTS",

        "RÉVOLUTIONS PAR MINUTE",
        "KILO CALORIES",
        "DÉCIBELS",
        "RADIANS",
};
