#include "orca/normalizer/fr/pv_normalizer_data_fr/pv_normalizer_date_data_fr.h"

const char *const PV_NORMALIZER_MONTH_NAMES_FR[PV_NORMALIZER_NUM_MONTH_NAMES_FR] = {
        "JANVIER",
        "FÉVRIER",
        "MARS",
        "AVRIL",
        "MAI",
        "JUIN",
        "JUILLET",
        "AOÛT",
        "SEPTEMBRE",
        "OCTOBRE",
        "NOVEMBRE",
        "DÉCEMBRE",

        "JAN",
        "FÉV",
        "MARS",
        "AVR",
        "MAI",
        "JUIN",
        "JUIL",
        "AOÛT",
        "SEPT",
        "OCT",
        "NOV",
        "DÉC",
};

const char *const PV_NORMALIZER_MONTH_NAMES_VERBALIZED_FR[PV_NORMALIZER_NUM_MONTH_NAMES_FR] = {
        "JANVIER",
        "FÉVRIER",
        "MARS",
        "AVRIL",
        "MAI",
        "JUIN",
        "JUILLET",
        "AOÛT",
        "SEPTEMBRE",
        "OCTOBRE",
        "NOVEMBRE",
        "DÉCEMBRE",

        "JANVIER",
        "FÉVRIER",
        "MARS",
        "AVRIL",
        "MAI",
        "JUIN",
        "JUILLET",
        "AOÛT",
        "SEPTEMBRE",
        "OCTOBRE",
        "NOVEMBRE",
        "DÉCEMBRE",
};
