#include "orca/normalizer/fr/pv_normalizer_data_fr/pv_normalizer_word_character_data_fr.h"
#include "orca/normalizer/pv_normalizer_data/pv_normalizer_shared_data.h"
#include "orca/normalizer/pv_normalizer_language_data.h"

const char *const PV_NORMALIZER_WORD_CHARACTERS_FR[PV_NORMALIZER_NUM_WORD_CHARACTERS_FR] = {
        "A",
        "a",
        "B",
        "b",
        "C",
        "c",
        "D",
        "d",
        "E",
        "e",
        "F",
        "f",
        "G",
        "g",
        "H",
        "h",
        "I",
        "i",
        "J",
        "j",
        "K",
        "k",
        "L",
        "l",
        "M",
        "m",
        "N",
        "n",
        "O",
        "o",
        "P",
        "p",
        "Q",
        "q",
        "R",
        "r",
        "S",
        "s",
        "T",
        "t",
        "U",
        "u",
        "V",
        "v",
        "W",
        "w",
        "X",
        "x",
        "Y",
        "y",
        "Z",
        "z",
        "À",
        "à",
        "Â",
        "â",
        "Ä",
        "ä",
        "Ç",
        "ç",
        "É",
        "é",
        "È",
        "è",
        "Ê",
        "ê",
        "Ë",
        "ë",
        "Î",
        "î",
        "Ï",
        "ï",
        "Ô",
        "ô",
        "Ö",
        "ö",
        "Ù",
        "ù",
        "Û",
        "û",
        "Ü",
        "ü",
        "Ÿ",
        "ÿ",
        "Œ",
        "œ",
        APOSTROPHE,
        HYPHEN,
};

const char *const PV_NORMALIZER_ALPHABET_CHARACTERS_FR[PV_NORMALIZER_NUM_ALPHABET_CHARACTERS_FR] = {
        "A",
        "a",
        "B",
        "b",
        "C",
        "c",
        "D",
        "d",
        "E",
        "e",
        "F",
        "f",
        "G",
        "g",
        "H",
        "h",
        "I",
        "i",
        "J",
        "j",
        "K",
        "k",
        "L",
        "l",
        "M",
        "m",
        "N",
        "n",
        "O",
        "o",
        "P",
        "p",
        "Q",
        "q",
        "R",
        "r",
        "S",
        "s",
        "T",
        "t",
        "U",
        "u",
        "V",
        "v",
        "W",
        "w",
        "X",
        "x",
        "Y",
        "y",
        "Z",
        "z",
        "À",
        "à",
        "Â",
        "â",
        "Ä",
        "ä",
        "Ç",
        "ç",
        "É",
        "é",
        "È",
        "è",
        "Ê",
        "ê",
        "Ë",
        "ë",
        "Î",
        "î",
        "Ï",
        "ï",
        "Ô",
        "ô",
        "Ö",
        "ö",
        "Ù",
        "ù",
        "Û",
        "û",
        "Ü",
        "ü",
        "Ÿ",
        "ÿ",
        "Œ",
        "œ",
};

const char *const PV_ORCA_PHONEMIZER_FR_ALPHABET_UPPERCASE_LETTERS[PV_ORCA_PHONEMIZER_FR_ALPHABET_NUM_LETTERS] = {
        "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V",
        "W", "X", "Y", "Z", "À", "Á", "Â", "È", "É", "Ê", "Ë", "Î", "Ï", "Ô", "Ù", "Û", "Ü", "Ç", "Œ"
};

const char *const PV_ORCA_PHONEMIZER_FR_ALPHABET_PRONUNCIATIONS[PV_ORCA_PHONEMIZER_FR_ALPHABET_NUM_LETTERS] = {
        "a", "b e", "s e", "d e", "ə", "ɛ f", "ʒ e", "a ʃ", "i", "ʒ i", "k a", "ɛ l", "ɛ m", "ɛ n", "o", "p e", "k y",
        "ɛ ʁ", "ɛ s", "t e", "y", "v e",
        "d u b l ə v e", "i k s", "i g ʁ ɛ k", "z ɛ d",
        "a", "a", "ɑ", "ɛ", "e", "ɛ", "ø", "i", "i", "o", "u", "y", "y", "s", "œ"
};

const char *PV_ORCA_STREAM_FR_EOS_PUNCTUATIONS[] = {".", "?", "!"};
const char *PV_ORCA_STREAM_FR_FALLBACK_CUTOFF_CHARACTERS[] = {":", ","};

