#include "orca/normalizer/fr/pv_normalizer_data_fr/pv_normalizer_special_character_data_fr.h"
#include "orca/normalizer/pv_normalizer_data/pv_normalizer_shared_data.h"
#include <stdbool.h>

const char *const PV_NORMALIZER_SPECIAL_CHARACTERS_FR[PV_NORMALIZER_NUM_SPECIAL_CHARACTERS_FR] = {
        "@",
        "%",
        "&",
        "\n",
        "_",
        "(",
        ")",
        "«",
        "»",
        "°C",
        "ºC",
        "°F",
        "ºF",
        "°",
        "º",
        "M²",
        "M³",
        "CM²",
        "CM³",
        "MM²",
        "MM³",
        "KM²",
        "KM³",
        "DM²",
        "DM³",
        "FT²",
        "FT³",
        "YD²",
        "YD³",
        "MI²",
        "MI³",
        "KBPS",
        "MBPS",
        "MHZ",
        "GHZ",
        "RPM",
        "KCAL",
        "+",
        "=",
        "/",
        "#",
        "[",
        "]",
        EM_DASH,
        ";",
        HORIZONTAL_BAR,
        HORIZONTAL_ELLIPSIS,
        RIGHT_DOUBLE_QUOTATION_MARK,
        LEFT_DOUBLE_QUOTATION_MARK,
};

const char *const PV_NORMALIZER_SPECIAL_CHARACTERS_VERBALIZED_FR[PV_NORMALIZER_NUM_SPECIAL_CHARACTERS_FR] = {
        "AROBASE",
        "POUR CENT",
        "ET",
        ".",
        "TIRET BAS",
        ",",
        ",",
        ",",
        ",",
        "DEGRÉ CELSIUS",
        "DEGRÉ CELSIUS",
        "DEGRÉ FAHRENHEIT",
        "DEGRÉ FAHRENHEIT",
        "DEGRÉ",
        "SYMBOLE DE DEGRÉ",
        "MÈTRE CARRÉ",
        "MÈTRE CUBE",
        "CENTIMÈTRE CARRÉ",
        "CENTIMÈTRE CUBE",
        "MILLIMÈTRE CARRÉ",
        "MILLIMÈTRE CUBE",
        "KILOMÈTRE CARRÉ",
        "KILOMÈTRE CUBE",
        "DÉCIMÈTRE CARRÉ",
        "DÉCIMÈTRE CUBE",
        "PIED CARRÉ",
        "PIED CUBE",
        "YARD CARRÉ",
        "YARD CUBE",
        "MILLE CARRÉ",
        "MILLE CUBE",
        "KILOBITS PAR SECONDE",
        "MÉGABITS PAR SECONDE",
        "MÉGAHERTZ",
        "GIGAHERTZ",
        "TOURS PAR MINUTE",
        "KILOCALORIE",
        "PLUS",
        "ÉGAL",
        "BARRE OBLIQUE",
        "DIÈSE",
        "CROCHET OUVRANT",
        "CROCHET FERMANT",
        ",",
        "POINT-VIRGULE",
        ",",
        ".",
        "\"",
        "\"",
};

bool const PV_NORMALIZER_SPECIAL_CHARACTERS_IS_VERBALIZED_TO_PUNCTUATION_FR[PV_NORMALIZER_NUM_SPECIAL_CHARACTERS_FR] = {
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        true,
        true,
};
