#include "orca/pv_orca_language_data.h"

const char *const PV_ORCA_PHONEMIZER_PT_ALPHABET_UPPERCASE_LETTERS[PV_ORCA_PHONEMIZER_PT_ALPHABET_NUM_LETTERS] = {
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
        "À",
        "Á",
        "Â",
        "Ã",
        "Ç",
        "È",
        "É",
        "Ê",
        "Í",
        "Ó",
        "Ô",
        "Õ",
        "Ú",
};

const char *const PV_ORCA_PHONEMIZER_PT_ALPHABET_PRONUNCIATIONS[PV_ORCA_PHONEMIZER_PT_ALPHABET_NUM_LETTERS] = {
        "ɐ",
        "b e",
        "s e",
        "d e",
        "i",
        "ɛ f i",
        "ʒ e",
        "ɐ ɡ ɐ",
        "i",
        "ʒ ɔ t ɐ",
        "k ɐ",
        "ɛ l i",
        "e m i",
        "e n i",
        "u",
        "p e",
        "k e",
        "ɛ ʁ i",
        "ɛ s i",
        "t e",
        "u",
        "v e",
        "d ɐ b i w j u",
        "ʃ i ʃ",
        "i p i s i l õ",
        "z e",
        "ɐ",
        "ɐ ɐ s ẽ t u ɐ ɡ u d u",
        "ɐ ɐ s ẽ t u s i ɾ k ũ f l ɛ k i s u",
        "ɐ t i w",
        "s e s e d i ʎ ɐ",
        "e ɐ s ẽ t u ɡ ɾ ɐ v i",
        "ɛ",
        "ɛ ɐ s ẽ t u s i ɾ k ũ f l ɛ k i s u",
        "i ɐ s ẽ t u ɐ ɡ u d u",
        "ɔ",
        "o",
        "ɔ t i w",
        "u ɐ s ẽ t u ɐ ɡ u d u",
};

const char *PV_ORCA_STREAM_PT_FALLBACK_CUTOFF_CHARACTERS[] = {":", ","};
