#include "orca/pv_orca_language_data.h"

const char *const PV_ORCA_PHONEMIZER_DE_ALPHABET_UPPERCASE_LETTERS[PV_ORCA_PHONEMIZER_DE_ALPHABET_NUM_LETTERS] = {
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
        "Ä",
        "Ö",
        "Ü",
};

const char *const PV_ORCA_PHONEMIZER_DE_ALPHABET_PRONUNCIATIONS[PV_ORCA_PHONEMIZER_DE_ALPHABET_NUM_LETTERS] = {
        "a",
        "b e",
        "ʦ e",
        "d e",
        "e",
        "ɛ f",
        "g e",
        "h a",
        "i",
        "j ɔ t",
        "k a",
        "ɛ l",
        "ɛ m",
        "ɛ n",
        "o",
        "p e",
        "k u",
        "ɛ r",
        "ɛ s",
        "t e",
        "u",
        "f aʊ",
        "v e",
        "ɪ k s",
        "ʏ p s ɪ l ɔ n",
        "ʦ ɛ t",
        "ɛː",
        "ø",
        "y",
};

const char *PV_ORCA_STREAM_DE_FALLBACK_CUTOFF_CHARACTERS[] = {":", ","};
