#include "orca/pv_orca_language_data.h"

const char *const PV_ORCA_PHONEMIZER_EN_ALPHABET_UPPERCASE_LETTERS[PV_ORCA_PHONEMIZER_EN_ALPHABET_NUM_LETTERS] = {
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
};

const char *const PV_ORCA_PHONEMIZER_EN_ALPHABET_PRONUNCIATIONS[PV_ORCA_PHONEMIZER_EN_ALPHABET_NUM_LETTERS] = {
        "EY",
        "B IY",
        "S IY",
        "D IY",
        "IY",
        "EH F",
        "JH IY",
        "EY CH",
        "AY",
        "JH EY",
        "K EY",
        "EH L",
        "EH M",
        "EH N",
        "OW",
        "P IY",
        "K Y UW",
        "AA R",
        "EH S",
        "T IY",
        "Y UW",
        "V IY",
        "D AH B AH L Y UW",
        "EH K S",
        "W AY",
        "Z IY",
};

const char *PV_ORCA_STREAM_EN_FALLBACK_CUTOFF_CHARACTERS[] = {":", ","};
