#include "orca/pv_orca_language_data.h"

const char *const PV_ORCA_PHONEMIZER_IT_ALPHABET_UPPERCASE_LETTERS[PV_ORCA_PHONEMIZER_IT_ALPHABET_NUM_LETTERS] = {
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
        "À",
        "È",
        "É",
        "Ì",
        "Ò",
        "Ù",
};

const char *const PV_ORCA_PHONEMIZER_IT_ALPHABET_PRONUNCIATIONS[PV_ORCA_PHONEMIZER_IT_ALPHABET_NUM_LETTERS] = {
        "a",
        "b i",
        "tʃ i",
        "d i",
        "e",
        "ɛ f f e",
        "dʒ i",
        "a k k a",
        "i",
        "i l u ŋ g a",
        "k a p p a",
        "ɛ l l e",
        "e m m e",
        "ɛ n n e",
        "o",
        "p i",
        "k u",
        "ɛ rr e",
        "e s s e",
        "t i",
        "u",
        "v i",
        "d o p p j a v i",
        "i k s",
        "i p s i l o n",
        "dz ɛ t a",
        "a",
        "ɛ",
        "e",
        "i",
        "ɔ",
        "u",
};

const char *PV_ORCA_STREAM_IT_FALLBACK_CUTOFF_CHARACTERS[] = {":", ","};
