#ifndef PV_NORMALIZER_TAGS_FR_H
#define PV_NORMALIZER_TAGS_FR_H

typedef enum {
    PV_NORMALIZER_TAG_FR_NONE = 0,
    PV_NORMALIZER_TAG_FR_WORD,
    PV_NORMALIZER_TAG_FR_CUSTOM_PRONUNCIATION,
    PV_NORMALIZER_TAG_FR_PUNCTUATION,
    PV_NORMALIZER_TAG_FR_CARDINAL,
    PV_NORMALIZER_TAG_FR_NEGATIVE_CARDINAL,
    PV_NORMALIZER_TAG_FR_NUMBER_RANGE_TO,
    PV_NORMALIZER_TAG_FR_ORDINAL,
    PV_NORMALIZER_TAG_FR_NEGATIVE_ORDINAL,
    PV_NORMALIZER_TAG_FR_SPECIAL_CHARACTER,
    PV_NORMALIZER_TAG_FR_ALPHANUM_SPELL_OUT,
    PV_NORMALIZER_TAG_FR_DECIMAL_POINT,
    PV_NORMALIZER_TAG_FR_DECIMAL_DIGITS,
    PV_NORMALIZER_TAG_FR_MEASUREMENT,
    PV_NORMALIZER_TAG_FR_PER_SLASH,
    PV_NORMALIZER_TAG_FR_TIME_COLON,
    PV_NORMALIZER_TAG_FR_TIME_MINUTES,
    PV_NORMALIZER_TAG_FR_TIME_HOURS,
    PV_NORMALIZER_TAG_FR_TIME_H,
    PV_NORMALIZER_TAG_FR_TIME_AM_PM,
    PV_NORMALIZER_TAG_FR_FRACTION_SLASH,
    PV_NORMALIZER_TAG_FR_DOT,
    PV_NORMALIZER_TAG_FR_COLON,
    PV_NORMALIZER_TAG_FR_ACRONYM,
    PV_NORMALIZER_TAG_FR_TOP_LEVEL_DOMAIN,
    PV_NORMALIZER_TAG_FR_CURRENCY,
    PV_NORMALIZER_TAG_FR_CURRENCY_SYMBOL,
    PV_NORMALIZER_TAG_FR_NEGATIVE_CURRENCY,
    PV_NORMALIZER_TAG_FR_ABBREVIATION,
    PV_NORMALIZER_TAG_FR_DIGITS,
    PV_NORMALIZER_TAG_FR_DIGITS_WITH_PARENTHESES,
    PV_NORMALIZER_TAG_FR_DIGITS_SEPARATOR,
    PV_NORMALIZER_TAG_FR_DATE_SEPARATOR,
    PV_NORMALIZER_TAG_FR_DATE_DAY,
    PV_NORMALIZER_TAG_FR_DATE_MONTH,
    PV_NORMALIZER_TAG_FR_DATE_YEAR,
    PV_NORMALIZER_TAG_FR_NAME_INITIAL_LETTER,
    PV_NORMALIZER_TAG_FR_NAME_INITIAL_DOT,
    PV_NORMALIZER_TAG_FR_LETTER_SPELL_OUT,
    PV_NORMALIZER_TAG_FR_CARDINAL_SPELL_OUT,
    PV_NORMALIZER_TAG_FR_SINGLE_QUOTE,
    PV_NORMALIZER_TAG_FR_SPACE,
    PV_NORMALIZER_TAG_FR_NUM_TAGS,
} pv_normalizer_token_tag_fr_t;

static const float PV_NORMALIZER_TOKEN_TAG_FR_WEIGHTS[PV_NORMALIZER_TAG_FR_NUM_TAGS] = {
        0.f, // 0
        1.f, // 1
        100.f, // 2
        0.5f, // 3
        1.f, // 4
        1.f, // 5
        1.f, // 6
        1.f, // 7
        1.f, // 8
        1.f, // 9
        0.5f, // 10
        2.f, // 11
        4.f, // 12
        4.f, // 13
        2.f, // 14
        3.f, // 15
        3.f, // 16
        3.f, // 17
        3.f, // 18
        2.f, // 19
        2.f, //
        1.f, // 20,
        1.f, // 21,
        10.f, // 22,
        11.f, // 23,
        5.f, // 24
        5.f, // 25
        5.f, // 26
        5.f, // 27
        2.f, // 28
        2.f, // 29
        2.f, // 30
        5.f, // 31
        5.f, // 32
        5.f, // 33
        5.f, // 34
        2.f, // 35
        2.f, // 36
        2.f, // 37
        2.f, // 38
        2.f, // 39
        0.5f, // 40
};

#endif // PV_NORMALIZER_TAGS_FR_H
