#ifndef PV_NORMALIZER_USE_CASES_FR_H
#define PV_NORMALIZER_USE_CASES_FR_H

#include "orca/normalizer/pv_normalizer_util.h"

typedef enum {
    PV_NORMALIZER_USE_WORD_NORMALIZER_FR = 0,
    PV_NORMALIZER_USE_CUSTOM_PRONUNCIATION_NORMALIZER_FR = 1,
    PV_NORMALIZER_USE_PUNCTUATION_NORMALIZER_FR = 2,
    PV_NORMALIZER_USE_CARDINAL_NORMALIZER_FR = 3,
    PV_NORMALIZER_USE_NEGATIVE_CARDINAL_NORMALIZER_FR = 4,
    PV_NORMALIZER_USE_NUMBER_RANGE_NORMALIZER_FR = 5,
    PV_NORMALIZER_USE_ORDINAL_NORMALIZER_FR = 6,
    PV_NORMALIZER_USE_NEGATIVE_ORDINAL_NORMALIZER_FR = 7,
    PV_NORMALIZER_USE_SPECIAL_CHARACTER_NORMALIZER_FR = 8,
    PV_NORMALIZER_USE_DECIMAL_NORMALIZER_FR = 9,
    PV_NORMALIZER_USE_MEASUREMENT_NORMALIZER_FR = 10,
    PV_NORMALIZER_USE_ALPHANUM_SPELL_OUT_NORMALIZER_FR = 11,
    PV_NORMALIZER_USE_TIME_NORMALIZER_FR = 12,
    PV_NORMALIZER_USE_FRACTION_NORMALIZER_FR = 13,
    PV_NORMALIZER_USE_URL_NORMALIZER_FR = 14,
    PV_NORMALIZER_USE_CURRENCY_NORMALIZER_FR = 15,
    PV_NORMALIZER_USE_ABBREVIATION_NORMALIZER_FR = 16,
    PV_NORMALIZER_USE_DIGITS_SEQUENCE_NORMALIZER_FR = 17,
    PV_NORMALIZER_USE_DATE_NORMALIZER_FR = 18,
    PV_NORMALIZER_USE_NAME_NORMALIZER_FR = 19,
    PV_NORMALIZER_NUM_CASES_FR = 20,
} pv_normalizer_use_cases_fr_t;

extern const pv_normalizer_use_cases_fr_t ALL_USE_CASES_FR[PV_NORMALIZER_NUM_CASES_FR];

#endif // PV_NORMALIZER_USE_CASES_FR_H
