#ifndef PV_NORMALIZER_TAGS_H
#define PV_NORMALIZER_TAGS_H

typedef enum {
    PV_NORMALIZER_TAG_NONE = 0,
    PV_NORMALIZER_TAG_CUSTOM_PRONUNCIATION = 1,
    PV_NORMALIZER_TAG_PUNCTUATION = 2,
    PV_NORMALIZER_TAG_SPACE = 3,
    PV_NORMALIZER_TAG_LETTER_SPELL_OUT = 4,
} pv_normalizer_token_tag_t;

#endif // PV_NORMALIZER_TAGS_H
