#ifndef PV_NORMALIZER_TAGS_JA_H
#define PV_NORMALIZER_TAGS_JA_H

typedef enum {
    PV_NORMALIZER_TAG_JA_NONE = 0,
    PV_NORMALIZER_TAG_JA_WORD = 1,
    PV_NORMALIZER_TAG_JA_CUSTOM_PRONUNCIATION = 2,
    PV_NORMALIZER_TAG_JA_PUNCTUATION = 3,
    PV_NORMALIZER_TAG_JA_CARDINAL = 4,
    PV_NORMALIZER_TAG_JA_NEGATIVE_CARDINAL = 5,
    PV_NORMALIZER_TAG_JA_NUMBER_RANGE_TO = 6,
    PV_NORMALIZER_TAG_JA_SPECIAL_CHARACTER = 7,
    PV_NORMALIZER_TAG_JA_ALPHANUM_SPELL_OUT = 8,
    PV_NORMALIZER_TAG_JA_DECIMAL_POINT = 9,
    PV_NORMALIZER_TAG_JA_DECIMAL_DIGITS = 10,
    PV_NORMALIZER_TAG_JA_MEASUREMENT = 11,
    PV_NORMALIZER_TAG_JA_PER_SLASH = 12,
    PV_NORMALIZER_TAG_JA_TIME_COLON = 13,
    PV_NORMALIZER_TAG_JA_TIME_SECONDS = 14,
    PV_NORMALIZER_TAG_JA_TIME_MINUTES = 15,
    PV_NORMALIZER_TAG_JA_TIME_HOURS = 16,
    PV_NORMALIZER_TAG_JA_TIME_AM_PM = 17,
    PV_NORMALIZER_TAG_JA_FRACTION_SLASH = 18,
    PV_NORMALIZER_TAG_JA_DOT = 19,
    PV_NORMALIZER_TAG_JA_COLON = 20,
    PV_NORMALIZER_TAG_JA_ACRONYM = 21,
    PV_NORMALIZER_TAG_JA_TOP_LEVEL_DOMAIN = 22,
    PV_NORMALIZER_TAG_JA_CURRENCY = 23,
    PV_NORMALIZER_TAG_JA_CURRENCY_SYMBOL = 24,
    PV_NORMALIZER_TAG_JA_NEGATIVE_CURRENCY = 25,
    PV_NORMALIZER_TAG_JA_ABBREVIATION = 26,
    PV_NORMALIZER_TAG_JA_DIGITS = 27,
    PV_NORMALIZER_TAG_JA_DIGITS_WITH_PARENTHESES = 28,
    PV_NORMALIZER_TAG_JA_DIGITS_SEPARATOR = 29,
    PV_NORMALIZER_TAG_JA_DATE_SEPARATOR = 30,
    PV_NORMALIZER_TAG_JA_DATE_DAY = 31,
    PV_NORMALIZER_TAG_JA_DATE_MONTH = 32,
    PV_NORMALIZER_TAG_JA_DATE_YEAR = 33,
    PV_NORMALIZER_TAG_JA_NAME_INITIAL_LETTER = 34,
    PV_NORMALIZER_TAG_JA_NAME_INITIAL_DOT = 35,
    PV_NORMALIZER_TAG_JA_LETTER_SPELL_OUT = 36,
    PV_NORMALIZER_TAG_JA_SPACE = 37,
    PV_NORMALIZER_TAG_JA_NUM_TAGS = 38,
} pv_normalizer_token_tag_ja_t;

static const float PV_NORMALIZER_TOKEN_TAG_JA_WEIGHTS[PV_NORMALIZER_TAG_JA_NUM_TAGS] = {
        0.f, // 0
        1.f, // 1
        100.f, // 2
        0.5f, // 3
        1.f, // 4
        1.f, // 5
        1.f, // 6
        1.f, // 7
        0.5f, // 8
        2.f, // 9
        4.f, // 10
        4.f, // 11
        2.f, // 12
        3.f, // 13
        3.f, // 14
        3.f, // 15
        3.f, // 16
        3.f, // 17
        2.f, // 18
        1.f, // 19
        1.f, // 20
        10.f, // 21
        11.f, // 22
        5.f, // 23
        5.f, // 24
        5.f, // 25
        5.f, // 26
        2.f, // 27
        2.f, // 28
        2.f, // 29
        5.f, // 30
        5.f, // 31
        5.f, // 32
        5.f, // 33
        2.f, // 34
        2.f, // 35
        2.f, // 36
        0.5f, // 38
};

#endif // PV_NORMALIZER_TAGS_JA_H
