#ifndef PV_NORMALIZER_USE_CASES_JA_H
#define PV_NORMALIZER_USE_CASES_JA_H

#include "orca/normalizer/pv_normalizer_util.h"

typedef enum {
    PV_NORMALIZER_USE_WORD_NORMALIZER_JA = 0,
    PV_NORMALIZER_USE_CUSTOM_PRONUNCIATION_NORMALIZER_JA = 1,
    PV_NORMALIZER_USE_PUNCTUATION_NORMALIZER_JA = 2,
    PV_NORMALIZER_USE_CARDINAL_NORMALIZER_JA = 3,
    PV_NORMALIZER_USE_NEGATIVE_CARDINAL_NORMALIZER_JA = 4,
    PV_NORMALIZER_USE_NUMBER_RANGE_NORMALIZER_JA = 5,
    PV_NORMALIZER_USE_SPECIAL_CHARACTER_NORMALIZER_JA = 6,
    PV_NORMALIZER_USE_DECIMAL_NORMALIZER_JA = 7,
    PV_NORMALIZER_USE_MEASUREMENT_NORMALIZER_JA = 8,
    PV_NORMALIZER_USE_ALPHANUM_SPELL_OUT_NORMALIZER_JA = 9,
    PV_NORMALIZER_USE_TIME_NORMALIZER_JA = 10,
    PV_NORMALIZER_USE_FRACTION_NORMALIZER_JA = 11,
    PV_NORMALIZER_USE_URL_NORMALIZER_JA = 12,
    PV_NORMALIZER_USE_CURRENCY_NORMALIZER_JA = 13,
    PV_NORMALIZER_USE_ABBREVIATION_NORMALIZER_JA = 14,
    PV_NORMALIZER_USE_DIGITS_SEQUENCE_NORMALIZER_JA = 15,
    PV_NORMALIZER_USE_DATE_NORMALIZER_JA = 16,
    PV_NORMALIZER_USE_NAME_NORMALIZER_JA = 17,
    PV_NORMALIZER_NUM_CASES_JA = 18,
} pv_normalizer_use_cases_ja_t;

extern const pv_normalizer_use_cases_ja_t ALL_USE_CASES_JA[PV_NORMALIZER_NUM_CASES_JA];

#endif // PV_NORMALIZER_USE_CASES_JA_H
