#include "orca/normalizer/de/pv_normalizer_data_de/pv_normalizer_measurement_data_de.h"

const char *const PV_NORMALIZER_MEASUREMENTS_DE[PV_NORMALIZER_NUM_MEASUREMENTS_DE] = {
        "°",
        "º",

        "°C",
        "ºC",
        "°F",
        "ºF",

        "M",
        "M2",
        "M²",
        "M3",
        "M³",
        "CM",
        "CM2",
        "CM²",
        "CM3",
        "CM³",
        "MM",
        "MM2",
        "MM²",
        "MM3",
        "MM³",
        "KM",
        "KM2",
        "KM²",
        "KM3",
        "KM³",
        "DM",
        "DM2",
        "DM²",
        "DM3",
        "DM³",

        "FT",
        "FT2",
        "FT²",
        "FT3",
        "FT³",
        "YD",
        "YD2",
        "YD²",
        "YD3",
        "YD³",
        "MI",
        "MI2",
        "MI²",
        "MI3",
        "MI³",

        "G",
        "KG",
        "MG",

        "OZ",
        "LB",
        "LBS",

        "L",
        "ML",

        "GAL",
        "QT",
        "PT",

        "S",
        "MIN",
        "H",

        "KB",
        "MB",
        "GB",
        "TB",
        "PB",
        "EB",
        "ZB",
        "YB",

        "KBPS",
        "MBPS",

        "HZ",
        "MHZ",
        "GHZ",
        "THZ",

        "KW",
        "MW",
        "GW",
        "TW",
        "PW",

        "KWH",
        "MWH",
        "GWH",
        "TWH",
        "PWH",

        "PA",
        "KPA",

        "V",
        "KV",

        "RPM",
        "KCAL",
        "DB",

        "EL",
};

const char *const PV_NORMALIZER_MEASUREMENTS_VERBALIZED_SINGULAR_DE[PV_NORMALIZER_NUM_MEASUREMENTS_DE] = {
        "GRAD",
        "GRAD",

        "GRAD CELSIUS",
        "GRAD CELSIUS",
        "GRAD FAHRENHEIT",
        "GRAD FAHRENHEIT",

        "METER",
        "QUADRATMETER",
        "QUADRATMETER",
        "KUBIKMETER",
        "KUBIKMETER",
        "ZENTIMETER",
        "QUADRATZENTIMETER",
        "QUADRATZENTIMETER",
        "KUBIKZENTIMETER",
        "KUBIKZENTIMETER",
        "MILLIMETER",
        "QUADRATMILLIMETER",
        "QUADRATMILLIMETER",
        "KUBIKMILLIMETER",
        "KUBIKMILLIMETER",
        "KILOMETER",
        "QUADRATKILOMETER",
        "QUADRATKILOMETER",
        "KUBIKKILOMETER",
        "KUBIKKILOMETER",
        "DEZIMETER",
        "QUADRATDEZIMETER",
        "QUADRATDEZIMETER",
        "KUBIKDEZIMETER",
        "KUBIKDEZIMETER",

        "FUß",
        "QUADRATFUß",
        "QUADRATFUß",
        "KUBIKFUß",
        "KUBIKFUß",
        "YARD",
        "QUADRATYARD",
        "QUADRATYARD",
        "KUBIKYARD",
        "KUBIKYARD",
        "MEILE",
        "QUADRATMEILE",
        "QUADRATMEILE",
        "KUBIKMEILE",
        "KUBIKMEILE",

        "GRAMM",
        "KILOGRAMM",
        "MILLIGRAMM",

        "UNZE",
        "PFUND",
        "PFUND",

        "LITER",
        "MILLILITER",

        "GALLONE",
        "QUARTE",
        "PINT",

        "SEKUNDE",
        "MINUTE",
        "STUNDE",

        "KILOBYTE",
        "MEGABYTE",
        "GIGABYTE",
        "TERABYTE",
        "PETABYTE",
        "EXABYTE",
        "ZETTABYTE",
        "YOTTABYTE",

        "KILOBIT PRO SEKUNDE",
        "MEGABIT PRO SEKUNDE",

        "HERTZ",
        "MEGAHERTZ",
        "GIGAHERTZ",
        "TERAHERTZ",
        "KILOWATT",
        "MEGAWATT",
        "GIGAWATT",
        "TERAWATT",
        "PETAWATT",

        "KILOWATTSTUNDE",
        "MEGAWATTSTUNDE",
        "GIGAWATTSTUNDE",
        "TERAWATTSTUNDE",
        "PETAWATTSTUNDE",

        "PASCAL",
        "KILOPASCAL",

        "VOLT",
        "KILOVOLT",

        "UMDREHUNG PRO MINUTE",
        "KILOKALORIE",
        "DEZIBEL",

        "ESSLÖFFEL",
};

const char *const PV_NORMALIZER_MEASUREMENTS_VERBALIZED_PLURAL_DE[PV_NORMALIZER_NUM_MEASUREMENTS_DE] = {
        "GRAD",
        "GRAD",

        "GRAD CELSIUS",
        "GRAD CELSIUS",
        "GRAD FAHRENHEIT",
        "GRAD FAHRENHEIT",

        "METER",
        "QUADRATMETER",
        "QUADRATMETER",
        "KUBIKMETER",
        "KUBIKMETER",
        "ZENTIMETER",
        "QUADRATZENTIMETER",
        "QUADRATZENTIMETER",
        "KUBIKZENTIMETER",
        "KUBIKZENTIMETER",
        "MILLIMETER",
        "QUADRATMILLIMETER",
        "QUADRATMILLIMETER",
        "KUBIKMILLIMETER",
        "KUBIKMILLIMETER",
        "KILOMETER",
        "QUADRATKILOMETER",
        "QUADRATKILOMETER",
        "KUBIKKILOMETER",
        "KUBIKKILOMETER",
        "DEZIMETER",
        "QUADRATDEZIMETER",
        "QUADRATDEZIMETER",
        "KUBIKDEZIMETER",
        "KUBIKDEZIMETER",

        "FUß",
        "QUADRATFUß",
        "QUADRATFUß",
        "KUBIKFUß",
        "KUBIKFUß",
        "YARD",
        "QUADRATYARD",
        "QUADRATYARD",
        "KUBIKYARD",
        "KUBIKYARD",
        "MEILE",
        "QUADRATMEILE",
        "QUADRATMEILE",
        "KUBIKMEILE",
        "KUBIKMEILE",

        "GRAMM",
        "KILOGRAMM",
        "MILLIGRAMM",

        "UNZEN",
        "PFUND",
        "PFUND",

        "LITER",
        "MILLILITER",

        "GALLONEN",
        "QUARTEN",
        "PINTS",

        "SEKUNDEN",
        "MINUTEN",
        "STUNDEN",

        "KILOBYTE",
        "MEGABYTE",
        "GIGABYTE",
        "TERABYTE",
        "PETABYTE",
        "EXABYTE",
        "ZETTABYTE",
        "YOTTABYTE",

        "KILOBITS PRO SEKUNDE",
        "MEGABITS PRO SEKUNDE",

        "HERTZ",
        "MEGAHERTZ",
        "GIGAHERTZ",
        "TERAHERTZ",

        "KILOWATTS",
        "MEGAWATTS",
        "GIGAWATTS",
        "TERAWATTS",
        "PETAWATTS",

        "KILOWATTSTUNDEN",
        "MEGAWATTSTUNDEN",
        "GIGAWATTSTUNDEN",
        "TERAWATTSTUNDEN",
        "PETAWATTSTUNDEN",

        "PASCAL",
        "KILOPASCAL",

        "VOLT",
        "KILOVOLT",

        "UMDREHUNGEN PRO MINUTE",
        "KILOKALORIEN",
        "DEZIBEL",

        "ESSLÖFFEL",
};
