#include "orca/normalizer/de/pv_normalizer_data_de/pv_normalizer_word_character_data_de.h"
#include "orca/normalizer/pv_normalizer_data/pv_normalizer_shared_data.h"
#include "orca/normalizer/pv_normalizer_language_data.h"

const char *const PV_NORMALIZER_WORD_CHARACTERS_DE[PV_NORMALIZER_NUM_WORD_CHARACTERS_DE] = {
        "A",
        "a",
        "B",
        "b",
        "C",
        "c",
        "D",
        "d",
        "E",
        "e",
        "F",
        "f",
        "G",
        "g",
        "H",
        "h",
        "I",
        "i",
        "J",
        "j",
        "K",
        "k",
        "L",
        "l",
        "M",
        "m",
        "N",
        "n",
        "O",
        "o",
        "P",
        "p",
        "Q",
        "q",
        "R",
        "r",
        "S",
        "s",
        "T",
        "t",
        "U",
        "u",
        "V",
        "v",
        "W",
        "w",
        "X",
        "x",
        "Y",
        "y",
        "Z",
        "z",
        "Ä",
        "ä",
        "Ö",
        "ö",
        "Ü",
        "ü",
        "ß",
        APOSTROPHE,
};

const char *const PV_NORMALIZER_ALPHABET_CHARACTERS_DE[PV_NORMALIZER_NUM_ALPHABET_CHARACTERS_DE] = {
        "A",
        "a",
        "B",
        "b",
        "C",
        "c",
        "D",
        "d",
        "E",
        "e",
        "F",
        "f",
        "G",
        "g",
        "H",
        "h",
        "I",
        "i",
        "J",
        "j",
        "K",
        "k",
        "L",
        "l",
        "M",
        "m",
        "N",
        "n",
        "O",
        "o",
        "P",
        "p",
        "Q",
        "q",
        "R",
        "r",
        "S",
        "s",
        "T",
        "t",
        "U",
        "u",
        "V",
        "v",
        "W",
        "w",
        "X",
        "x",
        "Y",
        "y",
        "Z",
        "z",
        "Ä",
        "ä",
        "Ö",
        "ö",
        "Ü",
        "ü",
        "ß",
};

const char *const PV_ORCA_PHONEMIZER_DE_ALPHABET_UPPERCASE_LETTERS[PV_ORCA_PHONEMIZER_DE_ALPHABET_NUM_LETTERS] = {
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
        "Ä",
        "Ö",
        "Ü",
};

const char *const PV_ORCA_PHONEMIZER_DE_ALPHABET_PRONUNCIATIONS[PV_ORCA_PHONEMIZER_DE_ALPHABET_NUM_LETTERS] = {
        "a",
        "b e",
        "ʦ e",
        "d e",
        "e",
        "ɛ f",
        "g e",
        "h a",
        "i",
        "j ɔ t",
        "k a",
        "ɛ l",
        "ɛ m",
        "ɛ n",
        "o",
        "p e",
        "k u",
        "ɛ r",
        "ɛ s",
        "t e",
        "u",
        "f aʊ",
        "v e",
        "ɪ k s",
        "ʏ p s ɪ l ɔ n",
        "ʦ ɛ t",
        "ɛː",
        "ø",
        "y",
};

const char *PV_ORCA_STREAM_DE_EOS_PUNCTUATIONS[] = {".", "?", "!"};
const char *PV_ORCA_STREAM_DE_FALLBACK_CUTOFF_CHARACTERS[] = {":", ","};

