#include "orca/normalizer/de/pv_normalizer_data_de/pv_normalizer_currency_data_de.h"

const char *const PV_NORMALIZER_CURRENCIES_DE[PV_NORMALIZER_NUM_CURRENCIES_DE] = {
        "$",
        "€",
        "¥", // Note: JPY and CNY use the same unicode symbol. Currently verbalizes to YUAN
        "₪",
        "£",
        "₩",
        "₺",
        "₱",
        "₽",
        "฿",
        "₴",
        "₹",
        "¢",

        "USD",
        "EUR",
        "CAD",
        "JPY",
        "GBP",
        "AUD",
        "CHF",
        "CNY",
        "SEK",
        "NZD",
        "MXN",
        "SGD",
        "HKD",
        "NOK",
        "KRW",
        "TRY",
        "RUB",
        "INR",
        "BRL",
        "ZAR",
        "DKK",
        "PLN",
        "THB",
        "IDR",
        "MYR",
        "CZK",
        "HUF",
        "ILS",
        "ARS",
        "PHP",
        "CLP",
        "COP",
        "EGP",
        "SAR",
        "AED",
        "KWD",
        "PKR",
        "BDT",
        "NGN",
        "VES",
};

const char *const PV_NORMALIZER_CURRENCIES_VERBALIZED_DE[PV_NORMALIZER_NUM_CURRENCIES_DE] = {
        "DOLLAR",
        "EURO",
        "YUAN",
        "SCHEKEL",
        "PFUND",
        "WON",
        "LIRA",
        "PESO",
        "RUBEL",
        "BAHT",
        "HRYWNJA",
        "RUPIE",
        "CENT",

        "US-DOLLAR",
        "EURO",
        "KANADISCHER DOLLAR",
        "JAPANISCHER YEN",
        "BRITISCHES PFUND",
        "AUSTRALISCHER DOLLAR",
        "SCHWEIZER FRANKEN",
        "CHINESISCHER YUAN",
        "SCHWEDISCHE KRONE",
        "NEUSEELÄNDISCHER DOLLAR",
        "MEXIKANISCHER PESO",
        "SINGAPUR-DOLLAR",
        "HONGKONG-DOLLAR",
        "NORWEGISCHE KRONE",
        "SÜDKOREANISCHER WON",
        "TÜRKISCHE LIRA",
        "RUSSISCHER RUBEL",
        "INDISCHE RUPIE",
        "BRASILIANISCHER REAL",
        "SÜDAFRIKANISCHER RAND",
        "DÄNISCHE KRONE",
        "POLNISCHER ZŁOTY",
        "THAILÄNDISCHER BAHT",
        "INDONESISCHE RUPIAH",
        "MALAYSISCHER RINGGIT",
        "TSCHECHISCHE KRONE",
        "UNGARISCHER FORINT",
        "ISRAELISCHER SCHEKEL",
        "ARGENTINISCHER PESO",
        "PHILIPPINISCHER PESO",
        "CHILENISCHER PESO",
        "KOLUMBIANISCHER PESO",
        "ÄGYPTISCHES PFUND",
        "SAUDI-RIAL",
        "VAE-DIRHAM",
        "KUWAIT-DINAR",
        "PAKISTANISCHE RUPIE",
        "BANGLADESCH-TAKA",
        "NIGERIANISCHER NAIRA",
        "VENEZOLANISCHER BOLÍVAR",
};

const char *const PV_NORMALIZER_SUB_CURRENCIES_VERBALIZED_DE[PV_NORMALIZER_NUM_CURRENCIES_DE] = {
        "CENT",
        "CENT",
        "FEN",
        "AGORA",
        "PENNY",
        "JEON",
        "KURUS",
        "SENTIMO",
        "KOPEKE",
        "SATANG",
        "KOPIJKA",
        "PAISA",
        "",

        "CENT",
        "CENT",
        "CENT",
        "SEN",
        "PENNY",
        "CENT",
        "RAPPEN",
        "FEN",
        "ÖRE",
        "CENT",
        "CENTAVO",
        "CENT",
        "CENT",
        "ØRE",
        "JEON",
        "KURUS",
        "KOPEKE",
        "PAISA",
        "CENTAVO",
        "CENT",
        "ØRE",
        "GROSZ",
        "SATANG",
        "SEN",
        "SEN",
        "HELLER",
        "FILLER",
        "AGORA",
        "CENTAVO",
        "SENTIMO",
        "CENTAVO",
        "CENTAVO",
        "PIASTER",
        "HALALA",
        "FILS",
        "FILS",
        "PAISA",
        "POYSHA",
        "KOBO",
        "CÉNTIMO",
};