#include "orca/normalizer/de/pv_normalizer_data_de/pv_normalizer_date_data_de.h"

const char *const PV_NORMALIZER_MONTH_NAMES_DE[PV_NORMALIZER_NUM_MONTH_NAMES_DE] = {
        "Januar",
        "Februar",
        "März",
        "April",
        "Mai",
        "Juni",
        "Juli",
        "August",
        "September",
        "Oktober",
        "November",
        "Dezember",

        "Jan",
        "Feb",
        "Mär",
        "Apr",
        "Mai",
        "Jun",
        "Jul",
        "Aug",
        "Sep",
        "Okt",
        "Nov",
        "Dez",
};

const char *const PV_NORMALIZER_MONTH_NAMES_VERBALIZED_DE[PV_NORMALIZER_NUM_MONTH_NAMES_DE] = {
        "JANUAR",
        "FEBRUAR",
        "MÄRZ",
        "APRIL",
        "MAI",
        "JUNI",
        "JULI",
        "AUGUST",
        "SEPTEMBER",
        "OKTOBER",
        "NOVEMBER",
        "DEZEMBER",

        "JANUAR",
        "FEBRUAR",
        "MÄRZ",
        "APRIL",
        "MAI",
        "JUNI",
        "JULI",
        "AUGUST",
        "SEPTEMBER",
        "OKTOBER",
        "NOVEMBER",
        "DEZEMBER",
};