#include "orca/normalizer/de/pv_normalizer_data_de/pv_normalizer_special_character_data_de.h"
#include "orca/normalizer/pv_normalizer_data/pv_normalizer_shared_data.h"

const char *const PV_NORMALIZER_SPECIAL_CHARACTERS_DE[PV_NORMALIZER_NUM_SPECIAL_CHARACTERS_DE] = {
        "@",
        "%",
        "&",
        "\n",
        "_",
        "(",
        ")",
        "°C",
        "ºC",
        "°F",
        "ºF",
        "°",
        "º",
        "M²",
        "M³",
        "CM²",
        "CM³",
        "MM²",
        "MM³",
        "KM²",
        "KM³",
        "DM²",
        "DM³",
        "FT²",
        "FT³",
        "YD²",
        "YD³",
        "MI²",
        "MI³",
        "KBPS",
        "MBPS",
        "MHZ",
        "GHZ",
        "RPM",
        "KCAL",
        "+",
        "=",
        "/",
        EM_DASH,
        HORIZONTAL_BAR,
        HORIZONTAL_ELLIPSIS,
        RIGHT_DOUBLE_QUOTATION_MARK,
        LEFT_DOUBLE_QUOTATION_MARK,
};

const char *const PV_NORMALIZER_SPECIAL_CHARACTERS_VERBALIZED_DE[PV_NORMALIZER_NUM_SPECIAL_CHARACTERS_DE] = {
        "BEI",
        "PROZENT",
        "UND",
        ".",
        "UNTERSTRICH",
        ",",
        ",",
        "GRAD CELSIUS",
        "GRAD CELSIUS",
        "GRAD FAHRENHEIT",
        "GRAD FAHRENHEIT",
        "GRAD",
        "GRAD",
        "QUADRATMETER",
        "KUBIKMETER",
        "QUADRATZENTIMETER",
        "KUBIKZENTIMETER",
        "QUADRATMILLIMETER",
        "KUBIKMILLIMETER",
        "QUADRATKILOMETER",
        "KUBIKKILOMETER",
        "QUADRATDEZIMETER",
        "KUBIKDEZIMETER",
        "QUADRATFUSS",
        "KUBIKFUSS",
        "QUADRATYARD",
        "KUBIKYARD",
        "QUADRATMILEN",
        "KUBIKMILEN",
        "KILOBIT PRO SEKUNDE",
        "MEGABIT PRO SEKUNDE",
        "MEGAHERTZ",
        "GIGAHERTZ",
        "UMDREHUNGEN PRO MINUTE",
        "KILOKALORIEN",
        "PLUS",
        "GLEICH",
        "SCHRÄGSTRICH",
        ",",
        ",",
        ".",
        "\"",
        "\"",
};

bool const PV_NORMALIZER_SPECIAL_CHARACTERS_IS_VERBALIZED_TO_PUNCTUATION_DE[PV_NORMALIZER_NUM_SPECIAL_CHARACTERS_DE] = {
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
};
