#include <stdbool.h>

#include "orca/normalizer/pt/pv_normalizer_data_pt/pv_normalizer_measurement_data_pt.h"

const char *const PV_NORMALIZER_MEASUREMENTS_PT[PV_NORMALIZER_NUM_MEASUREMENTS_PT] = {
        "°",

        "°C",
        "°F",

        "M",
        "M2",
        "M²",
        "M3",
        "M³",
        "CM",
        "CM2",
        "CM²",
        "CM3",
        "CM³",
        "MM",
        "MM2",
        "MM²",
        "MM3",
        "MM³",
        "KM",
        "KM2",
        "KM²",
        "KM3",
        "KM³",
        "DM",
        "DM2",
        "DM²",
        "DM3",
        "DM³",

        "FT",
        "FT2",
        "FT²",
        "FT3",
        "FT³",
        "YD",
        "YD2",
        "YD²",
        "YD3",
        "YD³",
        "MI",
        "MI2",
        "MI²",
        "MI3",
        "MI³",

        "G",
        "KG",
        "MG",

        "OZ",
        "LB",
        "LBS",

        "L",
        "ML",

        "GAL",
        "QT",
        "PT",

        "S",
        "SEG",
        "MIN",
        "H",

        "KB",
        "MB",
        "GB",
        "TB",
        "PB",
        "EB",
        "ZB",
        "YB",

        "KBPS",
        "MBPS",

        "HZ",
        "MHZ",
        "GHZ",
        "THZ",

        "W",
        "KW",
        "MW",
        "GW",
        "TW",
        "PW",

        "KWH",
        "MWH",
        "GWH",
        "TWH",
        "PWH",

        "PA",
        "KPA",

        "V",
        "KV",

        "RPM",
        "KCAL",
        "DB",
        "RAD",

        "mAh",
};

const char *const PV_NORMALIZER_MEASUREMENTS_VERBALIZED_SINGULAR_PT[PV_NORMALIZER_NUM_MEASUREMENTS_PT] = {
        "GRAU",

        "GRAU CELSIUS",
        "GRAU FAHRENHEIT",

        "METRO",
        "METRO QUADRADO",
        "METRO QUADRADO",
        "METRO CÚBICO",
        "METRO CÚBICO",
        "CENTÍMETRO",
        "CENTÍMETRO QUADRADO",
        "CENTÍMETRO QUADRADO",
        "CENTÍMETRO CÚBICO",
        "CENTÍMETRO CÚBICO",
        "MILÍMETRO",
        "MILÍMETRO QUADRADO",
        "MILÍMETRO QUADRADO",
        "MILÍMETRO CÚBICO",
        "MILÍMETRO CÚBICO",
        "QUILÓMETRO",
        "QUILÓMETRO QUADRADO",
        "QUILÓMETRO QUADRADO",
        "QUILÓMETRO CÚBICO",
        "QUILÓMETRO CÚBICO",
        "DECÍMETRO",
        "DECÍMETRO QUADRADO",
        "DECÍMETRO QUADRADO",
        "DECÍMETRO CÚBICO",
        "DECÍMETRO CÚBICO",

        "PÉ",
        "PÉ QUADRADO",
        "PÉ QUADRADO",
        "PÉ CÚBICO",
        "PÉ CÚBICO",
        "JARDA",
        "JARDA QUADRADA",
        "JARDA QUADRADA",
        "JARDA CÚBICA",
        "JARDA CÚBICA",
        "MILHA",
        "MILHA QUADRADA",
        "MILHA QUADRADA",
        "MILHA CÚBICA",
        "MILHA CÚBICA",

        "GRAMA",
        "QUILOGRAMA",
        "MILIGRAMA",

        "ONÇA",
        "LIBRA",
        "LIBRA",

        "LITRO",
        "MILILITRO",

        "GALÃO",
        "QUARTO",
        "PINTA",

        "SEGUNDO",
        "SEGUNDO",
        "MINUTO",
        "HORA",

        "KILOBYTE",
        "MEGABYTE",
        "GIGABYTE",
        "TERABYTE",
        "PETABYTE",
        "EXABYTE",
        "ZETTABYTE",
        "YOTTABYTE",

        "KILOBIT POR SEGUNDO",
        "MEGABIT POR SEGUNDO",

        "HERTZ",
        "MEGAHERTZ",
        "GIGAHERTZ",
        "TERAHERTZ",

        "WATT",
        "QUILOWATT",
        "MEGAWATT",
        "GIGAWATT",
        "TERAWATT",
        "PETAWATT",

        "QUILOWATT HORA",
        "MEGAWATT HORA",
        "GIGAWATT HORA",
        "TERAWATT HORA",
        "PETAWATT HORA",

        "PASCAL",
        "KILOPASCAL",

        "VOLT",
        "KILOVOLT",

        "REVOLUÇÃO POR MINUTO",
        "KILO CALORIA",
        "DECIBEL",
        "RADIANO",

        "MILIAMPERE HORAS",
};

const char *const PV_NORMALIZER_MEASUREMENTS_VERBALIZED_PLURAL_PT[PV_NORMALIZER_NUM_MEASUREMENTS_PT] = {
        "GRAUS",

        "GRAUS CELSIUS",
        "GRAUS FAHRENHEIT",

        "METROS",
        "METROS QUADRADOS",
        "METROS QUADRADOS",
        "METROS CÚBICOS",
        "METROS CÚBICOS",
        "CENTÍMETROS",
        "CENTÍMETROS QUADRADOS",
        "CENTÍMETROS QUADRADOS",
        "CENTÍMETROS CÚBICOS",
        "CENTÍMETROS CÚBICOS",
        "MILÍMETROS",
        "MILÍMETROS QUADRADOS",
        "MILÍMETROS QUADRADOS",
        "MILÍMETROS CÚBICOS",
        "MILÍMETROS CÚBICOS",
        "QUILÓMETROS",
        "QUILÓMETROS QUADRADOS",
        "QUILÓMETROS QUADRADOS",
        "QUILÓMETROS CÚBICOS",
        "QUILÓMETROS CÚBICOS",
        "DECÍMETROS",
        "DECÍMETROS QUADRADOS",
        "DECÍMETROS QUADRADOS",
        "DECÍMETROS CÚBICOS",
        "DECÍMETROS CÚBICOS",

        "PÉS",
        "PÉS QUADRADOS",
        "PÉS QUADRADOS",
        "PÉS CÚBICOS",
        "PÉS CÚBICOS",
        "JARDAS",
        "JARDAS QUADRADAS",
        "JARDAS QUADRADAS",
        "JARDAS CÚBICAS",
        "JARDAS CÚBICAS",
        "MILHAS",
        "MILHAS QUADRADAS",
        "MILHAS QUADRADAS",
        "MILHAS CÚBICAS",
        "MILHAS CÚBICAS",

        "GRAMAS",
        "QUILOGRAMAS",
        "MILIGRAMAS",

        "ONÇAS",
        "LIBRAS",
        "LIBRAS",

        "LITROS",
        "MILILITROS",

        "GALÕES",
        "QUARTOS",
        "PINTAS",

        "SEGUNDOS",
        "SEGUNDOS",
        "MINUTOS",
        "HORAS",

        "KILOBYTES",
        "MEGABYTES",
        "GIGABYTES",
        "TERABYTES",
        "PETABYTES",
        "EXABYTES",
        "ZETTABYTES",
        "YOTTABYTES",

        "KILOBITS POR SEGUNDO",
        "MEGABITS POR SEGUNDO",

        "HERTZ",
        "MEGAHERTZ",
        "GIGAHERTZ",
        "TERAHERTZ",

        "WATTS",
        "QUILOWATTS",
        "MEGAWATTS",
        "GIGAWATTS",
        "TERAWATTS",
        "PETAWATTS",

        "QUILOWATT HORAS",
        "MEGAWATT HORAS",
        "GIGAWATT HORAS",
        "TERAWATT HORAS",
        "PETAWATT HORAS",

        "PASCALS",
        "KILOPASCALS",

        "VOLTS",
        "KILOVOLTS",

        "REVOLUÇÕES POR MINUTO",
        "KILO CALORIAS",
        "DECIBEL",
        "RADIANOS",

        "MILIAMPERE HORAS",
};

const bool PV_NORMALIZER_MEASUREMENTS_IS_FEMININE[PV_NORMALIZER_NUM_MEASUREMENTS_PT] = {
        false,

        false,
        false,

        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,

        false,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,

        false,
        false,
        false,

        true,
        true,
        true,

        false,
        false,

        false,
        false,
        true,

        false,
        false,
        false,
        true,

        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,

        false,
        false,

        false,
        false,
        false,
        false,

        false,
        false,
        false,
        false,
        false,
        false,

        false,
        false,
        false,
        false,
        false,

        false,
        false,

        false,
        false,

        false,
        false,
        false,
        false,

        false,
};