#include "orca/normalizer/pt/pv_normalizer_data_pt/pv_normalizer_number_data_pt.h"

const int64_t MAX_VERBALIZED_CARDINAL_PT = 1000000000000000 - 1; // 1 quadrillion

const int64_t MAX_MULTIPLIER_PT = 1000000000000; // 1 trillion

const char *NUMBER_RANGE_INBETWEEN_STRING_PT = "A";

// masculine and feminine for one and two
const char *const ONE_TWO_MASCULINE_PT[3] = {"", "UM", "DOIS"};
const char *const ONE_TWO_FEMININE_PT[3] = {"", "UMA", "DUAS"};

const char *const ZERO_TO_NINETEEN_NO_GENDER_PT[20] = {
    "ZERO", "UM", "DOIS", "TRÊS", "QUATRO", "CINCO", "SEIS", "SETE", "OITO", "NOVE", "DEZ", "ONZE", "DOZE",
    "TREZE", "CATORZE", "QUINZE", "DEZASSEIS", "DEZASSETE", "DEZOITO", "DEZANOVE"};

const char *const TENS_PT[9] = {"", "VINTE", "TRINTA", "QUARENTA", "CINQUENTA", "SESSENTA", "SETENTA", "OITENTA", "NOVENTA"};

// Cem (one hundred) or Cento when followed by another number, eg. 103
const char *const ONE_HUNDREDS_PT[2] = {"CEM", "CENTO"};

const char *const HUNDREDS_TWO_TO_NINE_MASCULINE_PT[10] = {
        "", "", "DUZENTOS", "TREZENTOS", "QUATROCENTOS", "QUINHENTOS", "SEISCENTOS", "SETECENTOS", "OITOCENTOS", "NOVECENTOS"};
const char *const HUNDREDS_TWO_TO_NINE_FEMININE_PT[10] = {
        "", "", "DUZENTAS", "TREZENTAS", "QUATROCENTAS", "QUINHENTAS", "SEISCENTAS", "SETECENTAS", "OITOCENTAS", "NOVECENTAS"};

const char *const MULTIPLIERS_SINGULAR_PT[5] = {"", "BILHÃO", "MIL", "MILHÃO", "MIL"};
const char *const MULTIPLIERS_PLURAL_PT[5] = {"", "BILHÕES", "MIL", "MILHÕES", "MIL"};

const char *DENOMINATOR_STRING_PT = " AVOS";
const char *const DENOMINATOR_ORDINAL_KEYS_PT[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_PT] = {
    "2", "3", "4", "5", "6", "7", "8", "9", "10",
    "20", "30", "40", "50", "60", "70", "80", "90", "100",
    "1000", "1000000", "1000000000", "1000000000000"};
const char *const DENOMINATOR_ORDINAL_VALUES_SINGULAR_PT[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_PT] = {
    "MEIO", "TERÇO", "QUARTO", "QUINTO", "SEXTO", "SÉTIMO", "OITAVO", "NONO", "DÉCIMO",
    "VIGÉSIMO", "TRIGÉSIMO", "QUADRAGÉSIMO", "QUINQUAGÉSIMO", "SEXAGÉSIMO", "SEPTUAGÉSIMO", "OCTOGÉSIMO", "NONAGÉSIMO", "CENTÉSIMO",
    "MILÉSIMO", "MILIONÉSIMO", "MILÉSIMO MILIONÉSIMO", "BILLIONÉSIMO"};

const char *const DENOMINATOR_ORDINAL_VALUES_PLURAL_PT[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_PT] = {
    "MEIOS", "TERÇOS", "QUARTOS", "QUINTOS", "SEXTOS", "SÉTIMOS", "OITAVOS", "NONOS", "DÉCIMOS",
    "VIGÉSIMOS", "TRIGÉSIMOS", "QUADRAGÉSIMOS", "QUINQUAGÉSIMOS", "SEXAGÉSIMOS", "SEPTUAGÉSIMOS", "OCTOGÉSIMOS", "NONAGÉSIMOS", "CENTÉSIMOS",
    "MILÉSIMOS", "MILIONÉSIMOS", "MILÉSIMOS MILIONÉSIMOS", "BILLIONÉSIMOS"};

const char *const ORDINAL_VALID_SUPERSCRIPT_PT[PV_NORMALIZER_NUM_VALID_SUPERSCRIPT_PT] = {"º", "ª"};
const bool ORDINAL_SUPERSCRIPT_IS_FEMININE_PT[PV_NORMALIZER_NUM_VALID_SUPERSCRIPT_PT] = {false, true};

const char *const ORDINAL_ZERO_TO_NINE_MASCULINE_PT[10] = {
    "ZERÉSIMO", "PRIMEIRO", "SEGUNDO", "TERCEIRO", "QUARTO", "QUINTO", "SEXTO", "SÉTIMO", "OITAVO", "NONO"};
const char *const ORDINAL_ZERO_TO_NINE_FEMININE_PT[10] = {
    "ZERÉSIMA", "PRIMEIRA", "SEGUNDA", "TERCEIRA", "QUARTA", "QUINTA", "SEXTA", "SÉTIMA", "OITAVA", "NONA"};

const char *const ORDINAL_TENS_MASCULINE_PT[10] = {
    "", "DÉCIMO", "VIGÉSIMO", "TRIGÉSIMO", "QUADRAGÉSIMO", "QUINQUAGÉSIMO", "SEXAGÉSIMO", "SEPTUAGÉSIMO", "OCTOGÉSIMO", "NONAGÉSIMO"};
const char *const ORDINAL_TENS_FEMININE_PT[10] = {
    "", "DÉCIMA", "VIGÉSIMA", "TRIGÉSIMA", "QUADRAGÉSIMA", "QUINQUAGÉSIMA", "SEXAGÉSIMA", "SEPTUAGÉSIMA", "OCTOGÉSIMA", "NONAGÉSIMA"};

const char *const ORDINAL_HUNDREDS_MASCULINE_PT[10] = {
    "", "CENTÉSIMO", "DUCENTÉSIMO", "TRICENTÉSIMO", "QUADRINGENTÉSIMO", "QUINGENTÉSIMO",
    "SEXCENTÉSIMO", "SEPTINGENTÉSIMO", "OCTINGENTÉSIMO", "NONINGENTÉSIMO"};
const char *const ORDINAL_HUNDREDS_FEMININE_PT[10] = {
    "", "CENTÉSIMA", "DUCENTÉSIMA", "TRICENTÉSIMA", "QUADRINGENTÉSIMA", "QUINGENTÉSIMA",
    "SEXCENTÉSIMA", "SEPTINGENTÉSIMA", "OCTINGENTÉSIMA", "NONINGENTÉSIMA"};

const char *const ORDINAL_MULTIPLIERS_MASCULINE_PT[5] = {
    "", "BILIONÉSIMO", "MILÉSIMO", "MILIONÉSIMO", "MILÉSIMO"};
const char *const ORDINAL_MULTIPLIERS_FEMININE_PT[5] = {
    "", "BILIONÉSIMA", "MILÉSIMA", "MILIONÉSIMA", "MILÉSIMA"};
