#include "orca/normalizer/pt/pv_normalizer_data_pt/pv_normalizer_special_character_data_pt.h"
#include "orca/normalizer/pv_normalizer_data/pv_normalizer_shared_data.h"
#include <stdbool.h>

const char *const PV_NORMALIZER_SPECIAL_CHARACTERS_PT[PV_NORMALIZER_NUM_SPECIAL_CHARACTERS_PT] = {
        "@",
        "%",
        "&",
        "\n",
        "_",
        "(",
        ")",

        "°C",
        "°F",
        "°",
        "M²",
        "M³",
        "CM²",
        "CM³",
        "MM²",
        "MM³",
        "KM²",
        "KM³",
        "DM²",
        "DM³",
        "FT²",
        "FT³",
        "YD²",
        "YD³",
        "MI²",
        "MI³",
        "KBPS",
        "MBPS",
        "MHZ",
        "GHZ",
        "RPM",
        "KCAL",

        "²",
        "³",
        "+",
        "=",
        "/",
        "º",
        "ª",
        "nº",
        "#",
        "[",
        "]",
        EM_DASH,
        HORIZONTAL_BAR,
        HORIZONTAL_ELLIPSIS,
        RIGHT_DOUBLE_QUOTATION_MARK,
        LEFT_DOUBLE_QUOTATION_MARK,
};

const char *const PV_NORMALIZER_SPECIAL_CHARACTERS_VERBALIZED_PT[PV_NORMALIZER_NUM_SPECIAL_CHARACTERS_PT] = {
        "ARROBA",
        "POR CENTO",
        "E",
        ".",
        "SUBLINHADO",
        ",",
        ",",

        "GRAUS CELSIUS",
        "GRAUS FAHRENHEIT",
        "GRAUS",
        "METROS QUADRADOS",
        "METROS CÚBICOS",
        "CENTÍMETROS QUADRADOS",
        "CENTÍMETROS CÚBICOS",
        "MILÍMETROS QUADRADOS",
        "MILÍMETROS CÚBICOS",
        "QUILÓMETROS QUADRADOS",
        "QUILÓMETROS CÚBICOS",
        "DECÍMETROS QUADRADOS",
        "DECÍMETROS CÚBICOS",
        "PÉS QUADRADOS",
        "PÉS CÚBICOS",
        "JARDAS QUADRADAS",
        "JARDAS CÚBICAS",
        "MILHAS QUADRADAS",
        "MILHAS CÚBICAS",
        "KILOBITS POR SEGUNDO",
        "MEGABITS POR SEGUNDO",
        "MEGAHERTZ",
        "GIGAHERTZ",
        "REVOLUÇÕES POR MINUTO",
        "KILO CALORIAS",

        "SOBRESCRITO DOIS",
        "SOBRESCRITO TRÊS",

        "MAIS",
        "IGUAL",
        "BARRA",

        "Ó",
        "Á",
        "NÚMERO",
        "NÚMERO",

        ",",
        ",",
        ",",
        ",",
        ".",
        "\"",
        "\"",
};

bool const PV_NORMALIZER_SPECIAL_CHARACTERS_IS_VERBALIZED_TO_PUNCTUATION_PT[PV_NORMALIZER_NUM_SPECIAL_CHARACTERS_PT] = {
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
};
