// Put all characters that can be a part of a word in the language, for example in English we have all upper and lower case alphabet letters as well as apostrophe "'".

#include "orca/normalizer/pt/pv_normalizer_data_pt/pv_normalizer_word_character_data_pt.h"
#include "orca/normalizer/pv_normalizer_data/pv_normalizer_shared_data.h"
#include "orca/normalizer/pv_normalizer_language_data.h"

const char *const PV_NORMALIZER_WORD_CHARACTERS_PT[PV_NORMALIZER_NUM_WORD_CHARACTERS_PT] = {
        "A",
        "a",
        "B",
        "b",
        "C",
        "c",
        "D",
        "d",
        "E",
        "e",
        "F",
        "f",
        "G",
        "g",
        "H",
        "h",
        "I",
        "i",
        "J",
        "j",
        "K",
        "k",
        "L",
        "l",
        "M",
        "m",
        "N",
        "n",
        "O",
        "o",
        "P",
        "p",
        "Q",
        "q",
        "R",
        "r",
        "S",
        "s",
        "T",
        "t",
        "U",
        "u",
        "V",
        "v",
        "W",
        "w",
        "X",
        "x",
        "Y",
        "y",
        "Z",
        "z",
        "À",
        "à",
        "Á",
        "á",
        "Â",
        "â",
        "Ã",
        "ã",
        "Ç",
        "ç",
        "È",
        "è",
        "É",
        "é",
        "Ê",
        "ê",
        "Í",
        "í",
        "Ó",
        "ó",
        "Ô",
        "ô",
        "Õ",
        "õ",
        "Ú",
        "ú",
        APOSTROPHE,
};

const char *const PV_NORMALIZER_ALPHABET_CHARACTERS_PT[PV_NORMALIZER_NUM_ALPHABET_CHARACTERS_PT] = {
        "A",
        "a",
        "B",
        "b",
        "C",
        "c",
        "D",
        "d",
        "E",
        "e",
        "F",
        "f",
        "G",
        "g",
        "H",
        "h",
        "I",
        "i",
        "J",
        "j",
        "K",
        "k",
        "L",
        "l",
        "M",
        "m",
        "N",
        "n",
        "O",
        "o",
        "P",
        "p",
        "Q",
        "q",
        "R",
        "r",
        "S",
        "s",
        "T",
        "t",
        "U",
        "u",
        "V",
        "v",
        "W",
        "w",
        "X",
        "x",
        "Y",
        "y",
        "Z",
        "z",
        "À",
        "à",
        "Á",
        "á",
        "Â",
        "â",
        "Ã",
        "ã",
        "Ç",
        "ç",
        "È",
        "è",
        "É",
        "é",
        "Ê",
        "ê",
        "Í",
        "í",
        "Ó",
        "ó",
        "Ô",
        "ô",
        "Õ",
        "õ",
        "Ú",
        "ú",
};

const char *const PV_ORCA_PHONEMIZER_PT_ALPHABET_UPPERCASE_LETTERS[PV_ORCA_PHONEMIZER_PT_ALPHABET_NUM_LETTERS] = {
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
        "À",
        "Á",
        "Â",
        "Ã",
        "Ç",
        "È",
        "É",
        "Ê",
        "Í",
        "Ó",
        "Ô",
        "Õ",
        "Ú",
};

const char *const PV_ORCA_PHONEMIZER_PT_ALPHABET_PRONUNCIATIONS[PV_ORCA_PHONEMIZER_PT_ALPHABET_NUM_LETTERS] = {
        "ɐ",
        "b e",
        "s e",
        "d e",
        "i",
        "ɛ f i",
        "ʒ e",
        "ɐ ɡ ɐ",
        "i",
        "ʒ ɔ t ɐ",
        "k ɐ",
        "ɛ l i",
        "e m i",
        "e n i",
        "u",
        "p e",
        "k e",
        "ɛ ʁ i",
        "ɛ s i",
        "t e",
        "u",
        "v e",
        "d ɐ b i w j u",
        "ʃ i ʃ",
        "i p i s i l õ",
        "z e",
        "ɐ",
        "ɐ ɐ s ẽ t u ɐ ɡ u d u",
        "ɐ ɐ s ẽ t u s i ɾ k ũ f l ɛ k i s u",
        "ɐ t i w",
        "s e s e d i ʎ ɐ",
        "e ɐ s ẽ t u ɡ ɾ ɐ v i",
        "ɛ",
        "ɛ ɐ s ẽ t u s i ɾ k ũ f l ɛ k i s u",
        "i ɐ s ẽ t u ɐ ɡ u d u",
        "ɔ",
        "o",
        "ɔ t i w",
        "u ɐ s ẽ t u ɐ ɡ u d u",
};

const char *PV_ORCA_STREAM_PT_EOS_PUNCTUATIONS[] = {".", "?", "!"};
const char *PV_ORCA_STREAM_PT_FALLBACK_CUTOFF_CHARACTERS[] = {":", ","};

