#ifndef PV_NORMALIZER_TOP_LEVEL_DOMAIN_JA_H
#define PV_NORMALIZER_TOP_LEVEL_DOMAIN_JA_H

#include <stdbool.h>

#define PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS_JA (20)

extern const char *const PV_NORMALIZER_TOP_LEVEL_DOMAINS_JA[PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS_JA];
extern const char *const PV_NORMALIZER_TOP_LEVEL_DOMAINS_VERBALIZED_JA[PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS_JA];

#endif // PV_NORMALIZER_TOP_LEVEL_DOMAIN_JA_H