#ifndef PV_NORMALIZER_CURRENCY_DATA_JA_H
#define PV_NORMALIZER_CURRENCY_DATA_JA_H

#define PV_NORMALIZER_NUM_CURRENCIES_JA (53)

extern const char *const PV_NORMALIZER_CURRENCIES_JA[PV_NORMALIZER_NUM_CURRENCIES_JA];
extern const char *const PV_NORMALIZER_CURRENCIES_VERBALIZED_JA[PV_NORMALIZER_NUM_CURRENCIES_JA];
extern const char *const PV_NORMALIZER_SUB_CURRENCIES_VERBALIZED_JA[PV_NORMALIZER_NUM_CURRENCIES_JA];

#endif // PV_NORMALIZER_CURRENCY_DATA_JA_H
