#ifndef PV_NORMALIZER_ACRONYM_DATA_JA_H
#define PV_NORMALIZER_ACRONYM_DATA_JA_H

#define PV_NORMALIZER_NUM_ACRONYMS_JA (4)

extern const char *const PV_NORMALIZER_ACRONYMS_JA[PV_NORMALIZER_NUM_ACRONYMS_JA];

#endif // PV_NORMALIZER_ACRONYM_DATA_JA_H