#ifndef PV_NORMALIZER_PUNCTUATION_DATA_JA_H
#define PV_NORMALIZER_PUNCTUATION_DATA_JA_H

#define PV_NORMALIZER_NUM_PUNCTUATION_JA (10)

extern const char *const PV_NORMALIZER_PUNCTUATION_JA[PV_NORMALIZER_NUM_PUNCTUATION_JA];
extern const char *const PV_NORMALIZER_PUNCTUATION_VERBALIZED_JA[PV_NORMALIZER_NUM_PUNCTUATION_JA];

#endif // PV_NORMALIZER_PUNCTUATION_DATA_JA_H
