#ifndef PV_NORMALIZER_DATE_DATA_JA_H
#define PV_NORMALIZER_DATE_DATA_JA_H

#define PV_NORMALIZER_NUM_MONTH_NAMES_JA (21)
#define PV_NORMALIZER_NUM_DAY_NAMES_JA (40)

extern const char *const PV_NORMALIZER_MONTH_NAMES_JA[PV_NORMALIZER_NUM_MONTH_NAMES_JA];
extern const char *const PV_NORMALIZER_MONTH_NAMES_VERBALIZED_JA[PV_NORMALIZER_NUM_MONTH_NAMES_JA];

extern const char *const PV_NORMALIZER_DAY_NAMES_JA[PV_NORMALIZER_NUM_DAY_NAMES_JA];
extern const char *const PV_NORMALIZER_DAY_NAMES_VERBALIZED_JA[PV_NORMALIZER_NUM_DAY_NAMES_JA];
extern const char *const PV_NORMALIZER_DAY_MARKER_NAMES_VERBALIZED_JA[PV_NORMALIZER_NUM_DAY_NAMES_JA];

#endif // PV_NORMALIZER_DATE_DATA_JA_H
