#ifndef PV_NORMALIZER_TAGS_ES_H
#define PV_NORMALIZER_TAGS_ES_H

typedef enum {
    PV_NORMALIZER_TAG_ES_NONE = 0,
    PV_NORMALIZER_TAG_ES_WORD,
    PV_NORMALIZER_TAG_ES_CUSTOM_PRONUNCIATION,
    PV_NORMALIZER_TAG_ES_PUNCTUATION,
    PV_NORMALIZER_TAG_ES_CARDINAL,
    PV_NORMALIZER_TAG_ES_NEGATIVE_CARDINAL,
    PV_NORMALIZER_TAG_ES_NUMBER_RANGE_TO,
    PV_NORMALIZER_TAG_ES_ORDINAL,
    PV_NORMALIZER_TAG_ES_NEGATIVE_ORDINAL,
    PV_NORMALIZER_TAG_ES_SPECIAL_CHARACTER,
    PV_NORMALIZER_TAG_ES_ALPHANUM_SPELL_OUT,
    PV_NORMALIZER_TAG_ES_DECIMAL_POINT,
    PV_NORMALIZER_TAG_ES_DECIMAL_DIGITS,
    PV_NORMALIZER_TAG_ES_MEASUREMENT,
    PV_NORMALIZER_TAG_ES_POR_SLASH,
    PV_NORMALIZER_TAG_ES_TIME_COLON,
    PV_NORMALIZER_TAG_ES_TIME_MINUTES,
    PV_NORMALIZER_TAG_ES_TIME_HOURS,
    PV_NORMALIZER_TAG_ES_TIME_H,
    PV_NORMALIZER_TAG_ES_TIME_AM_PM,
    PV_NORMALIZER_TAG_ES_FRACTION_SLASH,
    PV_NORMALIZER_TAG_ES_DOT,
    PV_NORMALIZER_TAG_ES_COLON,
    PV_NORMALIZER_TAG_ES_ACRONYM,
    PV_NORMALIZER_TAG_ES_TOP_LEVEL_DOMAIN,
    PV_NORMALIZER_TAG_ES_CURRENCY,
    PV_NORMALIZER_TAG_ES_CURRENCY_SYMBOL,
    PV_NORMALIZER_TAG_ES_NEGATIVE_CURRENCY,
    PV_NORMALIZER_TAG_ES_ABBREVIATION,
    PV_NORMALIZER_TAG_ES_DIGITS,
    PV_NORMALIZER_TAG_ES_DIGITS_WITH_PARENTHESES,
    PV_NORMALIZER_TAG_ES_DIGITS_SEPARATOR,
    PV_NORMALIZER_TAG_ES_DATE_SEPARATOR,
    PV_NORMALIZER_TAG_ES_DATE_DAY,
    PV_NORMALIZER_TAG_ES_DATE_MONTH,
    PV_NORMALIZER_TAG_ES_DATE_YEAR,
    PV_NORMALIZER_TAG_ES_NAME_INITIAL_LETTER,
    PV_NORMALIZER_TAG_ES_NAME_INITIAL_DOT,
    PV_NORMALIZER_TAG_ES_LETTER_SPELL_OUT,
    PV_NORMALIZER_TAG_ES_CARDINAL_SPELL_OUT,
    PV_NORMALIZER_TAG_ES_SINGLE_QUOTE,
    PV_NORMALIZER_TAG_ES_SPACE,
    PV_NORMALIZER_TAG_ES_NUM_TAGS,
} pv_normalizer_token_tag_es_t;

static const float PV_NORMALIZER_TOKEN_TAG_ES_WEIGHTS[PV_NORMALIZER_TAG_ES_NUM_TAGS] = {
        0.f, // 0
        1.f, // 1
        100.f, // 2
        0.5f, // 3
        1.f, // 4
        1.f, // 5
        1.f, // 6
        1.f, // 7
        1.f, // 8
        1.f, // 9
        0.5f, // 10
        2.f, // 11
        4.f, // 12
        4.f, // 13
        2.f, // 14
        3.f, // 15
        3.f, // 16
        3.f, // 17
        3.f, // 18
        2.f, // 19
        2.f, //
        1.f, // 20,
        1.f, // 21,
        10.f, // 22,
        11.f, // 23,
        5.f, // 24
        5.f, // 25
        5.f, // 26
        5.f, // 27
        2.f, // 28
        2.f, // 29
        2.f, // 30
        5.f, // 31
        5.f, // 32
        5.f, // 33
        5.f, // 34
        2.f, // 35
        2.f, // 36
        2.f, // 37
        2.f, // 38
        2.f, // 39
        0.5f, // 40
};

#endif // PV_NORMALIZER_TAGS_ES_H
