#ifndef PV_NORMALIZER_USE_CASES_ES_H
#define PV_NORMALIZER_USE_CASES_ES_H

#include "orca/normalizer/pv_normalizer_util.h"

typedef enum { 
    PV_NORMALIZER_USE_WORD_NORMALIZER_ES = 0,
    PV_NORMALIZER_USE_CUSTOM_PRONUNCIATION_NORMALIZER_ES,
    PV_NORMALIZER_USE_PUNCTUATION_NORMALIZER_ES,
    PV_NORMALIZER_USE_CARDINAL_NORMALIZER_ES,
    PV_NORMALIZER_USE_NEGATIVE_CARDINAL_NORMALIZER_ES,
    PV_NORMALIZER_USE_NUMBER_RANGE_NORMALIZER_ES,
    PV_NORMALIZER_USE_ORDINAL_NORMALIZER_ES,
    PV_NORMALIZER_USE_NEGATIVE_ORDINAL_NORMALIZER_ES,
    PV_NORMALIZER_USE_SPECIAL_CHARACTER_NORMALIZER_ES,
    PV_NORMALIZER_USE_DECIMAL_NORMALIZER_ES,
    PV_NORMALIZER_USE_MEASUREMENT_NORMALIZER_ES,
    PV_NORMALIZER_USE_ALPHANUM_SPELL_OUT_NORMALIZER_ES,
    PV_NORMALIZER_USE_TIME_NORMALIZER_ES,
    PV_NORMALIZER_USE_FRACTION_NORMALIZER_ES,
    PV_NORMALIZER_USE_URL_NORMALIZER_ES,
    PV_NORMALIZER_USE_CURRENCY_NORMALIZER_ES,
    PV_NORMALIZER_USE_ABBREVIATION_NORMALIZER_ES,
    PV_NORMALIZER_USE_DIGITS_SEQUENCE_NORMALIZER_ES,
    PV_NORMALIZER_USE_DATE_NORMALIZER_ES,
    PV_NORMALIZER_USE_NAME_NORMALIZER_ES,
    PV_NORMALIZER_NUM_CASES_ES,
} pv_normalizer_use_cases_es_t;

extern const pv_normalizer_use_cases_es_t ALL_USE_CASES_ES[PV_NORMALIZER_NUM_CASES_ES];

#endif // PV_NORMALIZER_USE_CASES_ES_H      
