#include "orca/normalizer/en/pv_normalizer_use_cases_en.h"

const pv_normalizer_use_cases_en_t ALL_USE_CASES_EN[PV_NORMALIZER_NUM_CASES_EN] = {
        PV_NORMALIZER_USE_WORD_NORMALIZER,
        PV_NORMALIZER_USE_CUSTOM_PRONUNCIATION_NORMALIZER,
        PV_NORMALIZER_USE_PUNCTUATION_NORMALIZER,
        PV_NORMALIZER_USE_CARDINAL_NORMALIZER,
        PV_NORMALIZER_USE_NEGATIVE_CARDINAL_NORMALIZER,
        PV_NORMALIZER_USE_NUMBER_RANGE_NORMALIZER,
        PV_NORMALIZER_USE_ORDINAL_NORMALIZER,
        PV_NORMALIZER_USE_NEGATIVE_ORDINAL_NORMALIZER,
        PV_NORMALIZER_USE_SPECIAL_CHARACTER_NORMALIZER,
        PV_NORMALIZER_USE_DECIMAL_NORMALIZER,
        PV_NORMALIZER_USE_ALPHANUM_SPELL_OUT_NORMALIZER,
        PV_NORMALIZER_USE_MEASUREMENT_NORMALIZER,
        PV_NORMALIZER_USE_TIME_NORMALIZER,
        PV_NORMALIZER_USE_FRACTION_NORMALIZER,
        PV_NORMALIZER_USE_URL_NORMALIZER,
        PV_NORMALIZER_USE_CURRENCY_NORMALIZER,
        PV_NORMALIZER_USE_ABBREVIATION_NORMALIZER,
        PV_NORMALIZER_USE_DIGITS_SEQUENCE_NORMALIZER,
        PV_NORMALIZER_USE_DATE_NORMALIZER,
        PV_NORMALIZER_USE_NAME_NORMALIZER,
};
