#ifndef PV_NORMALIZER_ACRONYM_DATA_DE_H
#define PV_NORMALIZER_ACRONYM_DATA_DE_H

#define PV_NORMALIZER_NUM_ACRONYMS_DE (19)

extern const char *const PV_NORMALIZER_ACRONYMS_DE[PV_NORMALIZER_NUM_ACRONYMS_DE];

#endif // PV_NORMALIZER_ACRONYM_DATA_DE_H
