#ifndef PV_NORMALIZER_PUNCTUATION_DATA_DE_H
#define PV_NORMALIZER_PUNCTUATION_DATA_DE_H

#define PV_NORMALIZER_NUM_PUNCTUATION_DE (7)

extern const char *const PV_NORMALIZER_PUNCTUATION_DE[PV_NORMALIZER_NUM_PUNCTUATION_DE];

#endif // PV_NORMALIZER_PUNCTUATION_DATA_DE_H
