#ifndef PV_NORMALIZER_CURRENCY_DATA_DE_H
#define PV_NORMALIZER_CURRENCY_DATA_DE_H

#define PV_NORMALIZER_NUM_CURRENCIES_DE (53)

extern const char *const PV_NORMALIZER_CURRENCIES_DE[PV_NORMALIZER_NUM_CURRENCIES_DE];
extern const char *const PV_NORMALIZER_CURRENCIES_VERBALIZED_DE[PV_NORMALIZER_NUM_CURRENCIES_DE];
extern const char *const PV_NORMALIZER_SUB_CURRENCIES_VERBALIZED_DE[PV_NORMALIZER_NUM_CURRENCIES_DE];

#endif // PV_NORMALIZER_CURRENCY_DATA_DE_H