#ifndef PV_NORMALIZER_NUMBER_DATA_DE_H
#define PV_NORMALIZER_NUMBER_DATA_DE_H

#include <stdint.h>

#define PV_NORMALIZER_NUM_ORDINALS_DE (33)
#define PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_DE (31)

extern const int64_t MAX_VERBALIZED_CARDINAL_DE;

extern const int64_t MAX_MULTIPLIER_DE;
extern const char *NUMBER_RANGE_INBETWEEN_STRING_DE;

extern const char *const ONE_TO_NINETEEN_DE[20];
extern const char *const TENS_DE[9];
extern const char *const MULTIPLIERS_SINGULAR_DE[5];
extern const char *const MULTIPLIERS_PLURAL_DE[5];

extern const char *const ORDINAL_KEYS_SINGULAR_DE[PV_NORMALIZER_NUM_ORDINALS_DE];
extern const char *const ORDINAL_KEYS_PLURAL_DE[PV_NORMALIZER_NUM_ORDINALS_DE];
extern const char *const ORDINAL_VALUES_ROOT_DE[PV_NORMALIZER_NUM_ORDINALS_DE];
extern const char *const ORDINAL_VALUES_SUFFIXES_DE[12][4];

#define NORMALIZER_DE_NUM_NOMITIVE_DEFINITE_ARTICLES (3)
extern const char *const NORMALIZER_DE_NOMITIVE_DEFINITE_ARTICLES[NORMALIZER_DE_NUM_NOMITIVE_DEFINITE_ARTICLES];

#define NORMALIZER_DE_NUM_NOMITIVE_INDEFINITE_ARTICLES (2)
extern const char *const NORMALIZER_DE_NOMITIVE_INDEFINITE_ARTICLES[NORMALIZER_DE_NUM_NOMITIVE_INDEFINITE_ARTICLES];

#define NORMALIZER_DE_NUM_GENATIVE_DEFINITE_ARTICLES (2)
extern const char *const NORMALIZER_DE_GENATIVE_DEFINITE_ARTICLES[NORMALIZER_DE_NUM_GENATIVE_DEFINITE_ARTICLES];

#define NORMALIZER_DE_NUM_DATIVE_DEFINITE_ARTICLES (5)
extern const char *const NORMALIZER_DE_DATIVE_DEFINITE_ARTICLES[NORMALIZER_DE_NUM_DATIVE_DEFINITE_ARTICLES];

#define NORMALIZER_DE_NUM_DATIVE_INDEFINITE_ARTICLES (2)
extern const char *const NORMALIZER_DE_DATIVE_INDEFINITE_ARTICLES[NORMALIZER_DE_NUM_DATIVE_INDEFINITE_ARTICLES];

#define NORMALIZER_DE_NUM_ACCUSATIVE_DEFINITE_ARTICLES (1)
extern const char *const NORMALIZER_DE_ACCUSATIVE_DEFINITE_ARTICLES[NORMALIZER_DE_NUM_ACCUSATIVE_DEFINITE_ARTICLES];

#define NORMALIZER_DE_NUM_ACCUSATIVE_INDEFINITE_ARTICLES (3)
extern const char *const NORMALIZER_DE_ACCUSATIVE_INDEFINITE_ARTICLES[NORMALIZER_DE_NUM_ACCUSATIVE_INDEFINITE_ARTICLES];

extern const char *const DENOMINATOR_ORDINAL_KEYS_DE[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_DE];
extern const char *const DENOMINATOR_ORDINAL_VALUES_SINGULAR_DE[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_DE];
extern const char *const DENOMINATOR_ORDINAL_VALUES_PLURAL_DE[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_DE];

#endif // PV_NORMALIZER_NUMBER_DATA_DE_H
