#ifndef PV_NORMALIZER_DATE_DATA_DE_H
#define PV_NORMALIZER_DATE_DATA_DE_H

#define PV_NORMALIZER_NUM_MONTH_NAMES_DE (24)

extern const char *const PV_NORMALIZER_MONTH_NAMES_DE[PV_NORMALIZER_NUM_MONTH_NAMES_DE];
extern const char *const PV_NORMALIZER_MONTH_NAMES_VERBALIZED_DE[PV_NORMALIZER_NUM_MONTH_NAMES_DE];

#endif // PV_NORMALIZER_DATE_DATA_DE_H