#ifndef PV_NORMALIZER_TOP_LEVEL_DOMAIN_DE_H
#define PV_NORMALIZER_TOP_LEVEL_DOMAIN_DE_H

#include <stdbool.h>

#define PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS_DE (76)

extern const char *const PV_NORMALIZER_TOP_LEVEL_DOMAINS_DE[PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS_DE];
extern const bool PV_NORMALIZER_TOP_LEVEL_DOMAINS_IS_SPELL_OUT_DE[PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS_DE];

#endif // PV_NORMALIZER_TOP_LEVEL_DOMAIN_DE_H