#include "orca/normalizer/de/pv_normalizer_use_cases_de.h"

const pv_normalizer_use_cases_de_t ALL_USE_CASES_DE[PV_NORMALIZER_NUM_CASES_DE] = {
        PV_NORMALIZER_USE_WORD_NORMALIZER_DE,
        PV_NORMALIZER_USE_CUSTOM_PRONUNCIATION_NORMALIZER_DE,
        PV_NORMALIZER_USE_PUNCTUATION_NORMALIZER_DE,
        PV_NORMALIZER_USE_CARDINAL_NORMALIZER_DE,
        PV_NORMALIZER_USE_NEGATIVE_CARDINAL_NORMALIZER_DE,
        PV_NORMALIZER_USE_NUMBER_RANGE_NORMALIZER_DE,
        PV_NORMALIZER_USE_ORDINAL_NORMALIZER_DE,
        PV_NORMALIZER_USE_SPECIAL_CHARACTER_NORMALIZER_DE,
        PV_NORMALIZER_USE_DECIMAL_NORMALIZER_DE,
        PV_NORMALIZER_USE_MEASUREMENT_NORMALIZER_DE,
        PV_NORMALIZER_USE_ALPHANUM_SPELL_OUT_NORMALIZER_DE,
        PV_NORMALIZER_USE_TIME_NORMALIZER_DE,
        PV_NORMALIZER_USE_FRACTION_NORMALIZER_DE,
        PV_NORMALIZER_USE_URL_NORMALIZER_DE,
        PV_NORMALIZER_USE_CURRENCY_NORMALIZER_DE,
        PV_NORMALIZER_USE_ABBREVIATION_NORMALIZER_DE,
        PV_NORMALIZER_USE_DIGITS_SEQUENCE_NORMALIZER_DE,
        PV_NORMALIZER_USE_DATE_NORMALIZER_DE,
        PV_NORMALIZER_USE_NAME_NORMALIZER_DE,
};
