#ifndef PV_NORMALIZER_USE_CASES_IT_H
#define PV_NORMALIZER_USE_CASES_IT_H

#include "orca/normalizer/pv_normalizer_util.h"

typedef enum {
    PV_NORMALIZER_USE_WORD_NORMALIZER_IT = 0,
    PV_NORMALIZER_USE_CUSTOM_PRONUNCIATION_NORMALIZER_IT = 1,
    PV_NORMALIZER_USE_PUNCTUATION_NORMALIZER_IT = 2,
    PV_NORMALIZER_USE_CARDINAL_NORMALIZER_IT = 3,
    PV_NORMALIZER_USE_NEGATIVE_CARDINAL_NORMALIZER_IT = 4,
    PV_NORMALIZER_USE_NUMBER_RANGE_NORMALIZER_IT = 5,
    PV_NORMALIZER_USE_ORDINAL_NORMALIZER_IT = 6,
    PV_NORMALIZER_USE_NEGATIVE_ORDINAL_NORMALIZER_IT = 7,
    PV_NORMALIZER_USE_SPECIAL_CHARACTER_NORMALIZER_IT = 8,
    PV_NORMALIZER_USE_DECIMAL_NORMALIZER_IT = 9,
    PV_NORMALIZER_USE_MEASUREMENT_NORMALIZER_IT = 10,
    PV_NORMALIZER_USE_ALPHANUM_SPELL_OUT_NORMALIZER_IT = 11,
    PV_NORMALIZER_USE_TIME_NORMALIZER_IT = 12,
    PV_NORMALIZER_USE_FRACTION_NORMALIZER_IT = 13,
    PV_NORMALIZER_USE_URL_NORMALIZER_IT = 14,
    PV_NORMALIZER_USE_CURRENCY_NORMALIZER_IT = 15,
    PV_NORMALIZER_USE_ABBREVIATION_NORMALIZER_IT = 16,
    PV_NORMALIZER_USE_DIGITS_SEQUENCE_NORMALIZER_IT = 17,
    PV_NORMALIZER_USE_DATE_NORMALIZER_IT = 18,
    PV_NORMALIZER_USE_NAME_NORMALIZER_IT = 19,
    PV_NORMALIZER_NUM_CASES_IT = 20,
} pv_normalizer_use_cases_it_t;

extern const pv_normalizer_use_cases_it_t ALL_USE_CASES_IT[PV_NORMALIZER_NUM_CASES_IT];

#endif // PV_NORMALIZER_USE_CASES_IT_H
