#ifndef PV_NORMALIZER_USE_CASES_EN_H
#define PV_NORMALIZER_USE_CASES_EN_H

typedef enum {
    PV_NORMALIZER_USE_WORD_NORMALIZER = 0,
    PV_NORMALIZER_USE_CUSTOM_PRONUNCIATION_NORMALIZER = 1,
    PV_NORMALIZER_USE_PUNCTUATION_NORMALIZER = 2,
    PV_NORMALIZER_USE_CARDINAL_NORMALIZER = 3,
    PV_NORMALIZER_USE_NEGATIVE_CARDINAL_NORMALIZER = 4,
    PV_NORMALIZER_USE_NUMBER_RANGE_NORMALIZER = 5,
    PV_NORMALIZER_USE_ORDINAL_NORMALIZER = 6,
    PV_NORMALIZER_USE_NEGATIVE_ORDINAL_NORMALIZER = 7,
    PV_NORMALIZER_USE_SPECIAL_CHARACTER_NORMALIZER = 8,
    PV_NORMALIZER_USE_DECIMAL_NORMALIZER = 9,
    PV_NORMALIZER_USE_MEASUREMENT_NORMALIZER = 10,
    PV_NORMALIZER_USE_ALPHANUM_SPELL_OUT_NORMALIZER = 11,
    PV_NORMALIZER_USE_TIME_NORMALIZER = 12,
    PV_NORMALIZER_USE_FRACTION_NORMALIZER = 13,
    PV_NORMALIZER_USE_URL_NORMALIZER = 14,
    PV_NORMALIZER_USE_CURRENCY_NORMALIZER = 15,
    PV_NORMALIZER_USE_ABBREVIATION_NORMALIZER = 16,
    PV_NORMALIZER_USE_DIGITS_SEQUENCE_NORMALIZER = 17,
    PV_NORMALIZER_USE_DATE_NORMALIZER = 18,
    PV_NORMALIZER_USE_NAME_NORMALIZER = 19,
    PV_NORMALIZER_NUM_CASES_EN = 20,
} pv_normalizer_use_cases_en_t;

extern const pv_normalizer_use_cases_en_t ALL_USE_CASES_EN[PV_NORMALIZER_NUM_CASES_EN];

#endif // PV_NORMALIZER_USE_CASES_EN_H
