#ifndef PV_NORMALIZER_CHARACTER_DATA_ES_H
#define PV_NORMALIZER_CHARACTER_DATA_ES_H

#define PV_NORMALIZER_NUM_CHARACTERS_ES (117)

extern const char *const PV_NORMALIZER_CHARACTERS_ES[PV_NORMALIZER_NUM_CHARACTERS_ES];

#endif // PV_NORMALIZER_CHARACTER_DATA_ES_H
