#ifndef PV_NORMALIZER_NUMBER_DATA_ES_H
#define PV_NORMALIZER_NUMBER_DATA_ES_H

#include <stdint.h>

#define PV_NORMALIZER_NUM_ORDINALS_ES (51)
#define PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_ES (22)

extern const int64_t MAX_VERBALIZED_CARDINAL_ES;

extern const int64_t MAX_MULTIPLIER_ES;
extern const char *NUMBER_RANGE_INBETWEEN_STRING_ES;

extern const char *const ONE_TO_TWENTY_NINE_ES[30];
extern const char *const HUNDREDS_ES[9];
extern const char *const HUNDREDS_FEMININE_ES[9];
extern const char *const TENS_ES[9];
extern const char *const MULTIPLIERS_ES[6];
extern const char *const MULTIPLIERS_PLURAL_ES[6];

extern const char *const ORDINAL_KEYS_ES[PV_NORMALIZER_NUM_ORDINALS_ES];
extern const char *const ORDINAL_VALUES_MASCULINE_ES[PV_NORMALIZER_NUM_ORDINALS_ES];
extern const char *const ORDINAL_VALUES_FEMININE_ES[PV_NORMALIZER_NUM_ORDINALS_ES];

extern const char *const DENOMINATOR_ORDINAL_KEYS_ES[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_ES];
extern const char *const DENOMINATOR_ORDINAL_VALUES_MASCULINE_ES[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_ES];
extern const char *const DENOMINATOR_ORDINAL_VALUES_FEMININE_ES[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_ES];

#endif // PV_NORMALIZER_NUMBER_DATA_ES_H
