#ifndef PV_NORMALIZER_ACRONYM_DATA_ES_H
#define PV_NORMALIZER_ACRONYM_DATA_ES_H

#define PV_NORMALIZER_NUM_ACRONYMS_ES (4)

extern const char *const PV_NORMALIZER_ACRONYMS_ES[PV_NORMALIZER_NUM_ACRONYMS_ES];

#endif // PV_NORMALIZER_ACRONYM_DATA_ES_H