#ifndef PV_NORMALIZER_DATE_DATA_ES_H
#define PV_NORMALIZER_DATE_DATA_ES_H

#define PV_NORMALIZER_NUM_MONTH_NAMES_ES (24)

extern const char *const PV_NORMALIZER_MONTH_NAMES_ES[PV_NORMALIZER_NUM_MONTH_NAMES_ES];
extern const char *const PV_NORMALIZER_MONTH_NAMES_VERBALIZED_ES[PV_NORMALIZER_NUM_MONTH_NAMES_ES];

#endif // PV_NORMALIZER_DATE_DATA_ES_H
