#ifndef PV_NORMALIZER_TOP_LEVEL_DOMAIN_ES_H
#define PV_NORMALIZER_TOP_LEVEL_DOMAIN_ES_H

#include <stdbool.h>

#define PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS_ES (76)

extern const char *const PV_NORMALIZER_TOP_LEVEL_DOMAINS_ES[PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS_ES];
extern const bool PV_NORMALIZER_TOP_LEVEL_DOMAINS_IS_SPELL_OUT_ES[PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS_ES];

#endif // PV_NORMALIZER_TOP_LEVEL_DOMAIN_ES_H