#ifndef PV_NORMALIZER_PUNCTUATION_DATA_ES_H
#define PV_NORMALIZER_PUNCTUATION_DATA_ES_H

#define PV_NORMALIZER_NUM_PUNCTUATION_ES (9)

extern const char *const PV_NORMALIZER_PUNCTUATION_ES[PV_NORMALIZER_NUM_PUNCTUATION_ES];

#endif // PV_NORMALIZER_PUNCTUATION_DATA_ES_H
