#include "orca/normalizer/ko/pv_normalizer_data_ko/pv_normalizer_currency_data_ko.h"

const char *const PV_NORMALIZER_CURRENCIES_KO[PV_NORMALIZER_NUM_CURRENCIES_KO] = {
        "$",
        "€",
        "¥", // Note: JPY and CNY use the same unicode symbol. Currently verbalizes to YUAN
        "₪",
        "£",
        "₩",
        "₺",
        "₱",
        "₽",
        "฿",
        "₴",
        "₹",
        "¢",

        "USD",
        "EUR",
        "CAD",
        "JPY",
        "GBP",
        "AUD",
        "CHF",
        "CNY",
        "SEK",
        "NZD",
        "MXN",
        "SGD",
        "HKD",
        "NOK",
        "KRW",
        "TRY",
        "RUB",
        "INR",
        "BRL",
        "ZAR",
        "DKK",
        "PLN",
        "THB",
        "IDR",
        "MYR",
        "CZK",
        "HUF",
        "ILS",
        "ARS",
        "PHP",
        "CLP",
        "COP",
        "EGP",
        "SAR",
        "AED",
        "KWD",
        "PKR",
        "BDT",
        "NGN",
        "VES",
};

const char *const PV_NORMALIZER_CURRENCIES_VERBALIZED_KO[PV_NORMALIZER_NUM_CURRENCIES_KO] = {
        "달러",
        "유로",
        "위안",
        "세켈",
        "파운드",
        "원",
        "리라",
        "페소",
        "루블",
        "바트",
        "흐리브냐",
        "루피",
        "센트",

        "미국 달러",
        "유로",
        "캐나다 달러",
        "일본 엔",
        "영국 파운드",
        "호주 달러",
        "스위스 프랑",
        "중국 위안",
        "스웨덴 크로나",
        "뉴질랜드 달러",
        "멕시코 페소",
        "싱가포르 달러",
        "홍콩 달러",
        "노르웨이 크로네",
        "한국 원",
        "터키 리라",
        "러시아 루블",
        "인도 루피",
        "브라질 헤알",
        "남아프리카 랜드",
        "덴마크 크로네",
        "폴란드 즈워티",
        "태국 바트",
        "인도네시아 루피아",
        "말레이시아 링깃",
        "체코 코루나",
        "헝가리 포린트",
        "이스라엘 세켈",
        "아르헨티나 페소",
        "필리핀 페소",
        "칠레 페소",
        "콜롬비아 페소",
        "이집트 파운드",
        "사우디 리얄",
        "아랍에미리트 디르함",
        "쿠웨이트 디나르",
        "파키스탄 루피",
        "방글라데시 타카",
        "나이지리아 나이라",
        "베네수엘라 볼리바르",
};



const char *const PV_NORMALIZER_SUB_CURRENCIES_VERBALIZED_KO[PV_NORMALIZER_NUM_CURRENCIES_KO] = {
        "센트",
        "센트",
        "펀",
        "아고라",
        "페니",
        "센트",
        "쿠루스",
        "센티모",
        "코페크",
        "사탕",
        "코피이카",
        "파이사",
        "",

        "센트",
        "센트",
        "센트",
        "센",
        "페니",
        "센트",
        "라펜",
        "펀",
        "오레",
        "센트",
        "센타보",
        "센트",
        "센트",
        "오레",
        "센트",
        "쿠루스",
        "코페크",
        "파이사",
        "센타보",
        "센트",
        "오레",
        "그로시",
        "사탕",
        "센",
        "센",
        "헬러",
        "필러",
        "아고라",
        "센타보",
        "센티모",
        "센타보",
        "센타보",
        "파이스트르",
        "할랄라",
        "필스",
        "필스",
        "파이사",
        "포이샤",
        "코보",
        "센티모",
};
