#include "orca/normalizer/ko/pv_normalizer_data_ko/pv_normalizer_special_character_data_ko.h"
#include "orca/normalizer/pv_normalizer_data/pv_normalizer_shared_data.h"
#include <stdbool.h>
#include <stddef.h>

const char *const PV_NORMALIZER_SPECIAL_CHARACTERS_KO[PV_NORMALIZER_NUM_SPECIAL_CHARACTERS_KO] = {
        "@",
        "%",
        "&",
        "\n",
        "_",
        "(",
        ")",
        "°C",
        "ºC",
        "°F",
        "ºF",
        "°",
        "º",
        "M²",
        "M³",
        "CM²",
        "CM³",
        "MM²",
        "MM³",
        "KM²",
        "KM³",
        "DM²",
        "DM³",
        "FT²",
        "FT³",
        "YD²",
        "YD³",
        "MI²",
        "MI³",
        "KBPS",
        "MBPS",
        "MHZ",
        "GHZ",
        "RPM",
        "KCAL",
        "+",
        "=",
        "/",
        "#",
        "[",
        "]",
        EM_DASH,
        ";",
        "ㆍ",
        HORIZONTAL_BAR,
        HORIZONTAL_ELLIPSIS,
        RIGHT_DOUBLE_QUOTATION_MARK,
        LEFT_DOUBLE_QUOTATION_MARK,
};

const char *const PV_NORMALIZER_SPECIAL_CHARACTERS_VERBALIZED_KO[PV_NORMALIZER_NUM_SPECIAL_CHARACTERS_KO] = {
        "골뱅이",
        "퍼센트",
        "앤드",
        ".",
        "언더바",
        ",",
        ",",
        "섭씨 도",
        "섭씨 도",
        "화씨 도",
        "화씨 도",
        "도",
        "도",
        "제곱미터",
        "세제곱미터",
        "제곱센티미터",
        "세제곱센티미터",
        "제곱밀리미터",
        "세제곱밀리미터",
        "제곱킬로미터",
        "세제곱킬로미터",
        "제곱데시미터",
        "세제곱데시미터",
        "제곱피트",
        "세제곱피트",
        "제곱야드",
        "세제곱야드",
        "제곱마일",
        "세제곱마일",
        "초당 킬로비트",
        "초당 메가비트",
        "메가헤르츠",
        "기가헤르츠",
        "분당 회전수",
        "킬로칼로리",
        "더하기",
        "등호",
        "슬래시",
        "샵",
        ",",
        ",",
        ",",
        ",",
        ",",
        ",",
        ".",
        NULL, // Not verbalizing to double quotes due to the nature of the Korean language.
        NULL, // Not verbalizing to double quotes due to the nature of the Korean language.
};

bool const PV_NORMALIZER_SPECIAL_CHARACTERS_IS_VERBALIZED_TO_PUNCTUATION_KO[PV_NORMALIZER_NUM_SPECIAL_CHARACTERS_KO] = {
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
};
