#ifndef PV_NORMALIZER_PUNCTUATION_DATA_FR_H
#define PV_NORMALIZER_PUNCTUATION_DATA_FR_H

#define PV_NORMALIZER_NUM_PUNCTUATION_FR (7)

extern const char *const PV_NORMALIZER_PUNCTUATION_FR[PV_NORMALIZER_NUM_PUNCTUATION_FR];

#endif // PV_NORMALIZER_PUNCTUATION_DATA_FR_H
