#ifndef PV_NORMALIZER_NUMBER_DATA_FR_H
#define PV_NORMALIZER_NUMBER_DATA_FR_H

#include <stdint.h>

#define PV_NORMALIZER_NUM_ORDINALS_FR (33)
#define PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_FR (31)

extern const int64_t MAX_VERBALIZED_CARDINAL_FR;

extern const int64_t MAX_MULTIPLIER_FR;
extern const char *NUMBER_RANGE_INBETWEEN_STRING_FR;

extern const char *const ONE_TO_TWENTY_NINE_FR[30];
extern const char *const TENS_FR[9];
extern const char *const MULTIPLIERS_FR[5];

extern const char *const ORDINAL_KEYS_FR[PV_NORMALIZER_NUM_ORDINALS_FR];
extern const char *const ORDINAL_VALUES_FR[PV_NORMALIZER_NUM_ORDINALS_FR];

extern const char *const DENOMINATOR_ORDINAL_KEYS_FR[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_FR];
extern const char *const DENOMINATOR_ORDINAL_VALUES_SINGULAR_FR[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_FR];
extern const char *const DENOMINATOR_ORDINAL_VALUES_PLURAL_FR[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_FR];

#endif // PV_NORMALIZER_NUMBER_DATA_FR_H
