#ifndef PV_NORMALIZER_CHARACTER_DATA_FR_H
#define PV_NORMALIZER_CHARACTER_DATA_FR_H

#define PV_NORMALIZER_NUM_CHARACTERS_FR (133)

extern const char *const PV_NORMALIZER_CHARACTERS_FR[PV_NORMALIZER_NUM_CHARACTERS_FR];

#endif // PV_NORMALIZER_CHARACTER_DATA_FR_H
