#ifndef PV_NORMALIZER_DATE_DATA_FR_H
#define PV_NORMALIZER_DATE_DATA_FR_H

#define PV_NORMALIZER_NUM_MONTH_NAMES_FR (24)

extern const char *const PV_NORMALIZER_MONTH_NAMES_FR[PV_NORMALIZER_NUM_MONTH_NAMES_FR];
extern const char *const PV_NORMALIZER_MONTH_NAMES_VERBALIZED_FR[PV_NORMALIZER_NUM_MONTH_NAMES_FR];

#endif // PV_NORMALIZER_DATE_DATA_FR_H
