#ifndef PV_NORMALIZER_ACRONYM_DATA_FR_H
#define PV_NORMALIZER_ACRONYM_DATA_FR_H

#define PV_NORMALIZER_NUM_ACRONYMS_FR (4)

extern const char *const PV_NORMALIZER_ACRONYMS_FR[PV_NORMALIZER_NUM_ACRONYMS_FR];

#endif // PV_NORMALIZER_ACRONYM_DATA_FR_H
