#ifndef PV_NORMALIZER_TOP_LEVEL_DOMAIN_FR_H
#define PV_NORMALIZER_TOP_LEVEL_DOMAIN_FR_H

#include <stdbool.h>

#define PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS_FR (76)

extern const char *const PV_NORMALIZER_TOP_LEVEL_DOMAINS_FR[PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS_FR];
extern const bool PV_NORMALIZER_TOP_LEVEL_DOMAINS_IS_SPELL_OUT_FR[PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS_FR];

#endif // PV_NORMALIZER_TOP_LEVEL_DOMAIN_FR_H
