#ifndef PV_NORMALIZER_USE_CASES_PT_H
#define PV_NORMALIZER_USE_CASES_PT_H

#include "orca/normalizer/pv_normalizer_util.h"

typedef enum { 
    PV_NORMALIZER_USE_WORD_NORMALIZER_PT = 0,
    PV_NORMALIZER_USE_CUSTOM_PRONUNCIATION_NORMALIZER_PT = 1,
    PV_NORMALIZER_USE_PUNCTUATION_NORMALIZER_PT = 2,
    PV_NORMALIZER_USE_CARDINAL_NORMALIZER_PT = 3,
    PV_NORMALIZER_USE_NEGATIVE_CARDINAL_NORMALIZER_PT = 4,
    PV_NORMALIZER_USE_NUMBER_RANGE_NORMALIZER_PT = 5,
    PV_NORMALIZER_USE_DECIMAL_NORMALIZER_PT = 6,
    PV_NORMALIZER_USE_ALPHANUM_SPELL_OUT_NORMALIZER_PT = 7,
    PV_NORMALIZER_USE_FRACTION_NORMALIZER_PT = 8,
    PV_NORMALIZER_USE_MEASUREMENT_NORMALIZER_PT = 9,
    PV_NORMALIZER_USE_TIME_NORMALIZER_PT = 10,
    PV_NORMALIZER_USE_SPECIAL_CHARACTER_NORMALIZER_PT = 11,
    PV_NORMALIZER_USE_URL_NORMALIZER_PT = 12,
    PV_NORMALIZER_USE_CURRENCY_NORMALIZER_PT = 13,
    PV_NORMALIZER_USE_ABBREVIATION_NORMALIZER_PT = 14,
    PV_NORMALIZER_USE_DIGITS_SEQUENCE_NORMALIZER_PT = 15,
    PV_NORMALIZER_USE_DATE_NORMALIZER_PT = 16,
    PV_NORMALIZER_USE_NAME_NORMALIZER_PT = 17,
    PV_NORMALIZER_USE_ORDINAL_NORMALIZER_PT = 18,
    PV_NORMALIZER_USE_NEGATIVE_ORDINAL_NORMALIZER_PT = 19,
    PV_NORMALIZER_NUM_CASES_PT = 20,
} pv_normalizer_use_cases_pt_t;

extern const pv_normalizer_use_cases_pt_t ALL_USE_CASES_PT[PV_NORMALIZER_NUM_CASES_PT];

#endif // PV_NORMALIZER_USE_CASES_PT_H      
