#ifndef PV_NORMALIZER_WORD_CHARACTER_DATA_KO_H
#define PV_NORMALIZER_WORD_CHARACTER_DATA_KO_H

#define PV_NORMALIZER_NUM_WORD_CHARACTERS_KO (51)

extern const char *const PV_NORMALIZER_WORD_CHARACTERS_KO[PV_NORMALIZER_NUM_WORD_CHARACTERS_KO];

#endif // PV_NORMALIZER_WORD_CHARACTER_DATA_KO_H
