#ifndef PV_NORMALIZER_CURRENCY_DATA_KO_H
#define PV_NORMALIZER_CURRENCY_DATA_KO_H

#define PV_NORMALIZER_NUM_CURRENCIES_KO (53)

extern const char *const PV_NORMALIZER_CURRENCIES_KO[PV_NORMALIZER_NUM_CURRENCIES_KO];
extern const char *const PV_NORMALIZER_CURRENCIES_VERBALIZED_KO[PV_NORMALIZER_NUM_CURRENCIES_KO];
extern const char *const PV_NORMALIZER_SUB_CURRENCIES_VERBALIZED_KO[PV_NORMALIZER_NUM_CURRENCIES_KO];

#endif // PV_NORMALIZER_CURRENCY_DATA_KO_H