#ifndef PV_NORMALIZER_PUNCTUATION_DATA_KO_H
#define PV_NORMALIZER_PUNCTUATION_DATA_KO_H

#define PV_NORMALIZER_NUM_PUNCTUATION_KO (8)

extern const char *const PV_NORMALIZER_PUNCTUATION_KO[PV_NORMALIZER_NUM_PUNCTUATION_KO];

#endif // PV_NORMALIZER_PUNCTUATION_DATA_KO_H
