#ifndef PV_NORMALIZER_ACRONYM_DATA_KO_H
#define PV_NORMALIZER_ACRONYM_DATA_KO_H

#define PV_NORMALIZER_NUM_ACRONYMS_KO (4)

extern const char *const PV_NORMALIZER_ACRONYMS_KO[PV_NORMALIZER_NUM_ACRONYMS_KO];

#endif // PV_NORMALIZER_ACRONYM_DATA_KO_H