#ifndef PV_NORMALIZER_ALPHABET_DATA_KO_H
#define PV_NORMALIZER_ALPHABET_DATA_KO_H

extern const char *const PV_NORMALIZER_ALPHABET_KO[26];

extern const char *const PV_NORMALIZER_ALPHABET_WORD_KO[26];

#endif // PV_NORMALIZER_ALPHABET_DATA_KO_H