#ifndef PV_NORMALIZER_CHARACTER_DATA_KO_H
#define PV_NORMALIZER_CHARACTER_DATA_KO_H

#define PV_NORMALIZER_NUM_CHARACTERS_KO (153)

extern const char *const PV_NORMALIZER_CHARACTERS_KO[PV_NORMALIZER_NUM_CHARACTERS_KO];

#endif // PV_NORMALIZER_CHARACTER_DATA_KO_H
