import subprocess

import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm

sentences = [
    "Sorry, I didn't get that.",
    "I don't have enough information to do that.",
    "Let me check on that.",
    "Just a moment while I check that.",
    "Hmm, I can't seem to find an answer for that.",
    "I'm not sure I understand what you're asking.",
    "Let me think about that for a minute.",
    "Good question. I'll need to do some research before I can answer.",
    "I don't actually have an opinion on that.",
    "I'd rather not speculate.",
    "I don't have a definitive answer for you.",
    "Unfortunately I don't have enough information to respond.",
    "I wish I could be more helpful with that.",
    "I can look that up for you.",
    "Please rephrase your request so I can better understand.",
    "Can you provide more context so I can assist you?",
    "I'm afraid I don't have an answer for that right now.",
    "Let me do some more research and get back to you.",
    "I'm not programmed to handle that type of request just yet.",
    "Today will be sunny with a high of seventy five degrees.",
    "Expect rainy conditions throughout the day, with a high of sixty five degrees.",
    "Your alarm is set for seven AM tomorrow.",
    "I've set a recurring eight thirty AM alarm for weekdays.",
    "Here are today's top headlines from CNN: Stocks Soar to Record Highs, New Medical Breakthrough Reported.",
    "I'm sorry, I don't have access to that news source. I can search headlines from NY Times and Washington Post.",
    "The current weather is cloudy with a thirty percent chance of rain.",
    "Your evening alarm is set for nine fifteen PM",
    "Here are the latest tech headlines from CNET: New iPhone Launch, Massive Data Breach Reported.",
    "I can't find any matches for that news topic right now.",
    "Today will be windy with gusts up to thirty miles per hour and a high around sixty degrees.",
    "Your morning alarm is now set for six fourty five AM Monday to Friday.",
    "Here is an update on your requested sports news: Team Wins Big Upset, Star Player Traded.",
    "I don't have any sports news available at this time.",
    "Expect snowy conditions with two to four inches of accumulation.",
    "Your alarm for tomorrow is set for eight AM.",
    "Let me know if you want me to read any of those headlines fully.",
    "I'm afraid I don't have enough information to provide news on that topic.",
    "Today will be sunny with a high of eighty five degrees perfect for being outside.",
    "Your new alarm for six fifteen AM has been set for weekdays.",
    "The current temperature is sixty eight farenheit with clear skies and low humidity.",
    "There are no major delays on your usual route to work. Expect a twenty five minute commute.",
    "Reminder set to call John at six PM.",
    "New calendar event created for tomorrow at three PM.",
    "According to user reviews, the best restaurant nearby is \"The Red Hen\", an Italian American bistro with a four point five star rating on Google.",
    "A medium sized apple has about ninety five calories.",
    "The Los Angeles Dodgers won the twenty twenty World Series.",
    "Canberra is the capital of Australia.",
    "Joe Biden is the current President of the United States.",
    "The square root of two hundred fifty six is sixteen.",
    "The common cold is a viral infection that typically causes symptoms such as sneezing, runny nose, cough, sore throat, and fatigue.",
    "The current stock price of Apple is one hundred fourty five point zero five dollars.",
    "There are one hundred and eight ounces in a gallon.",
    "Leonardo da Vinci painted the Mona Lisa.",
    "The most populated city in the world is Tokyo, Japan.",
    "The average life expectancy in the United States is seventy eight point seven years.",
    "Some healthy breakfast ideas include overnight oats, avocado toast, smoothies, eggs, and whole grain toast with nut butter.",
    "To make a DIY face mask, you can combine ingredients such as honey, lemon juice, oatmeal.",
    "Thank you for calling Acme Corp. How may I assist you today?",
    "Please enter your account number followed by the pound sign.",
    "To speak with a representative, press zero.",
    "Your call is important to us. Please hold for the next available representative.",
    "For billing inquiries, press one. For technical support, press two.",
    "To make a payment, press one. To hear your balance, press two.",
    "To repeat this message, press nine.",
    "Our business hours are Monday through Friday from nine AM to five PM. Please call back during those hours.",
    "We're sorry, but we're currently experiencing high call volumes. Your call will be answered in the order it was received.",
    "To schedule an appointment, press one. To cancel an appointment, press two.",
    "Please hold while we transfer your call.",
    "To check the status of your order, press one. To place a new order, press two.",
    "You have reached the voicemail box of John Smith. Please leave a message after the tone.",
    "To reset your password, press one. To speak with a representative, press two.",
    "Your call may be recorded for quality assurance purposes.",
    "To speak with sales, press one. For customer service, press two.",
    "Please listen carefully as our menu options have changed.",
    "To check your account balance, press one. To hear your recent transactions, press two.",
    "We appreciate your patience. A representative will be with you shortly.",
    "For technical support, please press two. For all other inquiries, press one.",
    "Please say or enter the name of the person or department you wish to reach.",
    "To update your account information, press one. To hear your current account information, press two.",
    "To check the status of your claim, press one. To file a new claim, press two.",
    "For frequently asked questions, press one. To speak with a representative, press zero.",
    "To check your order status, press one. To track your package, press two.",
    "Please enter the last four digits of your Social Security number followed by the pound sign.",
    "Our business hours have changed. Please call back during our new hours of operation.",
    "Your call is important to us. Please stay on the line and a representative will be with you shortly.",
    "To make a reservation, press one. To cancel a reservation, press two.",
    "Please hold while we connect you to the next available representative.",
    "To speak with a manager, press zero. For all other inquiries, press one.",
    "To report a power outage, press one. For all other inquiries, press two.",
    "For account specific questions, please have your account number ready.",
    "Please wait while we verify your account information.",
    "To check your flight status, press one. To book a new flight, press two.",
    "Please enter your zip code followed by the pound sign.",
    "Our estimated wait time is ten minutes. Thank you for your patience.",
    "For product support, press one. For sales, press two.",
    "To check your account balance, press one. To make a payment, press two.",
    "To check your balance, please swipe your card or enter your account number.",
    "To speak with a live representative, press zero. For all other inquiries, please listen carefully to the following options.",
    "To report a lost or stolen card, press one. For all other inquiries, press two.",
    "To check your order status, please enter your order number followed by the pound sign.",
    "To speak with a customer service representative, please press one.",
    "For general information, press one. For specific questions, please listen carefully to the following options.",
    "To reset your PIN, press one. For all other inquiries, press two.",
    "Please enter your sixteen digit card number followed by the pound sign.",
    "To check your account balance, press one. To hear your recent transactions, press two.",
    "Your current pace is eight minute miles.",
    "You've run two point five miles so far, keep it up!",
    "Your heart rate is elevated at one hundred and sixty BPM, time to ease up.",
    "This workout has burned two hundred fifty calories for you so far.",
    "You set a new five K personal record of twenty five minutes!",
    "Your pace has slowed to twelve minute miles, let's get moving.",
    "Halfway done with this run, stay strong!",
    "Your heart rate has returned to one hundred twenty BPM in your recovery zone.",
    "Time to rehydrate, you've been exercising for fourty five minutes.",
    "Great job completing that workout! I'll sync your data to track your progress",
    "Your current heart rate is eighty two beats per minute.",
    "It's three PM, time for your daily meditation session.",
    "You've taken five thousand steps so far today, great work!",
    "I set a timer for twenty minutes for your next activity.",
    "Your average sleep quality last night was eighty percent.",
    "You have a meeting coming up in fifteen minutes.",
    "Your calendar shows your exercise class at six PM tonight.",
    "The UV index is currently nine, make sure to apply sunscreen.",
    "Your blood oxygen level is currently ninety seven percent",
    "Your headphones are now connected for music playback.",
    "Recording started.",
    "Saving video clip of the last five minutes due to sudden acceleration.",
    "Uploading video to your phone now.",
    "Location and speed data added to latest video file.",
    "Switching to night vision mode due to low lighting conditions.",
    "Entering park mode. motion detection is now active when vehicle is off.",
    "Battery at twenty percent. Please reconnect charger.",
    "Impact detected. locking video file for safety.",
    "Micro SD card is full. please format or replace.",
    "Device overheating detected. turning off to prevent damage",
    "Welcome home! The temperature is currently set to sixty degrees.",
    "Turning on the kitchen lights.",
    "I'm sorry, I don't have a device set up for the bedroom yet.",
    "The front door is unlocked.",
    "Setting thermostat to eighty degrees as requested.",
    "I don't have permission to access those camera feeds.",
    "The garage door has been open for five minutes.",
    "Playing your Spotify playlist on the living room speakers.",
    "I couldn't find any smart appliances matching that name.",
    "Your grocery list has been sent to your phone for easy access at the store.",
    "Hello Sir, how are you doing today? How can I help you?",
    "This is the customer service of emoji bank. How can I help you today?",
    "I need to check your balance. Give me one second please.",
    "I'll forward you to a colleague, please hold the line.",
    "Thank you for calling our customer support. How can I help you today?",
    "I see, so you're having issues with logging into our website. Let me take a look into that for you.",
    "Thank you for calling ClimateCare, this is Khaled. How may I assist you this evening?",
    "I see - we should be able to easily transfer your account details over to that new address.",
    "To start, could you please confirm your phone number and email address on file?",
    "Thank you. And what is the new address where you need your ClimateCare account managed?",
    "Understood. Let me just double check a few details on our end.",
    "I apologize, but it looks like an account already exists for that location under a different name.",
    "Ah I see - this must be your vacation property then! No problem, we can still connect it.",
    "Connecto customer support. Before we proceed, may I first verify your call is from number seven eight one zero four four three?",
    "I do apologize for any confusion around managing your subscription. let me clarify.",
    "Our monthly memberships auto-renew by default to prevent any lapses in service.",
    "If you would like to cancel, you'll need to select Turn Off Auto Renew in your account billing settings.",
    "Alternatively you can choose to swap to one of our annual subscription options which cost less overall.",
    "Does this help explain the process? I'm happy to walk you through making any adjustments needed.",
    "Wonderful, I've gone ahead and disabled the auto renewal as per your request. Feel free to re-enable.",
    "You're so welcome! It was my absolute pleasure. Don't hesitate to reach out if any other questions come up!",
    "Thank you for contacting ClimateCare customer support, my name is Diego. How may I be of help?",
    "I sincerely apologize for the troublesome experience. Allow me a moment to review your account history.",
    "I understand. After your move it appears the local weather driver malfunctioned leading to inaccurate readings and alerts.",
    "For English, press one.",
    "To speak with a representative, press zero.",
    "For billing questions, press two.",
    "To check the status of an order, press three",
    "To schedule a service appointment, press four.",
    "For technical support, press five.",
    "To hear these options again, press six.",
    "For all other inquiries, please stay on the line.",
    "We are currently experiencing high call volumes. Please hold for the next available agent.",
    "If you know your party's extension, you may dial it at any time.",
    "Welcome! Please select from the menu to begin.",
    "Card payment successful. Please take your receipt.",
    "Please insert cash or select another payment option.",
    "Invalid selection. Please try again or press help for assistance.",
    "Please take your items from the dispenser below.",
    "Insufficient funds entered. Please insert the remaining balance due.",
    "Your total comes to twelve dollars, please insert payment to continue.",
    "Thank you for your payment. Your transaction is processing.",
    "Machine is temporarily out of service. Please contact staff for help.",
    "Transaction cancelled. Please take your card and feel free to start again.",
    "Not sure at what point it's good to start",
    "The quick brown fox jumps over the lazy dog.",
    "Hello, how are you today?",
    "This is a sample sentence for testing.",
]
fast_sentences = [
    "She sells seashells by the seashore, the seashells she sells are surely seashells.",
    "How much wood would a woodchuck chuck if a woodchuck could chuck wood?",
    "I scream, you scream, we all scream for ice cream!",
    "Peter Piper picked a peck of pickled peppers. A peck of pickled peppers Peter Piper picked. If Peter Piper picked a peck of pickled peppers, where's the peck of pickled peppers Peter Piper picked?",
    "Can you can a can as a canner can can a can?",
    "She sells sea shells by the sea shore, but the sea shells she sells are surely sea shore shells.",
    "Imagine an imaginary menagerie manager managing an imaginary menagerie.",
    "I know I saw a kitten eating chicken in the kitchen.",
    "Whether the weather be fine or whether the weather be not, whether the weather be cold or whether the weather be hot, we'll weather the weather, whether we like it or not!",
    "Fuzzy Wuzzy was a bear, Fuzzy Wuzzy had no hair. Fuzzy Wuzzy wasn't fuzzy, was he?"
]

first_audio_lengths = []

for sentence in tqdm(fast_sentences):
    command = f"./build/release/x86_64/pv_orca_input_output_streaming_app -a 1lhrIDM8FUuBZPIORpQ3Cbbl0sDGHB9Foej1pwL3fhjIsiX7CO2QTA== -m res/param/orca_params_en_female.pv -o 0.wav -t \"{sentence}\""
    output = subprocess.check_output(command, shell=True)

    try:
        lines = output.decode().splitlines()
        for line in lines:
            if "Chunk #0: audio length:" in line:
                audio_length = float(line.split(": ")[2].split(" ")[0])
                first_audio_lengths.append(audio_length)
                break
    except:
        pass

print(first_audio_lengths)
print(f"MIN: {min(first_audio_lengths)}")
print(f"MAX: {max(first_audio_lengths)}")
print(f"STD: {np.std(first_audio_lengths)}")
print(f"MEAN: {np.mean(first_audio_lengths)}")


plt.figure(figsize=(8, 6))
plt.hist(first_audio_lengths, bins=20, edgecolor='black')
plt.xlabel('Audio Length (s)')
plt.ylabel('Frequency')
plt.title('Audio Length Histogram')
plt.grid(True)
plt.show()
