#include "orca/normalizer/ja/pv_normalizer_data_ja/pv_normalizer_top_level_domain_data_ja.h"

const char *const PV_NORMALIZER_TOP_LEVEL_DOMAINS_JA[PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS_JA] = {
        "COM",
        "ORG",
        "NET",
        "CO",
        "INFO",
        "BIZ",
        "ONLINE",
        "CLUB",
        "PRO",
        "SITE",
        "SHOP",
        "STORE",
        "APP",
        "LIVE",
        "INT",
        "MIL",
        "NEWS",
        "WIKI",
        "MOBI",
        "CAT",
};

const char *const PV_NORMALIZER_TOP_LEVEL_DOMAINS_VERBALIZED_JA[PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS_JA] = {
        "コム",
        "オーグ",
        "ネット",
        "コー",
        "インフォ",
        "ビズ",
        "オンライン",
        "クラブ",
        "プロ",
        "サイト",
        "ショップ",
        "ストア",
        "アップ",
        "ライブ",
        "インターナショナル",
        "ミル",
        "ニュース",
        "ウィキ",
        "モビ",
        "キャット",
};
