#ifndef PV_NORMALIZER_PUNCTUATION_DATA_IT_H
#define PV_NORMALIZER_PUNCTUATION_DATA_IT_H

#define PV_NORMALIZER_NUM_PUNCTUATION_IT (7)

extern const char *const PV_NORMALIZER_PUNCTUATION_IT[PV_NORMALIZER_NUM_PUNCTUATION_IT];

#endif // PV_NORMALIZER_PUNCTUATION_DATA_IT_H
