#ifndef PV_NORMALIZER_WORD_CHARACTER_DATA_IT_H
#define PV_NORMALIZER_WORD_CHARACTER_DATA_IT_H

#define PV_NORMALIZER_NUM_WORD_CHARACTERS_IT (65)
#define PV_NORMALIZER_NUM_ALPHABET_CHARACTERS_IT (64)
#define PV_NORMALIZER_NUM_VOWELS_IT (22)
#define PV_NORMALIZER_NUM_CONSONANTS_IT (42)

extern const char *const PV_NORMALIZER_WORD_CHARACTERS_IT[PV_NORMALIZER_NUM_WORD_CHARACTERS_IT];
extern const char *const PV_NORMALIZER_ALPHABET_CHARACTERS_IT[PV_NORMALIZER_NUM_ALPHABET_CHARACTERS_IT];
extern const char *const PV_NORMALIZER_VOWELS_IT[PV_NORMALIZER_NUM_VOWELS_IT];
extern const char PV_NORMALIZER_CONSONANTS_IT[PV_NORMALIZER_NUM_CONSONANTS_IT];

#endif // PV_NORMALIZER_WORD_CHARACTER_DATA_IT_H
