#ifndef PV_NORMALIZER_DATE_DATA_IT_H
#define PV_NORMALIZER_DATE_DATA_IT_H

#define PV_NORMALIZER_NUM_MONTH_NAMES_IT (12)

extern const char *const PV_NORMALIZER_MONTH_NAMES_IT[PV_NORMALIZER_NUM_MONTH_NAMES_IT];
extern const char *const PV_NORMALIZER_MONTH_NAMES_VERBALIZED_IT[PV_NORMALIZER_NUM_MONTH_NAMES_IT];

#endif // PV_NORMALIZER_DATE_DATA_IT_H
