#ifndef PV_NORMALIZER_TOP_LEVEL_DOMAIN_IT_H
#define PV_NORMALIZER_TOP_LEVEL_DOMAIN_IT_H

#include <stdbool.h>

#define PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS_IT (76)

extern const char *const PV_NORMALIZER_TOP_LEVEL_DOMAINS_IT[PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS_IT];
extern const bool PV_NORMALIZER_TOP_LEVEL_DOMAINS_IS_SPELL_OUT_IT[PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS_IT];

#endif // PV_NORMALIZER_TOP_LEVEL_DOMAIN_IT_H
