#ifndef PV_NORMALIZER_ABBREVIATIONS_DATA_IT_H
#define PV_NORMALIZER_ABBREVIATIONS_DATA_IT_H

#define PV_NORMALIZER_NUM_ABBREVIATIONS_IT (18)

extern const char *const PV_NORMALIZER_ABBREVIATIONS_IT[PV_NORMALIZER_NUM_ABBREVIATIONS_IT];
extern const char *const PV_NORMALIZER_ABBREVIATIONS_VERBALIZED_IT[PV_NORMALIZER_NUM_ABBREVIATIONS_IT];

#endif // PV_NORMALIZER_ABBREVIATIONS_DATA_IT_H
