#ifndef PV_NORMALIZER_NUMBER_DATA_IT_H
#define PV_NORMALIZER_NUMBER_DATA_IT_H

#include <stdint.h>

#define PV_NORMALIZER_NUM_ORDINALS_IT (15)
#define PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_IT (10)

extern const int64_t MAX_VERBALIZED_CARDINAL_IT;

extern const int64_t MAX_MULTIPLIER_IT;
extern const char *NUMBER_RANGE_INBETWEEN_STRING_IT;

extern const char *const ZERO_TO_NINETY_NINE_ACCENTED_IT[100];
extern const char *const ZERO_TO_NINETY_NINE_NON_ACCENTED_IT[100];
extern const char *const MULTIPLIERS_SINGULAR_IT[5];
extern const char *const MULTIPLIERS_PLURAL_IT[5];

extern const char HUNDRED_IT[];
extern const char ONE_MASCULINE_IT[];

extern const char UN[];
extern const char UNO[];
extern const char UNA[];
extern const char UN_APOSTROPHE[];


extern const char ORDINAL_SUFFIX_MASCULINE_IT[];
extern const char ORDINAL_SUFFIX_FEMININE_IT[];

extern const int32_t ORDINAL_SUFFIX_MASCULINE_LENGTH_IT;
extern const int32_t ORDINAL_SUFFIX_FEMININE_LENGTH_IT;


extern const char *const ORDINAL_KEYS_IT[PV_NORMALIZER_NUM_ORDINALS_IT];
extern const char *const ORDINAL_VALUES_MASCULINE_IT[PV_NORMALIZER_NUM_ORDINALS_IT];
extern const char *const ORDINAL_VALUES_FEMININE_IT[PV_NORMALIZER_NUM_ORDINALS_IT];

extern const char *const DENOMINATOR_ORDINAL_KEYS_IT[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_IT];
extern const char *const DENOMINATOR_ORDINAL_VALUES_SINGULAR_IT[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_IT];
extern const char *const DENOMINATOR_ORDINAL_VALUES_PLURAL_IT[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS_IT];

#endif // PV_NORMALIZER_NUMBER_DATA_IT_H
