#ifndef PV_NORMALIZER_ACRONYM_DATA_IT_H
#define PV_NORMALIZER_ACRONYM_DATA_IT_H

#define PV_NORMALIZER_NUM_ACRONYMS_IT (4)

extern const char *const PV_NORMALIZER_ACRONYMS_IT[PV_NORMALIZER_NUM_ACRONYMS_IT];

#endif // PV_NORMALIZER_ACRONYM_DATA_IT_H
