#ifndef PV_NORMALIZER_ACRONYM_DATA_EN_H
#define PV_NORMALIZER_ACRONYM_DATA_EN_H

#define PV_NORMALIZER_NUM_ACRONYMS (4)

extern const char *const PV_NORMALIZER_ACRONYMS[PV_NORMALIZER_NUM_ACRONYMS];

#endif // PV_NORMALIZER_ACRONYM_DATA_EN_H