#ifndef PV_NORMALIZER_ABBREVIATIONS_DATA_EN_H
#define PV_NORMALIZER_ABBREVIATIONS_DATA_EN_H

#define PV_NORMALIZER_NUM_ABBREVIATIONS (53)
#define PV_NORMALIZER_NUM_PARTIAL_ABBREVIATIONS (6)

extern const char *const PV_NORMALIZER_ABBREVIATIONS[PV_NORMALIZER_NUM_ABBREVIATIONS];
extern const char *const PV_NORMALIZER_PARTIAL_ABBREVIATIONS[PV_NORMALIZER_NUM_PARTIAL_ABBREVIATIONS];
extern const char *const PV_NORMALIZER_ABBREVIATIONS_VERBALIZED[PV_NORMALIZER_NUM_ABBREVIATIONS];

#endif // PV_NORMALIZER_ABBREVIATIONS_DATA_EN_H
