#ifndef PV_NORMALIZER_TOP_LEVEL_DOMAIN_EN_H
#define PV_NORMALIZER_TOP_LEVEL_DOMAIN_EN_H

#include <stdbool.h>

#define PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS (76)

extern const char *const PV_NORMALIZER_TOP_LEVEL_DOMAINS[PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS];
extern const bool PV_NORMALIZER_TOP_LEVEL_DOMAINS_IS_SPELL_OUT[PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS];

#endif // PV_NORMALIZER_TOP_LEVEL_DOMAIN_EN_H