#ifndef PV_NORMALIZER_DATE_DATA_EN_H
#define PV_NORMALIZER_DATE_DATA_EN_H

#define PV_NORMALIZER_NUM_MONTH_NAMES (24)

extern const char *const PV_NORMALIZER_MONTH_NAMES[PV_NORMALIZER_NUM_MONTH_NAMES];
extern const char *const PV_NORMALIZER_MONTH_NAMES_VERBALIZED[PV_NORMALIZER_NUM_MONTH_NAMES];

#endif // PV_NORMALIZER_DATE_DATA_EN_H
