#ifndef PV_NORMALIZER_PUNCTUATION_DATA_EN_H
#define PV_NORMALIZER_PUNCTUATION_DATA_EN_H

#define PV_NORMALIZER_NUM_PUNCTUATION_EN (7)

extern const char *const PV_NORMALIZER_PUNCTUATION_EN[PV_NORMALIZER_NUM_PUNCTUATION_EN];

#endif // PV_NORMALIZER_PUNCTUATION_DATA_EN_H
