#ifndef PV_NORMALIZER_NUMBER_DATA_EN_H
#define PV_NORMALIZER_NUMBER_DATA_EN_H

#include <stdint.h>

#define PV_NORMALIZER_NUM_ORDINALS (33)
#define PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS (31)

extern const int64_t MAX_VERBALIZED_CARDINAL;

extern const int64_t MAX_MULTIPLIER;
extern const char *NUMBER_RANGE_INBETWEEN_STRING;

extern const char *const ONE_TO_NINETEEN[20];
extern const char *const TENS[9];
extern const char *const MULTIPLIERS[5];

extern const char *const ORDINAL_KEYS[PV_NORMALIZER_NUM_ORDINALS];
extern const char *const ORDINAL_VALUES[PV_NORMALIZER_NUM_ORDINALS];

extern const char *const DENOMINATOR_ORDINAL_KEYS[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS];
extern const char *const DENOMINATOR_ORDINAL_VALUES_SINGULAR[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS];
extern const char *const DENOMINATOR_ORDINAL_VALUES_PLURAL[PV_NORMALIZER_NUM_DENOMINATOR_ORDINALS];

#endif // PV_NORMALIZER_NUMBER_DATA_EN_H
