#ifndef PV_NORMALIZER_ACRONYM_DATA_PT_H
#define PV_NORMALIZER_ACRONYM_DATA_PT_H

#define PV_NORMALIZER_NUM_ACRONYMS_PT (4)

extern const char *const PV_NORMALIZER_ACRONYMS_PT[PV_NORMALIZER_NUM_ACRONYMS_PT];

#endif // PV_NORMALIZER_ACRONYM_DATA_PT_H