#ifndef PV_NORMALIZER_TOP_LEVEL_DOMAIN_PT_H
#define PV_NORMALIZER_TOP_LEVEL_DOMAIN_PT_H

#include <stdbool.h>

#define PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS_PT (76)

extern const char *const PV_NORMALIZER_TOP_LEVEL_DOMAINS_PT[PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS_PT];
extern const bool PV_NORMALIZER_TOP_LEVEL_DOMAINS_IS_SPELL_OUT_PT[PV_NORMALIZER_NUM_TOP_LEVEL_DOMAINS_PT];

#endif // PV_NORMALIZER_TOP_LEVEL_DOMAIN_PT_H