#ifndef PV_NORMALIZER_DATE_DATA_PT_H
#define PV_NORMALIZER_DATE_DATA_PT_H

#define PV_NORMALIZER_NUM_MONTH_NAMES_PT (24)

extern const char *const PV_NORMALIZER_MONTH_NAMES_PT[PV_NORMALIZER_NUM_MONTH_NAMES_PT];
extern const char *const PV_NORMALIZER_MONTH_NAMES_VERBALIZED_PT[PV_NORMALIZER_NUM_MONTH_NAMES_PT];

#endif // PV_NORMALIZER_DATE_DATA_PT_H
