#ifndef PV_NORMALIZER_PUNCTUATION_DATA_PT_H
#define PV_NORMALIZER_PUNCTUATION_DATA_PT_H

#define PV_NORMALIZER_NUM_PUNCTUATION_PT (7)

extern const char *const PV_NORMALIZER_PUNCTUATION_PT[PV_NORMALIZER_NUM_PUNCTUATION_PT];

#endif // PV_NORMALIZER_PUNCTUATION_DATA_PT_H
