#include "orca/normalizer/it/pv_normalizer_use_cases_it.h"

const pv_normalizer_use_cases_it_t ALL_USE_CASES_IT[PV_NORMALIZER_NUM_CASES_IT] = {
        PV_NORMALIZER_USE_WORD_NORMALIZER_IT,
        PV_NORMALIZER_USE_CUSTOM_PRONUNCIATION_NORMALIZER_IT,
        PV_NORMALIZER_USE_PUNCTUATION_NORMALIZER_IT,
        PV_NORMALIZER_USE_CARDINAL_NORMALIZER_IT,
        PV_NORMALIZER_USE_NEGATIVE_CARDINAL_NORMALIZER_IT,
        PV_NORMALIZER_USE_NUMBER_RANGE_NORMALIZER_IT,
        PV_NORMALIZER_USE_ORDINAL_NORMALIZER_IT,
        PV_NORMALIZER_USE_NEGATIVE_ORDINAL_NORMALIZER_IT,
        PV_NORMALIZER_USE_SPECIAL_CHARACTER_NORMALIZER_IT,
        PV_NORMALIZER_USE_DECIMAL_NORMALIZER_IT,
        PV_NORMALIZER_USE_MEASUREMENT_NORMALIZER_IT,
        PV_NORMALIZER_USE_ALPHANUM_SPELL_OUT_NORMALIZER_IT,
        PV_NORMALIZER_USE_TIME_NORMALIZER_IT,
        PV_NORMALIZER_USE_FRACTION_NORMALIZER_IT,
        PV_NORMALIZER_USE_URL_NORMALIZER_IT,
        PV_NORMALIZER_USE_CURRENCY_NORMALIZER_IT,
        PV_NORMALIZER_USE_ABBREVIATION_NORMALIZER_IT,
        PV_NORMALIZER_USE_DIGITS_SEQUENCE_NORMALIZER_IT,
        PV_NORMALIZER_USE_DATE_NORMALIZER_IT,
        PV_NORMALIZER_USE_NAME_NORMALIZER_IT,
};
