source 'https://cdn.cocoapods.org/'
platform :ios, '13.0'

target 'OrcaAppTest' do
  pod 'Orca-iOS', '~> 1.0.0'
end

target 'OrcaAppTestUITests' do
  pod 'Orca-iOS', '~> 1.0.0'
end

target 'PerformanceTest' do
  pod 'Orca-iOS', '~> 1.0.0'
end
