source 'https://cdn.cocoapods.org/'
platform :ios, '13.0'

target 'OrcaAppTest' do
  pod 'Orca-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/orca/ios-handle-apostrophes/binding/ios/Orca-iOS.podspec'
end

target 'OrcaAppTestUITests' do
  pod 'Orca-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/orca/ios-handle-apostrophes/binding/ios/Orca-iOS.podspec'
end

target 'PerformanceTest' do
  pod 'Orca-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/orca/ios-handle-apostrophes/binding/ios/Orca-iOS.podspec'
end
