#ifndef PV_NORMALIZER_USE_CASES_DE_H
#define PV_NORMALIZER_USE_CASES_DE_H

#include "orca/normalizer/pv_normalizer_util.h"

typedef enum {
    PV_NORMALIZER_USE_WORD_NORMALIZER_DE = 0,
    PV_NORMALIZER_USE_CUSTOM_PRONUNCIATION_NORMALIZER_DE = 1,
    PV_NORMALIZER_USE_PUNCTUATION_NORMALIZER_DE = 2,
    PV_NORMALIZER_USE_CARDINAL_NORMALIZER_DE = 3,
    PV_NORMALIZER_USE_NEGATIVE_CARDINAL_NORMALIZER_DE = 4,
    PV_NORMALIZER_USE_NUMBER_RANGE_NORMALIZER_DE = 5,
    PV_NORMALIZER_USE_ORDINAL_NORMALIZER_DE = 6,
    PV_NORMALIZER_USE_SPECIAL_CHARACTER_NORMALIZER_DE = 7,
    PV_NORMALIZER_USE_DECIMAL_NORMALIZER_DE = 8,
    PV_NORMALIZER_USE_MEASUREMENT_NORMALIZER_DE = 9,
    PV_NORMALIZER_USE_ALPHANUM_SPELL_OUT_NORMALIZER_DE = 10,
    PV_NORMALIZER_USE_TIME_NORMALIZER_DE = 11,
    PV_NORMALIZER_USE_FRACTION_NORMALIZER_DE = 12,
    PV_NORMALIZER_USE_URL_NORMALIZER_DE = 13,
    PV_NORMALIZER_USE_CURRENCY_NORMALIZER_DE = 14,
    PV_NORMALIZER_USE_ABBREVIATION_NORMALIZER_DE = 15,
    PV_NORMALIZER_USE_DIGITS_SEQUENCE_NORMALIZER_DE = 16,
    PV_NORMALIZER_USE_DATE_NORMALIZER_DE = 17,
    PV_NORMALIZER_USE_NAME_NORMALIZER_DE = 18,
    PV_NORMALIZER_NUM_CASES_DE = 19,
} pv_normalizer_use_cases_de_t;

extern const pv_normalizer_use_cases_de_t ALL_USE_CASES_DE[PV_NORMALIZER_NUM_CASES_DE];

#endif // PV_NORMALIZER_USE_CASES_DE_H
