#include "orca/normalizer/fr/pv_normalizer_use_cases_fr.h"

const pv_normalizer_use_cases_fr_t ALL_USE_CASES_FR[PV_NORMALIZER_NUM_CASES_FR] = {
        PV_NORMALIZER_USE_WORD_NORMALIZER_FR,
        PV_NORMALIZER_USE_CUSTOM_PRONUNCIATION_NORMALIZER_FR,
        PV_NORMALIZER_USE_PUNCTUATION_NORMALIZER_FR,
        PV_NORMALIZER_USE_CARDINAL_NORMALIZER_FR,
        PV_NORMALIZER_USE_NEGATIVE_CARDINAL_NORMALIZER_FR,
        PV_NORMALIZER_USE_NUMBER_RANGE_NORMALIZER_FR,
        PV_NORMALIZER_USE_ORDINAL_NORMALIZER_FR,
        PV_NORMALIZER_USE_NEGATIVE_ORDINAL_NORMALIZER_FR,
        PV_NORMALIZER_USE_SPECIAL_CHARACTER_NORMALIZER_FR,
        PV_NORMALIZER_USE_DECIMAL_NORMALIZER_FR,
        PV_NORMALIZER_USE_ALPHANUM_SPELL_OUT_NORMALIZER_FR,
        PV_NORMALIZER_USE_MEASUREMENT_NORMALIZER_FR,
        PV_NORMALIZER_USE_TIME_NORMALIZER_FR,
        PV_NORMALIZER_USE_FRACTION_NORMALIZER_FR,
        PV_NORMALIZER_USE_URL_NORMALIZER_FR,
        PV_NORMALIZER_USE_CURRENCY_NORMALIZER_FR,
        PV_NORMALIZER_USE_ABBREVIATION_NORMALIZER_FR,
        PV_NORMALIZER_USE_DIGITS_SEQUENCE_NORMALIZER_FR,
        PV_NORMALIZER_USE_DATE_NORMALIZER_FR,
        PV_NORMALIZER_USE_NAME_NORMALIZER_FR,
};
