name: Android Demos

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/android-demos.yml'
      - 'demo/android/**'
      - '!demo/android/OrcaDemo/README.md'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - '.github/workflows/android-demos.yml'
      - 'demo/android/**'
      - '!demo/android/OrcaDemo/README.md'

jobs:
  build-orca-demo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/android/OrcaDemo

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build
        run: ./gradlew assembleDebug
