name: Node.js

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/nodejs.yml'
      - 'binding/nodejs/**'
      - '!binding/nodejs/README.md'
      - 'lib/common/**'
      - 'lib/node/**'
      - 'resources/.test/**'

  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+*' ]
    paths:
      - '.github/workflows/nodejs.yml'
      - 'binding/nodejs/**'
      - '!binding/nodejs/README.md'
      - 'lib/common/**'
      - 'lib/node/**'
      - 'resources/.test/**'

defaults:
  run:
    working-directory: binding/nodejs

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        device: [cpu:1, cpu]
        node-version: [18.x, 20.x, 22.x, 24.x]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: mac
          - os: windows-latest
            platform: windows

    env:
      PLATFORM_NAME: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test test/index.test.ts --access_key=${{secrets.PV_VALID_ACCESS_KEY}} --device=${{ matrix.device }}

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        device: [best]
        machine: [ rpi3-32, rpi3-64, rpi4-32, rpi4-64, rpi5-64, pv-windows-arm64 ]
        include:
          - device: gpu
            machine: pv-linux
            platform: linux
          - device: gpu
            machine: pv-windows
            platform: windows
          - device: gpu
            machine: pv-ios
            platform: ios
          - machine: rpi3-32
            platform: raspberry-pi3
          - machine: rpi3-64
            platform: raspberry-pi3-64
          - machine: rpi4-32
            platform: raspberry-pi4
          - machine: rpi4-64
            platform: raspberry-pi4-64
          - machine: rpi5-64
            platform: raspberry-pi5-64
          - machine: pv-windows-arm64
            platform: windows

    env:
      PLATFORM_NAME: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test test/index.test.ts --access_key=${{secrets.PV_VALID_ACCESS_KEY}} --device=${{ matrix.device }}
