name: Python

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/python.yml'
      - 'binding/python/**'
      - '!binding/python/README.md'
      - 'lib/common/**'
      - 'lib/linux/**'
      - 'lib/mac/**'
      - 'lib/raspberry-pi/**'
      - 'lib/windows/**'
      - 'resources/.test/**'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+*' ]
    paths:
      - '.github/workflows/python.yml'
      - 'binding/python/**'
      - '!binding/python/README.md'
      - 'lib/common/**'
      - 'lib/linux/**'
      - 'lib/mac/**'
      - 'lib/raspberry-pi/**'
      - 'lib/windows/**'
      - 'resources/.test/**'

defaults:
  run:
    working-directory: binding/python

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        device: [ cpu:1, cpu ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ '3.9', '3.10', '3.11', '3.12', '3.13', '3.14' ]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: windows
          - os: macos-latest
            platform: mac

    env:
      PLATFORM_NAME: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pre-build dependencies
        run: python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test
        continue-on-error: true
        run: python3 test_orca.py --access-key ${{secrets.PV_VALID_ACCESS_KEY}} --device ${{ matrix.device }}

      - name: Upload output artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-debug-${{ github.run_attempt }}
          path: binding/python/out/
          if-no-files-found: warn
          retention-days: 5

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        device: [ best ]
        machine: [ rpi3-32, rpi3-64, rpi4-32, rpi4-64, rpi5-64, pv-windows-arm64, pv-linux, pv-windows, pv-ios ]
        include:
          - machine: rpi3-32
            platform: raspberry-pi3
          - machine: rpi3-64
            platform: raspberry-pi3-64
          - machine: rpi4-32
            platform: raspberry-pi4
          - machine: rpi4-64
            platform: raspberry-pi4-64
          - machine: rpi5-64
            platform: raspberry-pi5-64
          - machine: pv-windows-arm64
            platform: windows
          - machine: pv-linux
            platform: linux
          - machine: pv-windows
            platform: windows
          - machine: pv-ios
            platform: ios

    env:
      PLATFORM_NAME: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python virtualenv (*nix)
        if: ${{ matrix.machine != 'pv-windows' && matrix.machine != 'pv-windows-igpu' && matrix.machine != 'pv-windows-arm64' }}
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Setup Python virtualenv (windows)
        if: ${{ matrix.machine == 'pv-windows' || matrix.machine == 'pv-windows-igpu' || matrix.machine == 'pv-windows-arm64' }}
        run: |
          python3 -m venv .venv --symlinks
          .venv\Scripts\activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Pre-build dependencies
        run: python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test
        continue-on-error: true
        run: python3 test_orca.py --access-key ${{secrets.PV_VALID_ACCESS_KEY}} --device ${{ matrix.device }}
