name: Web Codestyle

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**/web/*.js'
      - '**/web/*.ts'
      - '.github/workflows/web-codestyle.yml'
  pull_request:
    # TODO: delete "orca-prepare-v0.2" before release
    branches: [ main, 'v[0-9]+.[0-9]+', 'orca-prepare-v0.2' ]
    paths:
      - '**/web/*.js'
      - '**/web/*.ts'
      - '.github/workflows/web-codestyle.yml'

jobs:
  check-web-codestyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Pre-build dependencies
        run: npm install yarn

      - name: Run Binding Linter
        run: yarn && yarn lint
        working-directory: binding/web
