name: Web Demos

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'demo/web/**'
      - '!demo/web/README.md'
      - '.github/workflows/web-demos.yml'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'demo/web/**'
      - '!demo/web/README.md'
      - '.github/workflows/web-demos.yml'

defaults:
  run:
    working-directory: demo/web

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 20.x ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

#### REMOVE AFTER RELEASE ####

      - name: Install SDK dependencies
        run: yarn install
        working-directory: binding/web

      - name: Copy libs
        run: yarn copywasm
        working-directory: binding/web

      - name: Build SDK
        run: yarn build
        working-directory: binding/web

####

      - name: Pre-build dependencies
        run: npm install yarn

      - name: Install dependencies
        run: yarn install
